### PR TITLE
C++: Fix external boost, icu and xerces to build on Windows

### PR DESCRIPTION
**Pull request by rleigh-dundee**
This is the second part of https://github.com/openmicroscopy/bioformats/pull/1859

- Propagate cmake options to subsidiary bioformats build
- Update helper scripts to propagate all toolchain and related cmake settings to subsidiary builds
- Update boost, icu and xerces to build on Windows

--------

Testing:

- Options such as `qtgui`, `sphinx` and `doxygen` can now be set when running cmake with `-Dbioformats-superbuild=ON` and they will be set when running the subsidiary bioformats build.  This can be tested on any Unix-like system.

- Check https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild/ (qtgui and options propagation will make cod components green)

- Check https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/ (all green)

### CODE REVIEW

**Comment by joshmoore** [comment]
```
make[1]: Leaving directory `/home/travis/build/openmicroscopy/bioformats/cpp/build/CMakeFiles/CMakeTmp'
make[1]: *** [CMakeFiles/cmTryCompileExec2628997385.dir/TIFF_HAVE_TMSIZE_T.c.o] Error 1
...
make: *** No targets specified and no makefile found.  Stop.
The command "./tools/test-build $BUILD" exited with 2.
Done. Your build exited with 1.
```
says travis.

**Comment by rleigh-dundee** [comment]
@joshmoore I'm not certain that's the error; there are a bunch of expected failures from feature tests, and this is working on every platform I've tested on (Windows, Linux, MacOS, BSD), and we haven't touched the standard build.  I'll have to test on Ubuntu 12.04 directly to see where the failure is.

**Comment by rleigh-dundee** [comment]
Note: https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/ (greeen) and https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild/ (waiting rerun after scc merge)

**Comment by rleigh-dundee** [comment]
This mornings merge build didn't include the last (typo only) commit, but the superbuild jobs were all green last night bar perch as noted above.  I've restarted these two builds after @sbesson's new bioformats trigger job ran, plus merge-cpp.  Note that VS2012 is in the -win matrix but not expected to pass (the "11") column; "12" is VS2013.

**Comment by rleigh-dundee** [comment]
VS2013 green in https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/ (2012 is red, but is not yet supported by the superbuild).

**Comment by joshmoore** [comment]
@rleigh-dundee -- thoughts on removing the red configurations from https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild/ then?

**Comment by rleigh-dundee** [comment]
@joshmoore None of the failures are due to the build being broken.  The recent one is due to the SourceForge download being broken, and previous to that are I think intermittent space issues, perhaps when another build is also using a lot of space; I think I added throttling for helping with that.

**Pull request merged**
