### PR TITLE
MRC: add signed bytes support

### PR DESCRIPTION
**Pull request by sbesson**
See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7757&p=15458#p15458 and http://bio3d.colorado.edu/imod/doc/mrc_format.txt.

According to the MRC specification, mode 0 can correspond to `int8` data depending on the value of `imodStamp`. At the moment MRCReader is imposing `uint8`. This PR adds support for `int8` mrc data by adding an extra check for mode 0 and removing the block which flips the pixel type to unsigned bytes depending on the maximum and minimum pixel values.

### CODE REVIEW

**Comment by sbesson** [comment]
Marking as exclude since https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-repository-subset/10/ is failing on a couple of sample files.

**Comment by sbesson** [comment]
Closing and re-opening to use the fix from #1657

**Comment by will-moore** [comment]
Image and pixel range look good.

screen shot 2015-03-12 at 11 05 02

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
