### PR TITLE
TIFF: expand single-tile special case

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7750 and https://trello.com/c/urm1ZpPz/144-threaded-jpeg-2000.

To test, download the file linked on the forum thread, uncompress it and import into OMERO.  Pyramid generation should occur without an exception, and is expected to complete in under 10 minutes.

### CODE REVIEW

**Comment by mtbc** [comment]
An enormous improvement. :+1: Will be great to have this in for 5.1.0.

**Comment by mtbc** [comment]
I should add, I tested it locally. I've no idea why travis hasn't run for this.

**Comment by sbesson** [comment]
Good point @mtbc. closed and re-opened to re-rigger Travis hook.

**Comment by mtbc** [comment]
Thanks! Looks like it now needs a kick.

**Comment by joshmoore** [comment]
```
pkg_resources.VersionConflict: (pep8 1.6.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pep8<1.6,>=1.5.7'))
The command "./tools/test-build $BUILD" exited with 1.
```

**Comment by sbesson** [comment]
See https://github.com/openmicroscopy/bioformats/pull/1653

**Comment by sbesson** [comment]
Alternatively, this PR seems to be at the origin of the pyramid generation performance improvement described in http://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7751#p15460.

**Comment by mtbc** [comment]
That'd be my guess.

**Comment by melissalinkert** [comment]
One more commit pushed for https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-openbytes-performance/424/

**Comment by sbesson** [comment]
Closing and re-opening to use the fix from #1657

**Comment by sbesson** [comment]
Re-tested using both sample files mentioned in the PR. The stitched TIFF files all completed with similar metrics as the one measured in  60c6033. The large LSM file, completed in ~5min.

```
$ grep HANDLED var/log/PixelData-0.log 
2015-03-12 05:11:01,682 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-1) HANDLED EventLog:55421(entityId=1282) [25638 ms.]
2015-03-12 09:33:48,376 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-1) HANDLED EventLog:55422(entityId=1373) [24301 ms.]
2015-03-12 09:33:48,379 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-5) HANDLED EventLog:55424(entityId=1374) [24312 ms.]
2015-03-12 09:34:11,350 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-4) HANDLED EventLog:55426(entityId=1375) [22918 ms.]
2015-03-12 09:34:11,634 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-1) HANDLED EventLog:55432(entityId=1371) [23202 ms.]
2015-03-12 09:34:35,292 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-5) HANDLED EventLog:55435(entityId=1372) [23587 ms.]
2015-03-12 10:24:31,953 INFO  [ ome.services.pixeldata.PixelDataHandler] (2-thread-3) HANDLED EventLog:65672(entityId=1376) [283912 ms.]
```

https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-openbytes-performance/425/ is also green. Ready to merge.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
