### PR TITLE
linking grouping files to pattern file page

### PR DESCRIPTION
**Pull request by hflynn**
Requested/suggested by @joshmoore on https://trello.com/c/X4OxB2FS/385-minor-cross-link-patterns
Although this page is aimed at ImageJ users, the cross-link may also help people searching for the functionality to find the content they need.

### CODE REVIEW

**Comment by mtbc** [comment]
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.1-staging/users/imagej/load-images.html#group-files-with-similar-names.

**Comment by mtbc** [comment]
Good to merge.

**Comment by hflynn** [comment]
Shall I rebase this onto develop?

**Comment by sbesson** [comment]
@hflynn: yes we are rebasing `dev_5_1` PRs to develop now we split.

**Comment by hflynn** [comment]
--rebased-to #2120

**Pull request merged**
