### PR TITLE
bump model doc reference to new 5.2 OMERO

### PR DESCRIPTION
**Pull request by mtbc**
Effects https://trello.com/c/lUQDSthL/81-update-model-docs-to-point-at-omero-5-2-docs. Staged at http://www.openmicroscopy.org/site/support/bio-formats5.1-staging/users/index.html#omero.

--no-rebase

### CODE REVIEW

**Comment by hflynn** [comment]
Hi @mtbc great of you to be helpful, but this isn't actually the change I had in mind - it is the formats folder of the ome-documentation repo that I meant not Bio-Formats.

**Comment by mtbc** [comment]
Ha. Is this change useful or not?

**Comment by hflynn** [comment]
Probably not just now. I need to check where OMERO docs links occur but now we've decoupled, changing it to a version numberless reference so it just always points to the latest release is probably best.

**Comment by mtbc** [comment]
Okay, closing then. Happy to also close https://github.com/openmicroscopy/ome-documentation/pull/1302 if that's also not what's required.

**Pull request closed without merging**
