### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by melissalinkert**
This removes a handful of methods that were deprecated in 5.0 (or earlier) and which are now unused.

See https://trello.com/c/iNieNBuZ/77-remove-deprecated-methods

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-build/ICE=3.4,jdk=7_LATEST,label=trout/394/console, this requires a companion openmicroscopy PR. Labelling as breaking.

```
03:58:47 /opt/hudson/workspace/OMERO-5.1-merge-build/src/components/blitz/src/ome/formats/OMEROMetadataStoreClient.java:6767: error: method does not override or implement a method from a supertype
03:58:47     @Override
03:58:47     ^
```

**Comment by melissalinkert** [comment]
Corresponding OMERO PR opened: https://github.com/openmicroscopy/openmicroscopy/pull/3422

**Comment by rleigh-dundee** [comment]
Removals all look fine.  Please merge if green.

**Comment by sbesson** [comment]
Thanks. Merging.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
