### PR TITLE
Fixes for less common Woolz data types

### PR DESCRIPTION
**Pull request by melissalinkert**
This should allow ```ts14-cpd.wlz``` to import, as well as preventing segfaults (and thus server restarts) when importing ```ts14-tiled.wlz```.  The two files that are now known to not import are ```ts14-tiled.wlz``` and ```EMA53_TS17_mesh.wlz```.  I haven't found a suitable way to get either file working though - I suspect that some enhancements may be needed at the JWlz level.

In any case, all of the Woolz test data that we have is now in ```from_skyking/woolz``` and should be successfully tested by the merge builds.

/cc @sbesson

### CODE REVIEW

**Comment by sbesson** [comment]
As mentioned, the `ts14-cpd.wlz` is now fixed 

```
$ ./showinf -version && ./showinf -nopix /ome/data_repo/from_skyking/woolz/ts14-cpd.wlz 
Version: 5.1.0-m3
VCS revision: b97e94a
Build date: 16 December 2014
Checking file format [Woolz]
Initializing reader
WlzReader initializing /ome/data_repo/from_skyking/woolz/ts14-cpd.wlz
Exception in thread "main" loci.formats.FormatException: Unable to determine Woolz object value type (uk.ac.mrc.hgu.Wlz.WlzException: WLZ_ERR_OBJECT_TYPE)
	at loci.formats.services.WlzServiceImpl.openRead(WlzServiceImpl.java:518)
	at loci.formats.services.WlzServiceImpl.open(WlzServiceImpl.java:167)
	at loci.formats.in.WlzReader.initFile(WlzReader.java:162)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:823)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:641)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:988)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1070)
```

vs with the merge build

```
$ ./showinf -version && ./showinf -nopix /ome/data_repo/from_skyking/woolz/ts14-cpd.wlz 
Version: 5.1.0-DEV
VCS revision: 09a78d0
Build date: 5 February 2015
Checking file format [Woolz]
Initializing reader
WlzReader initializing /ome/data_repo/from_skyking/woolz/ts14-cpd.wlz
Initialization took 0.313s

Reading core metadata
Filename = /ome/data_repo/from_skyking/woolz/ts14-cpd.wlz
Series count = 1
```

and the tiled image throws an exception.

```
$ ./showinf -version && ./showinf -nopix /ome/data_repo/from_skyking/woolz/ts14-tiled.wlz 
Version: 5.1.0-DEV
VCS revision: 09a78d0
Build date: 5 February 2015
Checking file format [Woolz]
Initializing reader
WlzReader initializing /ome/data_repo/from_skyking/woolz/ts14-tiled.wlz
Exception in thread "main" loci.formats.FormatException: Value table data not supported
	at loci.formats.services.WlzServiceImpl.openRead(WlzServiceImpl.java:531)
	at loci.formats.services.WlzServiceImpl.open(WlzServiceImpl.java:167)
	at loci.formats.in.WlzReader.initFile(WlzReader.java:162)
	at loci.formats.FormatReader.setId(FormatReader.java:1396)
	at loci.formats.ImageReader.setId(ImageReader.java:835)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:988)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1070)
```

Interestingly, I could not reproduce the segfault for the `tiled` image. Do you have a scenario or is it just importing?

**Comment by melissalinkert** [comment]
Try ```showinf ts14-tiled.wlz```?  The segfault consistently occurred for me when reading pixel data.  I have Woolz 1.4.0 binaries locally, to match JWlz 1.4.0 in the repository.

**Comment by sbesson** [comment]
Follow up, I was able to reproduce the segfault mentioned in the description using the 10.9.5 binaries distributed at http://www.emouseatlas.org/emap/analysis_tools_resources/software/woolz.html.

However the Woolz 1.5.0 library compiled under CentOS seems to worked fine with this tiled file. Commit  https://github.com/ma-tech/Woolz/commit/a7a1590ff47bba03b4243d9af6b7fd1207c40ad2 looks relevant to this and suggests that the distributed binaries are 1.4.0 and this segfault is solved in 1.5.0. /cc @jianguo11

**Comment by melissalinkert** [comment]
Temporarily excluding for gh-1637.

Do we need/want this for 5.1.0?

**Comment by sbesson** [comment]
I would think so. As far as I can tell this will catch other segfaults caused by the same issue. Once gh-1637 is in and this PR is re-included, I will re-test functionalities work as expected.

**Comment by melissalinkert** [comment]
gh-1637 now merged; origin/develop is merged in here with conflicts fixed, so removing exclude label.

**Comment by sbesson** [comment]
Tested using `OMERO-5.1-merge-integration`. The two known failing files `EMA53_TS17_mesh.wlz` and `ts14-tiled.wlz` both fail (the latter with a more readable exception). All other samples files import correctly.
Ready to merge.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
