### PR TITLE
Rebase Metamorph changes from metadata

### PR DESCRIPTION
**Pull request by simleo**
Rebases `MetamorphReader` and `MinimalTiffReader` changes from #2151 and #2411.

### CODE REVIEW

**Comment by simleo** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-repository-subset/282/:

```
Initializing /ome/data_repo/curated/metamorph/heiko/sample_2x2.stk: 
	ImageNames: FAILED (Series 0 (got 'A01 : Scan A1', expected ''))
Initializing /ome/data_repo/curated/metamorph/chris/exp1_w1CSU GREEN_s3_t001.stk: 
	ImageNames: FAILED (Series 0 (got 'p3 x1/5-1', expected ''))
Initializing /ome/data_repo/curated/metamorph/steve/Experiment2.stk: 
	ImageNames: FAILED (Series 0 (got '}@', expected ''))
Initializing /ome/data_repo/curated/metamorph/aaron/RR11_2 TRAINED mid lobIX 63X GFP568_s1.STK: 
	ImageNames: FAILED (Series 0 (got 'Position278', expected ''))
Initializing /ome/data_repo/curated/metamorph/aaron/metamorph.stk: 
	ImageNames: FAILED (Series 0 (got 'Position278', expected ''))
Initializing /ome/data_repo/curated/metamorph/stephane/Lame7-E5-Y+-001.stk: 
	ImageNames: FAILED (Series 0 (got '??@', expected ''))
Initializing /ome/data_repo/curated/metamorph/heiko/sample_3x3.stk: 
	ImageNames: FAILED (Series 0 (got 'A01 : Scan A1', expected ''))
Initializing /ome/data_repo/curated/metamorph/ascb/C1  Stack.stk: 
	ImageNames: FAILED (Series 0 (got '??@', expected ''))
Initializing /ome/data_repo/curated/metamorph/chris/exp1_w2CSU RED_s3_t001.stk: 
	ImageNames: FAILED (Series 0 (got 'p3 x1/5-1', expected ''))
Initializing /ome/data_repo/curated/metamorph/chris/test2_w2_s1_t1.stk: 
	ImageNames: FAILED (Series 0 (got '?~@', expected ''))
Initializing /ome/data_repo/curated/metamorph/mike/TEST 1_7_w2EN GFP_s1_t61.STK: 
	ImageNames: FAILED (Series 0 (got 'Position24', expected ''))
Initializing /ome/data_repo/curated/metamorph/dave/Z Series.stk: 
	ImageNames: FAILED (Series 0 (got '??@', expected ''))
Initializing /ome/data_repo/curated/metamorph/alex/Selected FITC.stk: 
	ImageNames: FAILED (Series 0 (got 'B03 : Site 2', expected ''))
```

**Comment by simleo** [comment]
Here is a dump of the stage labels for all of the above datasets, shown as the set of unique values followed by the length of the actual list (non-printable characters are displayed as in Python, so e.g. the null character is `\x00`):

```
/ome/data_repo/curated/metamorph/heiko/sample_2x2.stk
  {'A01 : Scan A1\x00', 'A01 : Scan B1\x00', 'A01 : Scan A2\x00', 'A01 : Scan B2\x00]'} (len = 4)

/ome/data_repo/curated/metamorph/chris/exp1_w1CSU GREEN_s3_t001.stk
  {'p3 x1/5-1\x00', 'p3 x1/5-1\x00]'} (len = 51)

/ome/data_repo/curated/metamorph/steve/Experiment2.stk
  {'\x00er\x00\x00', '\x00\x01\x0c\x01\x00', ...} (len = 99)

/ome/data_repo/curated/metamorph/aaron/RR11_2 TRAINED mid lobIX 63X GFP568_s1.STK
  {'Position278\x00', 'Position278\x00]'} (len = 139)

/ome/data_repo/curated/metamorph/aaron/metamorph.stk
  {'Position278\x00', 'Position278\x00]'} (len = 139)

/ome/data_repo/curated/metamorph/stephane/Lame7-E5-Y+-001.stk
  {'\x00x%\x00\x00', '\x00\xef\xbf\xbd\xef\xbf\xbd@\x00', ...} (len = 4)

/ome/data_repo/curated/metamorph/heiko/sample_3x3.stk
  {'A01 : Scan B1\x00', 'A01 : Scan C3\x00]', 'A01 : Scan C1\x00', 'A01 : Scan C2\x00', 'A01 : Scan A3\x00', 'A01 : Scan A2\x00', 'A01 : Scan A1\x00', 'A01 : Scan B2\x00', 'A01 : Scan B3\x00'} (len = 9)

/ome/data_repo/curated/metamorph/ascb/C1  Stack.stk
  {'\x00w%\x00\x00]', '\x00\xef\xbf\xbd\xef\xbf\xbd@\x00', ...} (len = 4)

/ome/data_repo/curated/metamorph/chris/exp1_w2CSU RED_s3_t001.stk
  {'p3 x1/5-1\x00', 'p3 x1/5-1\x00]'} (len = 51)

/ome/data_repo/curated/metamorph/chris/test2_w2_s1_t1.stk
  {'\x00]\xef\xbf\xbd\xef\xbf\xbd\x00', '\x00y\x16\x00\x00', ...} (len = 51)

/ome/data_repo/curated/metamorph/mike/TEST 1_7_w2EN GFP_s1_t61.STK
  {'Position24\x00]', 'Position24\x00'} (len = 8)

/ome/data_repo/curated/metamorph/dave/Z Series.stk
  {'\x00ati\x00', '\x00\x00\x00\x00\x00', ...} (len = 21)

/ome/data_repo/curated/metamorph/alex/Selected FITC.stk
  {'B03 : Site 2\x00]', 'B03 : Site 2\x00'} (len = 15)
```

This means we have two issues:

* What we are using to read the stage labels is **not terminating strings correctly before the first null character**, so empty strings are misread as chunks of binary bogus and nonempty ones have a trailing null character. This needs to be fixed.
* When labels are nonempty, they can encode well information in different ways or be completely uninformative. With the current code, if the expected pattern is not found, additional images are not read. This means we have to relax the current assumption and fall back to some kind of automatic well coordinate and plate layout assignment (perhaps based on the number of labels and known plate layouts) when stage labels do not help.

**Comment by simleo** [comment]
5ced413 fixes the first issue. This brings the error count from 13 down to 8 in [the build](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-repository-subset/283):

```
logs.283/pool-1-thread-1.txt:   [testng] [2017-07-31 11:13:35,744] [pool-1-thread-1] Initializing /ome/data_repo/curated/metamorph/heiko/sample_2x2.stk: 
logs.283/pool-1-thread-1.txt:   [testng] [2017-07-31 11:13:36,136] [pool-1-thread-1] 	ImageNames: FAILED (Series 0 (got 'A01 : Scan A1', expected ''))
logs.283/pool-1-thread-1.txt:   [testng] [2017-07-31 11:14:07,919] [pool-1-thread-1] Initializing /ome/data_repo/curated/metamorph/mike/TEST 1_7_w2EN GFP_s1_t61.STK: 
logs.283/pool-1-thread-1.txt:   [testng] [2017-07-31 11:14:08,229] [pool-1-thread-1] 	ImageNames: FAILED (Series 0 (got 'Position24', expected ''))
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:14:18,945] [pool-1-thread-2] Initializing /ome/data_repo/curated/metamorph/aaron/RR11_2 TRAINED mid lobIX 63X GFP568_s1.STK: 
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:14:19,294] [pool-1-thread-2] 	ImageNames: FAILED (Series 0 (got 'Position278', expected ''))
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:14:54,182] [pool-1-thread-2] Initializing /ome/data_repo/curated/metamorph/aaron/metamorph.stk: 
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:14:54,404] [pool-1-thread-2] 	ImageNames: FAILED (Series 0 (got 'Position278', expected ''))
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:15:00,409] [pool-1-thread-2] Initializing /ome/data_repo/curated/metamorph/heiko/sample_3x3.stk: 
logs.283/pool-1-thread-2.txt:   [testng] [2017-07-31 11:15:00,625] [pool-1-thread-2] 	ImageNames: FAILED (Series 0 (got 'A01 : Scan A1', expected ''))
logs.283/pool-1-thread-3.txt:   [testng] [2017-07-31 11:15:19,302] [pool-1-thread-3] Initializing /ome/data_repo/curated/metamorph/chris/exp1_w1CSU GREEN_s3_t001.stk: 
logs.283/pool-1-thread-3.txt:   [testng] [2017-07-31 11:15:19,719] [pool-1-thread-3] 	ImageNames: FAILED (Series 0 (got 'p3 x1/5-1', expected ''))
logs.283/pool-1-thread-3.txt:   [testng] [2017-07-31 11:15:47,675] [pool-1-thread-3] Initializing /ome/data_repo/curated/metamorph/alex/Selected FITC.stk: 
logs.283/pool-1-thread-3.txt:   [testng] [2017-07-31 11:15:48,127] [pool-1-thread-3] 	ImageNames: FAILED (Series 0 (got 'B03 : Site 2', expected ''))
logs.283/pool-1-thread-4.txt:   [testng] [2017-07-31 11:13:57,164] [pool-1-thread-4] Initializing /ome/data_repo/curated/metamorph/chris/exp1_w2CSU RED_s3_t001.stk: 
logs.283/pool-1-thread-4.txt:   [testng] [2017-07-31 11:13:57,595] [pool-1-thread-4] 	ImageNames: FAILED (Series 0 (got 'p3 x1/5-1', expected ''))
```

Here is the new stage labels dump for the original 13 failing filesets:

```
/ome/data_repo/curated/metamorph/heiko/sample_2x2.stk
  {'A01 : Scan A1', 'A01 : Scan B1', 'A01 : Scan B2', 'A01 : Scan A2'} (len = 4)

/ome/data_repo/curated/metamorph/chris/exp1_w1CSU GREEN_s3_t001.stk
  {'p3 x1/5-1'} (len = 51)

/ome/data_repo/curated/metamorph/steve/Experiment2.stk
  {''} (len = 99)

/ome/data_repo/curated/metamorph/aaron/RR11_2 TRAINED mid lobIX 63X GFP568_s1.STK
  {'Position278'} (len = 139)

/ome/data_repo/curated/metamorph/aaron/metamorph.stk
  {'Position278'} (len = 139)

/ome/data_repo/curated/metamorph/stephane/Lame7-E5-Y+-001.stk
  {''} (len = 4)

/ome/data_repo/curated/metamorph/heiko/sample_3x3.stk
  {'A01 : Scan B1', 'A01 : Scan B2', 'A01 : Scan B3', 'A01 : Scan C3', 'A01 : Scan C2', 'A01 : Scan C1', 'A01 : Scan A1', 'A01 : Scan A3', 'A01 : Scan A2'} (len = 9)

/ome/data_repo/curated/metamorph/ascb/C1  Stack.stk
  {''} (len = 4)

/ome/data_repo/curated/metamorph/chris/exp1_w2CSU RED_s3_t001.stk
  {'p3 x1/5-1'} (len = 51)

/ome/data_repo/curated/metamorph/chris/test2_w2_s1_t1.stk
  {'', 'p3 x1/5-1'} (len = 51)

/ome/data_repo/curated/metamorph/mike/TEST 1_7_w2EN GFP_s1_t61.STK
  {'Position24'} (len = 8)

/ome/data_repo/curated/metamorph/dave/Z Series.stk
  {''} (len = 21)

/ome/data_repo/curated/metamorph/alex/Selected FITC.stk
  {'B03 : Site 2'} (len = 15)
```

Updating the config files at this point would probably fix all errors, but they are going to change again anyway after we generalize plate layout detection.

**NOTE:** we might want to move `readCString` to a method in `RandomAccessInputStream` at some point.

**Comment by simleo** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-repository-subset/286 green with the companion config PR.

55b4502 should also result in a performance improvement, since the old code was quadratic in the number of stage labels due to the usage of an inappropriate data structure (list instead of set).

**Comment by simleo** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-repository-subset/288 also green (adds a test from idr0010).

**Comment by dgault** [comment]
The code changes here all look to be fine and make sense based on the info in https://trello.com/c/vpc8NKAC/163-idr0010-metamorph-stk-per-channel

The builds, tests and repo jobs are green with the corresponding config PR included

Manually testing with the files that originally failed shows that the stage label changes are as expected and look to be correct.

PR looks good to merge alongside the config PR

**Pull request merged**
