### PR TITLE
OME-XML samples: synchronization and cleanup

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/visx1plk/36-schema-samples-migration. This PR supersedes https://github.com/openmicroscopy/bioformats/pull/2178/ and does the following:

- removes all non OME-XML samples from `components/specification/samples`
- synchronizes all OME-XML samples under `components/specification/samples` from the [live samples](http://downloads.openmicroscopy.org/images/OME-XML/) including naming changes and last additions and fixes
- fixes the OME-XML samples to comply with the policy decided on https://github.com/openmicroscopy/bioformats/pull/2286#issuecomment-197911813 using `XMLLINT_INDENT="  " xmllint -format`
- fixes the name of the samples across the repository especially in the various unit tests
- fixes the `specification` target validating the samples offline 

To test this PR:
- check all CI jobs are green including the Bio-Formats unit tests and the OME-XML C++ unit tests
- review the indentation changes in the OME-XML samples
- run the automated tests against the samples using the configuration files under `curated/ome-xml/ome-schemas`

Once this PR is accepted, the `samples` subfolder can be the home of the OME-XML samples, i.e. modifications/additions of the OME-XML samples can be proposed by PR. Once accepted, the data  under `data_repo/curated` should be updated to reflect these changes.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
In principle looks fine, but I'm not too happy with the reindentation commits.  They are reflowing the text as well as reindenting, and this actually makes them less readable since the examples were previously formatted by hand to be readable--it's jamming all the element attributes on one line where previously they were nicely indented and spread over multiple lines.  I don't think xmllint does a particularly good job here.

**Comment by sbesson** [comment]
@rleigh-dundee @joshmoore: as discussed,  374ba08 should reindent the XML using the emacs `region-indent` apply in batch (see command in the commit message).

**Comment by rleigh-dundee** [comment]
@sbesson Yes, looks much better thanks.  The only inconsistency is that it's using tabs and spaces for indents, so an `untabify` on the files would be nice.  Set `indent-tabs-mode` to `nil` to suppress tabs, perhaps?

**Comment by sbesson** [comment]
@rleigh-dundee: ran `untabify` in batch mode

**Comment by rleigh-dundee** [comment]
components/specification/released-schema/2016-DEV0/ome.xsd seems to be re-re-indented back to 8 spaces (from 2).

**Comment by rleigh-dundee** [comment]
Some of the 2015-01 samples (e.g.`hcs.ome.xml`, `minimum-specification.ome.xml`, `xmlannotation-body-space.ome.xml`) have trailing whitespace which would be nice to also clean up.

**Comment by sbesson** [comment]
Trailing whitespaces removed. Which commit/URL did you use for checking the `ome.xsd` file? It should be unmodified by this PR which was based before the cleanup work in https://github.com/openmicroscopy/bioformats/pull/2286

```
sbesson@ls30630:specification (ome_xml_samples_resync) $ git log --oneline -- released-schema/
78e6c96 Indent fix
986114a Merge branch 'openmicroscopy/develop' into ShapeComplexType-develop
```

I will go through the `2015-01` up the whitespaces in a follow-up PR.

**Comment by rleigh-dundee** [comment]
My problem doing the diff regarding ome.xsd.  Looks fine to merge.

**Comment by joshmoore** [comment]
Thanks all. Closing https://trello.com/c/visx1plk/36-schema-samples-migration ( :tada: )

**Comment by rleigh-dundee** [comment]
@joshmoore Please merge https://github.com/ome/ome-files-cpp/pull/4 at the same time.

**Pull request merged**
