### PR TITLE
NetCDF update

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Update to use version 4.6.10.

See [trello card](https://trello.com/c/VrpWk1Fj/119-netcdf-review)

Testing: Check builds and full repository job remain green.  Some IMS and other files which previously failed to read will now work.

### CODE REVIEW

**Comment by sbesson** [comment]
From the CI point of view, this PR builds fine and introduces no regression in the repository tests for the existing Imaris files. Some Imaris files were previously [failing](https://trello.com/c/ZxSCde2Z/94-imaris-ims-file-problems) and the next step would be to open some configuration PRs matching these changes to check these files are now properly read.

From the library standpoint, until now only the netcdf JAR was included in the dependency tree

```
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
```

With the changes included in this PR, the new dependency tree reads as follows:

```
[INFO] |  +- edu.ucar:netcdf4:jar:4.6.10:compile
[INFO] |  |  +- edu.ucar:cdm:jar:4.6.10:compile
[INFO] |  |  |  +- edu.ucar:httpservices:jar:4.6.10:compile
[INFO] |  |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  |  |  |  |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpmime:jar:4.5.1:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |  |  +- com.beust:jcommander:jar:1.35:compile
[INFO] |  |  |  \- com.amazonaws:aws-java-sdk-s3:jar:1.11.113:compile
[INFO] |  |  |     +- com.amazonaws:aws-java-sdk-kms:jar:1.11.113:compile
[INFO] |  |  |     +- com.amazonaws:aws-java-sdk-core:jar:1.11.113:compile
[INFO] |  |  |     |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  |     |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.6:compile
[INFO] |  |  |     |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  |  |     |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.6:compile
[INFO] |  |  |     |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.6:compile
[INFO] |  |  |     \- com.amazonaws:jmespath-java:jar:1.11.113:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:4.2.2:compile
```

For information, if all exclusions were removed from the `components/formats-gpl/pom.xml`, the `netcdf:4.3.22` tree would look like:

```
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
[INFO] |  |  +- edu.ucar:udunits:jar:4.3.22:compile
[INFO] |  |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.2:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.5:runtime
[INFO] |  |  +- org.jdom:jdom2:jar:2.0.4:compile
[INFO] |  |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  +- com.sun.jna:jna:jar:3.0.9:compile
[INFO] |  |  +- org.quartz-scheduler:quartz:jar:2.1.1:compile
[INFO] |  |  |  \- c3p0:c3p0:jar:0.9.1.1:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  |  +- net.sf.ehcache:ehcache-core:jar:2.6.2:compile
[INFO] |  |  \- com.sleepycat:je:jar:4.0.92:compile
```

While we review that these changes can be propagated across our software stack (https://github.com/openmicroscopy/openmicroscopy/pull/5462), two immediate questions come to mind:
- reading http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/BuildDependencies.html, it seems like only `cdm` might be required for our usage of this library, is that correct?
- is the entire dependency tree required? We previously excluded `httpclient` and `jna` but the library now consumes artifacts from a organization. We might not use the functionalities of dependencies like `com.amazonaws:aws-java-sdk-core` for instance. If we decided to include all dependencies for thoroughness, should we also review the dependencies already excluded?

While the first question might have an easy answer, the second one probably requires a larger conversation and a project-wide agreement to make sure we are all on the same page in terms of timelines and content /cc @jburel @joshmoore

**Comment by rleigh-codelibre** [comment]
Regarding cdm, I think you're most likely correct.  Shall I update the PR to only use cdm and retry the full repo test?

**Comment by sbesson** [comment]
:+1: for testing `cdm` only and checking the builds/automated tests are still passing with it.

**Comment by joshmoore** [comment]
Sorry the close was accidental while cleaning up branches. Now redirected.

**Comment by sbesson** [comment]
Unfortunately, while trying to integrate the changes from #3147 in a development build of OMERO, I realized this PR still breaks the build of the full stack (see [log](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build/58/console)).

Trying to summarize the situations:
- at the Bio-Formats level, the latest version of the dependency upgrade proposed works as expected. No regression for all HDF-based formats using this library was detected by the repository tests
- at the OMERO level, the upgrade causes some conflicts. The most recent investigation suggests this is related to issues between the dependency resolution mechanisms at the BF level (Maven-based) and at the OMERO level (Ivy-based) (see [comment](https://trello.com/c/VrpWk1Fj/119-netcdf-update#comment-599aa167d56f6424a91c9c48))
- initial investigation to drop `netcdf` usages by `jhdf5` turned out to be more complex than expectied.

As this is not a priority for the Users meeting and is preventing outstanding testing, closing this PR for now. Once we have established the priorities for the second half of 2018, we might want to discuss what would be the next steps to resurrect this upgrade effort across the stack.

**Comment by mtbc** [comment]
Note `udunits` note on https://github.com/ome/omero-model/pull/23.

**Pull request closed without merging**
