### PR TITLE
Bug Fix (Color Properties): Open OmeroROI's in ImageJ

### PR DESCRIPTION
**Pull request by bramalingam**
Testing Instructions:

1) Open an omero Image in Insight, create/modify ROI shape properties (Specifically stroke width and stroke colour of the ROI's) and save them.
2) Now open the Image on ImageJ using the OMERO-IJ Plugin and check if the ROI's are added to the ROIManager (and the shape properties are replicated in ImageJ).

### CODE REVIEW

**Comment by pwalczysko** [comment]
In ImageJ all works as epxected. Will test Fiji after the meeting.

**Comment by pwalczysko** [comment]
Okay, I have found an edge case which still does not work (both IJ and Fiji).
  - create some regions with changed properties (color and line width) in OMERO
  - open the image in ImageJ (all works fine)
  - create on this image one more region in ImageJ (or Fiji) - use the default line width and color (=yellow)
  - use ``Save to OMERO`` (all is saved as expected and regions still look exactly as created)
  - reopen the same image in ImageJ or Fiji - the region which was created last has slightly thicker line (just like if it would try to adjust to the lines of the previously created regions)  -> not expected, the region should have the default line thickness, just like it has in OMERO and just like it was created

Note that the region is visible though in any case. 
Also note that if you stick to default properties, it does not matter how many round trips you make with the regions, they are always visible as drawn in ImageJ and Fiji.

**Comment by pwalczysko** [comment]
Although I found a bug https://github.com/openmicroscopy/bioformats/pull/1671#issuecomment-82458999, I think this is an edge case. The behaviour here is fine in general for ImageJ and Fiji.
I would suggest to merge this and deal with the problem at a later time.

**Comment by melissalinkert** [comment]
Agreed - this PR only changes colors and likely wouldn't have introduced the line width difference.

**Comment by pwalczysko** [comment]
Thanks. Created a follow-up checklist item on https://trello.com/c/deNMiFvH/88-plugins-for-imagej-implementation

**Comment by bramalingam** [comment]
--no-rebase

**Pull request merged**
