### PR TITLE
Add CellH5 support

### PR DESCRIPTION
**Pull request by melissalinkert**
Replaces https://github.com/openmicroscopy/bioformats/pull/1591. /cc @sommerc

This has the commits from gh-1591, with additional commits to ensure that tests are successfully run and that the various aspects of building and importing with OMERO will work as expected.  There are also a number of style and whitespace fixes, for consistency with existing readers.

Note that this does change some of the color handling in ```ROIHandler``` - the change is technically correct, but a workaround may need to be added for using ```ROIHandler``` with Insight (/cc @bramalingam, @jburel).

The test files from http://cellh5.org have been added to ```data_repo/.../cellh5/samples```.  To test, verify that the ```reduced``` dataset both opens in ImageJ and imports into OMERO without any errors.  Import into OMERO will take quite some time (and memory!), as there are > 100,000 ROIs to be imported.  Import/display in OMERO should just work without an additional pull request.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#822](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/822/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/822/consoleText) for more details.
Possible conflicts:
  - PR #1573 melissalinkert 'Fixes for less common Woolz data types'
    - components/test-suite/src/loci/tests/testng/FormatReaderTest.java

**Comment by rleigh-dundee** [comment]
Overall looks OK.  Testing import into OMERO, just taking a long time to complete.

Metadata and images look OK with showinf.  OME-XML is valid.  But space-wise, could be improved to save space:

```
      <ROIRef xmlns="http://www.openmicroscopy.org/Schemas/ROI/2015-01" ID="ROI:0"/>
```

Due to the number of ROIs, specifying a `ROI:` xml namespace would allow `ROI:ROIRef` to be used, and this would remove the huge duplication of `xmlns` for every ROI schema element.  This is really a more general issue with the OME-XML output than this specific reader.

```
name: reduced
name: full
name: full
name: full
```

The above were printed onto the terminal while importing with Insight; not sure what's printing this; couldn't see it in the reader itself.

**Comment by rleigh-dundee** [comment]
On the OMERO side, it looks like there are some performance issues with this many ROIs, but that's of course not directly related to the file format or this PR.

**Comment by melissalinkert** [comment]
Switching to ROIRef is something for a separate PR I think.  The terminal output was introduced in https://github.com/openmicroscopy/openmicroscopy/pull/3569, and removed in https://github.com/jburel/openmicroscopy/commit/d1097d72116ef0f4f9ccac62611eb45b988cc5d5 on the same PR.

**Comment by melissalinkert** [comment]
Is this good to merge then?

**Comment by rleigh-dundee** [comment]
@melissalinkert Certainly from me, yes.

**Comment by melissalinkert** [comment]
--no-rebase

**Comment by maierl** [comment]
@sommerc do you already have an idea when you'll be able to implement the CellH5 writer for bioformats?

**Comment by sommerc** [comment]
Not yet on my list, but if there's interest for that!? The first version would rather only write 5D images to hdf5 (without ROI information). Is this something you could use?

**Comment by maierl** [comment]
That would definitely something we could use :+1:

**Comment by sommerc** [comment]
Cool! I will soon start with it...

Cheers, Chris

**Pull request merged**
