### PR TITLE
jpeg EXIF reading

### PR DESCRIPTION
**Pull request by PaulVanSchayck**
This allows to read jpeg EXIF data as original metadata. The datatime digitized is taken as input for the acquisition date.

To test, take jpeg files with and without exif data.

### CODE REVIEW

**Comment by melissalinkert** [comment]
Thanks, @PaulVanSchayck.  This seems fine on initial review - we're just waiting on confirmation from the CI system.

**Comment by melissalinkert** [comment]
Based on the output of https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/392/, there are just a couple of small changes that needed to be made.  I've opened a pull request against your ```jpeg-exif``` branch (https://github.com/PaulVanSchayck/bioformats/pull/1) with the necessary changes - once you have that merged, this should be ready to merge as well.

**Comment by ximenesuk** [comment]
@melissalinkert I listed this for review on Thursday but it didn't get picked up so inherited you name. Would you like a wider review by someone else on the team?

**Comment by melissalinkert** [comment]
Further review is not needed, I'm just waiting for https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/396 to finish before merging.

**Comment by melissalinkert** [comment]
--no-rebase

**Comment by PaulVanSchayck** [comment]
Thank you for merging! Looking forward to the 5.1 release.

I guess this also means you can close this ticket:
http://trac.openmicroscopy.org.uk/ome/ticket/12287

**Comment by pwalczysko** [comment]
Problems with importing jpeg images into OMERO in 5.1-m4 resulting from hese changes. Reopened http://trac.openmicroscopy.org.uk/ome/ticket/12287#comment:3.

**Comment by PaulVanSchayck** [comment]
@pwalczysko I can look at this Monday. Are these test images publicly available?

**Comment by pwalczysko** [comment]
@PaulVanSchayck : I can easily run the test on these images myself, it will be much faster than making them available to you, thanks. I think @melissalinkert was going to deal with the problem today already. So in case yoiu have no special images which you think need to be tested, we should be fine.

**Pull request merged**
