### PR TITLE
Deprecate the unused osgi Ant targets

### PR DESCRIPTION
**Pull request by sbesson**
The osgi targets are not built or released. The ome-tools bundle is release with other components but is unmaintained and unused. 
This commit deprecates these build targets in anticipation of their removal in upcoming releases.

### CODE REVIEW

**Comment by mtbc** [comment]
I don't think I'd even noticed the OME tools bundle before. Is it unrelated to `bftools.zip`?

**Comment by sbesson** [comment]
Completely unrelated, it might have been introduced as a very low-level component (dependencies are https://github.com/openmicroscopy/bioformats/blob/v5.2.2/ant/toplevel.properties#L137)

**Comment by mtbc** [comment]
Noted in Trello to mention this in whatsnew?

**Comment by sbesson** [comment]
There is a card for the 5.2.3 version history including this PR in the checklist /cc @hflynn

**Comment by mtbc** [comment]
:+1: Good to merge.

**Pull request merged**
