### PR TITLE
URL Pattern Reader

### PR DESCRIPTION
**Pull request by manics**
This is a version of FilePatternReader intended for importing remote files into OMERO as links. OMERO should only see this file, it should not see anything listed inside the `.urlpattern` file.

### CODE REVIEW

**Comment by sbesson** [comment]
Closing/reopening to include #3251

**Comment by manics** [comment]
Last two commits add a quick and dirty way of setting the reader in the urlpattern file, e.g.: `fov57-minio.urlpattern`:
```
s3://minio.openmicroscopy.org/czi.starfish.data.public/browse/raw/20180820/merfish_u2os/fov_57.tif
loci.formats.in.TiffDelegateReader
```
With the reader showinf takes ~30s, without ~50s.

**Comment by manics** [comment]
The last two commits get rid of FileStitcher and use a plain reader instead. FileStitcher still makes a lot of remote calls (~50), by using a plain `ReaderWrapper` the number of calls goes down to around 6, time ~15s.

**Comment by manics** [comment]
The last commits work with showinf, but they fail in omero import:
```
2018-11-16 14:35:46,173 6580       [l.Client-1] INFO   ormats.importer.cli.LoggingImportMonitor - METADATA_IMPORTED Step: 1 of 5  Logfile: 4069
2018-11-16 14:35:46,228 6635       [l.Client-0] DEBUG  ormats.importer.cli.LoggingImportMonitor - INTERNAL_EXCEPTION: /data/merfish_u2os-minio-tiffreader/fov_57.urlpattern
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: import-request-failure
Parameters: {stacktrace=java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at ome.formats.importer.OMEROWrapper.isMinMaxSet(OMEROWrapper.java:233)
        at ome.services.blitz.repo.ManagedImportRequestI.pixelData(ManagedImportRequestI.java:667)
        at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:524)
        at omero.cmd.HandleI.steps(HandleI.java:448)
        at omero.cmd.HandleI$RunSteps.innerWork(HandleI.java:509)
        at omero.cmd.HandleI$2.doWork(HandleI.java:383)
        at omero.cmd.HandleI$2.doWork(HandleI.java:380)
        at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:573)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy72.doWork(Unknown Source)
        at ome.services.util.Executor$Impl.execute(Executor.java:452)
        at omero.cmd.HandleI.run(HandleI.java:379)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at ome.services.util.Executor$Impl$1.call(Executor.java:493)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
, message=Index: 0, Size: 0}

        at ome.formats.importer.ImportLibrary$ImportCallback.onFinished(ImportLibrary.java:756)
        at omero.cmd.CmdCallbackI.finished(CmdCallbackI.java:334)
        at omero.cmd._CmdCallbackDisp.___finished(_CmdCallbackDisp.java:118)
        at omero.cmd._CmdCallbackDisp.__dispatch(_CmdCallbackDisp.java:145)
        at IceInternal.Incoming.invoke(Incoming.java:221)
        at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
        at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
        at Ice.ConnectionI.message(ConnectionI.java:1056)
        at IceInternal.ThreadPool.run(ThreadPool.java:395)
        at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
        at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by manics** [comment]
As discussed the reader will be moved into a separate repo. Relevant changes to help are in https://github.com/openmicroscopy/bioformats/pull/3279.

**Pull request closed without merging**
