### PR TITLE
Rebased: APLReader - Update to use native units

### PR DESCRIPTION
**Pull request by dgault**
APLReader - Update to use native units - Rebased from https://github.com/openmicroscopy/bioformats/pull/2067 onto develop

This PR adjusts the APLReader to store the physical pixel size read from apl files using the native units.

To test this PR, check apl files (cellr) are read correctly and automated tests are passing.

### CODE REVIEW

**Comment by dgault** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/15/

**Comment by sbesson** [comment]
--rebased-from #2067

**Comment by sbesson** [comment]
@dgault: are the commits from https://github.com/openmicroscopy/bioformats/pull/2071 meant to be rebased here as the `dev_5_1` PR is marked as `--no-rebase`?

**Comment by dgault** [comment]
No I wasn't going to rebase the units conversion. For 5.2 the units helper methods should probably be reworked.

**Comment by sbesson** [comment]
Make sense. Could you force push away the two commits which do not come from the original PR then ?

**Comment by dgault** [comment]
@sbesson: Removed the unwanted commits from this rebased PR

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/16/console

**Pull request merged**
