### PR TITLE
LIF reader wavelength

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes issue https://trac.openmicroscopy.org/ome/ticket/12808

To test:
 * Import ```leica-lif/niko/6-2-15MF2-Pos3-S1.lif```
 * Check that the excitation wavelength is correctly set.

### CODE REVIEW

**Comment by ehrenfeu** [comment]
Great to see this - I'm looking forward to test it! :smiley:

**Comment by melissalinkert** [comment]
https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/454/ notes 22 failures with this change, but I haven't checked yet to see what LAS AF Lite shows for the failing files.

**Comment by mtbc** [comment]
After import `6-2-15__MF2-Pos3-S1.lif` has excitation wavelengths of,
* 405nm for channel 0
* 488nm for channel 1
* 561nm for channel 2
* 633nm for channel 3.

The code looks plausible.

**Comment by melissalinkert** [comment]
This does seem to be breaking BIOFORMATS-5.1-merge-full-repository(-win), with 22 failures across 11 files.  Excluding for now.

**Comment by jburel** [comment]
@melissalinkert: I have not find a way in LAS AF Lite to see the metadata, any tip?

**Comment by melissalinkert** [comment]
Right-clicking the series name on the left-hand side and picking "Properties of..." should show a set of metadata tables that apply to that series.  Finding the excitation wavelengths can be a little tricky, but they will usually be listed as "Peak Excitation" in a "Channels used" table (usually near the top of the window), or in the "Sequential Setting Nr." tables (usually one table per non-brightfield channel) by looking up which of the "Laser Line Visible" entries has a percentage value greater than 0.

**Comment by jburel** [comment]
@melissalinkert: thanks

**Comment by jburel** [comment]
I had a closer look at one of the file that currently failed (file in the ```donald``` folder).
with change made in this PR the value for wavelength matches what LAS AF Lite shows
see 5x Objective.

**Comment by melissalinkert** [comment]
```.bioformats.breaking``` configuration files added for the 11 files that showed changed ExcitationWavelength values - those configuration files should match what LAS AF Lite shows.  Some of the files were definitely incorrect before, and fixed with this PR; some are better with this PR, but still not quite right.

As discussed with @sbesson, next step is running the breaking subset job; when the ```ExcitationWavelength``` failures are fixed there we can remove breaking, move the ```.bioformats.breaking``` files to ```.bioformats```, and merge.

**Comment by jburel** [comment]
@melissalinkert, @sbesson: I will have a look at the remaining files. I only had time to check 2 today.

**Comment by jburel** [comment]
More problems noticed, so this PR won't make it for 5.1.1

**Comment by jburel** [comment]
I will run the subset job tomorrow,depending on outcome, I will remove the breaking label.

**Comment by mtbc** [comment]
@jburel: It looks separate to me, but if #1793 causes you any trouble don't hesitate to exclude it.

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-breaking-repository-subset/57/ is finally green

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-test_images_good/496/ is green

**Comment by jburel** [comment]
List of files reviewed sent to @will-moore who is reviewing this PR today.

**Comment by jburel** [comment]
Went over the "FRAP" cases with @will-moore.
One adjustment to make to code. 
Moving it back to breaking so we can test it there w/o breaking anything.

**Comment by melissalinkert** [comment]
At this point, it might actually be better to not have this in breaking - keeping this out of the merge build will cause the merge builds to fail due to configuration changes.

**Comment by jburel** [comment]
I think I understood what is happening fro FRAP. Since it was not the initial goal of this PR and due to time constraints, I will investigate it in another PR using the breaking queue.

**Pull request merged**
