### PR TITLE
Add version history for 5.1.6

### PR DESCRIPTION
**Pull request by melissalinkert**
A couple of yet-unmerged PRs are referenced here, so depending on how Friday goes this may need one more commit.

### CODE REVIEW

**Comment by joshmoore** [comment]
Looks like a nice month's worth of work!

**Comment by melissalinkert** [comment]
Amended to remove references to gh-2044 and gh-2046.

**Comment by sbesson** [comment]
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/about/whats-new.html

**Comment by mtbc** [comment]
I don't see any typos! :+1:

**Comment by melissalinkert** [comment]
--rebased-to #2101

**Pull request merged**
