### PR TITLE
TIFF: reduce memory required for large files

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/dxVTjrxb/235-logbot-out-of-memory-detected-nightshade.

This makes better use of the ```OnDemandLongArray``` class to prevent keeping all tile/strip offsets and byte counts in memory.  The amount of memory required during setId with or without memoization should be greatly reduced for files with a large number of strips or tiles.

### CODE REVIEW

**Comment by joshmoore** [comment]
From travis:
```
Failed tests: 
  TiffPixelsTest.testDEFLATE:150->readSavedPlane:164 Â» Format Sorry, CCITT Group...
  TiffPixelsTest.testLZW:123->readSavedPlane:164 Â» Format Sorry, CCITT Group 3 1...
  TiffPixelsTest.testPROPRIETARY_DEFLATE:141->readSavedPlane:164 Â» Format Sorry,...
  TiffPixelsTest.testUNCOMPRESSED:87->readSavedPlane:164 Â» Format Sorry, CCITT G...
```

**Comment by melissalinkert** [comment]
Reverted the compression caching change; that didn't provide much memory savings anyway.  Not completely sure why that failed in Maven but not Ant, though.

**Comment by joshmoore** [comment]
Still seeing the exception on trout:

```
[jamoore@ome-c6100-3 ~]$ export PATH=$PATH:/opt/hudson/workspace/OMERO-5.1-merge-build/src/dist/bin/
[jamoore@ome-c6100-3 ~]$ omero import -f /repositories/OMERO-5.1-merge-deploy/ManagedRepository/user-1_8/2015-05/13/11-12-42.814
...
Caused by: java.lang.OutOfMemoryError: Java heap space
        at loci.formats.tiff.TiffParser.getIFDValue(TiffParser.java:526) ~[formats-bsd.jar:na]
        at loci.formats.tiff.TiffParser.fillInIFD(TiffParser.java:457) ~[formats-bsd.jar:na]
        at loci.formats.in.MinimalTiffReader.initFile(MinimalTiffReader.java:470) ~[formats-bsd.jar:na]
        at loci.formats.FormatReader.setId(FormatReader.java:1395) ~[formats-api.jar:na]
        at loci.formats.in.OMETiffReader.initFile(OMETiffReader.java:843) ~[formats-bsd.jar:na]
        at loci.formats.FormatReader.setId(FormatReader.java:1395) ~[formats-api.jar:na]
        at loci.formats.ImageReader.setId(ImageReader.java:835) ~[formats-api.jar:na]
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651) ~[formats-api.jar:na]
        at loci.formats.ChannelFiller.setId(ChannelFiller.java:223) ~[formats-bsd.jar:na]
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651) ~[formats-api.jar:na]
        at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:289) ~[formats-bsd.jar:na]
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651) ~[formats-api.jar:na]
        at loci.formats.Memoizer.setId(Memoizer.java:649) ~[formats-bsd.jar:na]
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651) ~[formats-api.jar:na]
        at ome.formats.importer.ImportCandidates.singleFile(ImportCandidates.java:414) [blitz.jar:na]
```

**Comment by manics** [comment]
`JAVA_OPTS=-Xmx4096M ~hudson/OMERO-5.1-merge-deploy/bin/omero import ...` worked (previously I had to use -Xmx8192M`, using the defaults fails as for Josh). Importing the image multiple times and opening all of them in the OMERO.web full image viewer leads to `java.lang.OutOfMemoryError: Java heap space` as before.

**Comment by joshmoore** [comment]
`-Xmx2G` fails; 3G passes.

**Comment by melissalinkert** [comment]
In looking at the file, the issue is slightly different than what this change was originally meant to fix.  For ```RhoRNAi_AurBmChTub.ome.tif```, each of the 2404 planes (1202 timepoints x 2 channels) has a color lookup table stored with it.  The small size of the planes means that there is actual more lookup table data than pixel data; because each lookup table was being read into memory (as part of the IFD), ~900 MB of lookup table data was being stored in memory/memo for each setId.

I've pushed a commit to remove the lookup table caching, so that a pointer is cached instead and the tables are read on demand.  This should reduce the memo file size to < 1.5 MB, and should hopefully help with import/display OOMs.  What I'm not entirely sure of is the extent to which on-demand lookup table reading will affect viewing performance - any feedback on that would be appreciated.

setId + memo file generation worked for me with a 2GB heap; I haven't tried anything smaller yet.

**Comment by melissalinkert** [comment]
Commit pushed to fix https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-openbytes-performance/496/.

**Comment by joshmoore** [comment]
Default options can now parse this (`23851ms.`). Times over a number of settings:
 * default: 23851ms.
 * 128m: 1707ms.
 * 500m: 6611ms.
 * 1g: 3502ms.
 * 2g: 4640ms.

**Comment by manics** [comment]
:+1: 
Imports without any special `-Xmx` options, I can open the image multiple times without an OOM.

**Pull request merged**
