### PR TITLE
Metamorph TIFF: add dual camera support

### PR DESCRIPTION
**Pull request by melissalinkert**
See QA 16887.  Dual camera acquisitions store two channels side-by-side;
this splits the image and records two separate channels.  The same
feature is already present in MetamorphReader.

To test, verify that the file from QA 16887 is 512x512, 2 channels, 200 timepoints, and that the channels are distinct.  Builds should remain green.

### CODE REVIEW

**Comment by sbesson** [comment]
Note https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-repository-subset/133/ reports one failure with the companion TIF file.

**Comment by melissalinkert** [comment]
Commit pushed which should fix that failure.

**Comment by sbesson** [comment]
Tested with the merge bioformats_package in ImageJ. The TIF file is correctly recognized as a 2-channel image:
screen shot 2015-11-10 at 14 32 56

Assuming automated tests pass, this looks ready to merge. /cc @mkitti

**Comment by melissalinkert** [comment]
Merging, since https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/673/ is more or less green.

**Comment by melissalinkert** [comment]
--rebased-to #2091

**Pull request merged**
