### PR TITLE
Sync east with develop

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Pull in latest changes to try to get tests green on east-ci.

Testing: Check jobs are green.

### CODE REVIEW

**Comment by mtbc** [comment]
Did the merge go smoothly?

**Comment by rleigh-codelibre** [comment]
@mtbc Some conflicts in the pom (`5.9.0-SNAPSHOT` vs `5.8.2-SNAPSHOT`) which were resolved.

**Comment by rleigh-codelibre** [comment]
Closed because we'll try to fix this by making the test logic ignore "unconfigured files"

**Comment by mtbc** [comment]
Ah, okay. Just to note, I had difficulty finding which builds had previously included this.

**Comment by rleigh-codelibre** [comment]
Nothing included this; it was only opened just before standup.

**Comment by rleigh-codelibre** [comment]
Replaced by https://github.com/openmicroscopy/bioformats/pull/3122

**Pull request closed without merging**
