### PR TITLE
TEST: Force generation of diffs for metadata

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Not for merging.

Check that https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-generated-sources/ has metadata diffs for java and cpp, and that both match the template change for MetadataStore (one comment addition per file).

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
ome-xml-metadata-cpp.diff is empty.

**Comment by jburel** [comment]
@rleigh-dundee: just looked at it and noticed the same problem
Java works fine.
cc @sbesson

**Comment by jburel** [comment]
Marking it as onhold so it does not get listed.

**Comment by sbesson** [comment]
Thanks for the review. The generated `meta` C++ component was not previously committed. After modification of the jobs, see https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-generated-sources/253/.

**Comment by jburel** [comment]
Thanks @sbesson.
Closing the PR, now that we have tested the job

**Comment by rleigh-dundee** [comment]
Looks good, thanks.

**Pull request closed without merging**
