### PR TITLE
Correct meta-companion samples

### PR DESCRIPTION
**Pull request by qidane**
Adding missing closing tag to the metadata.

These files may still not import correctly as the reader does not support metadata companions yet.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The replacement text is not XML, just a filename:

```
for file in components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-*.tiff; do ./tools/tiffcomment $file > ${file}.orig.xml; done
[ apply patch ]
for file in components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-*.tiff; do ./tools/tiffcomment $file > ${file}.new.xml; done
for file in components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-*.tiff; do diff ${file}.orig.xml ${file}.new.xml; done
1c1
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:4978087c-a670-4b12-af53-256c62d8d101" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> @/tmp/mateTiffComment-0sx1VW../bioformats/components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-split-Z1.ome.tiff/comment.xml
1c1
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f2307570-bede-47a7-aa2b-4e23231ac295" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> @/tmp/mateTiffComment-JcsNym../bioformats/components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-split-Z2.ome.tiff/comment.xml
1c1
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f4927e53-35eb-45b3-ac16-a9255a58860c" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> @/tmp/mateTiffComment-Lt8KlB../bioformats/components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-split-Z3.ome.tiff/comment.xml
1c1
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:25097c6a-c144-45fa-af9f-f10b1c045288" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> @/tmp/mateTiffComment-GutekV../bioformats/components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-split-Z4.ome.tiff/comment.xml
1c1
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:07a89384-e358-44dc-94d8-40e786ed9655" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> @/tmp/mateTiffComment-wkoCvS../bioformats/components/specification/samples/2013-06/set-1-meta-companion/18x24y5z1t1c8b-text-split-Z5.ome.tiff/comment.xml
```

**Comment by qidane** [comment]
Ok, this is a bit weird. Is seems that if you use the tiffcomment command when the upgrade check server is unavailable the comment is written to a temp file instead of std-out, and the path to the temp file is used instead.

**Comment by qidane** [comment]
Ok, it seems to be a change in behaviour in imagemagick convert. This use to work:

```
convert -depth 8 -comment "@$tf$filename/comment.xml" $filename $filename.out.tiff
```

According to the docs: http://www.imagemagick.org/script/command-line-options.php
the ```@``` should make it read the comment from the given file.

**Comment by qidane** [comment]
Switched my script to use graphicsmagick instead

```
gm convert -depth 8 -comment "@$tf$filename/comment.xml" $filename $filename.out.tiff
```

**Comment by qidane** [comment]
@rleigh-dundee Should be correct now.

**Comment by rleigh-dundee** [comment]
Changes look better now, but are adding a trailing blank line at the end of the text:

```
1c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:4978087c-a670-4b12-af53-256c62d8d101" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:4978087c-a670-4b12-af53-256c62d8d101" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"/></OME>
> 
1c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f2307570-bede-47a7-aa2b-4e23231ac295" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f2307570-bede-47a7-aa2b-4e23231ac295" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"/></OME>
> 
1c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f4927e53-35eb-45b3-ac16-a9255a58860c" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:f4927e53-35eb-45b3-ac16-a9255a58860c" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"/></OME>
> 
1c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:25097c6a-c144-45fa-af9f-f10b1c045288" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:25097c6a-c144-45fa-af9f-f10b1c045288" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"/></OME>
> 
1c1,2
< <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:07a89384-e358-44dc-94d8-40e786ed9655" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"></OME>
---
> <?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Warning: this comment is an OME-XML metadata block, which contains crucial dimensional parameters and other important metadata. Please edit cautiously (if at all), and back up the original data before doing so. For more information, see the OME-TIFF web site: http://ome-xml.org/wiki/OmeTiff. --><OME UUID="urn:uuid:07a89384-e358-44dc-94d8-40e786ed9655" xmlns="http://www.openmicroscopy.org/Schemas/OME/2013-06" xmlns:Bin="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06" xmlns:SPW="http://www.openmicroscopy.org/Schemas/SPW/2013-06" xmlns:SA="http://www.openmicroscopy.org/Schemas/SA/2013-06" xmlns:ROI="http://www.openmicroscopy.org/Schemas/ROI/2013-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06     http://www.openmicroscopy.org/Schemas/OME/2013-06/ome.xsd"><BinaryOnly MetadataFile="18x24y5z1t1c8b-text-companion.ome" UUID="urn:uuid:07504f88-7bc3-11e0-b937-2faf67bc00b3"/></OME>
> 
```

**Comment by qidane** [comment]
The extra whitespace should not cause a problem, and I am inclined to stop messing with the files.

**Comment by joshmoore** [comment]
> Ok, this is a bit weird. Is seems that if you use the tiffcomment command when the upgrade check server is unavailable the comment is written to a temp file instead of std-out, and the path to the temp file is used instead.

@melissalinkert : is that known?

**Comment by qidane** [comment]
@melissalinkert @joshmoore It might have been an artefact of the way my script was using it. I think it was being confused by getting the warning message from the command ahead of the comment. That combined with the fact there looks to be a bug in the latest version of imagemagick convert was causing my problems.

**Comment by melissalinkert** [comment]
There shouldn't be any special handling of files based on the upgrade check status.  If it's a serious problem, we'd need to see the script in question - otherwise the quick fix (which I think was noted in devteam) is to set the ```bioformats_can_do_upgrade_check``` environment variable to ```false```.

**Comment by qidane** [comment]
--no-rebase

**Pull request merged**
