### PR TITLE
Final Windows fixes

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository-win/2.

This will need one more commit after the next build of BIOFORMATS-5.1-merge-full-repository-win, so doesn't need to be reviewed quite yet.  I would expect all other builds to remain green, and the test failure count to be reduced by 95.  The 92 failures on QuickTime datasets are not yet resolved, but logging has been added to help determine the cause.

/cc @sbesson

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: Will run the Windows full repository job post-exclusion of gh-1723 tonight to assess these fixes.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-full-repository-win/5/console and https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-full-repository/458/ now have the same number of failures (i.e. 2 errors both related to https://github.com/openmicroscopy/bioformats/pull/1730#issuecomment-93854746). Good to merge!

**Comment by joshmoore** [comment]
:tada:

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
