### PR TITLE
C++: Fix external zlib, bzip2 and tiff to build on Windows

### PR DESCRIPTION
**Pull request by rleigh-dundee**
- Add option to disable Qt GUI widgets and viewer; not strictly superbuild-related, but it's breaking the superbuild job due to an incompatibility between Boost and Qt versions on cod, so this will allow it to be disabled
- Add helper script to drive installation for all cmake projects with both make and other build systems such as msbuild
- Adapt the zlib, bzip2 and tiff external projects to use this script, and so build on Windows
- Additional minor fixes to make this all work

--------

Testing:

On Linux, the superbuild will continue to work as in previous PRs.  The `qtgui` option can be tested by running:

`cmake -Dqtgui:BOOL=OFF`

and (assuming it would otherwise have built with Qt if it's available) it will now *not* build libome-qtwidgets or showinf/bf view.

On Windows, run in a temporary build dir:

```
cmake -G "Visual Studio 12 2013 Win64" -Dbioformats-superbuild:BOOL=ON -DBIOFORMATS_EP_SOURCE_CACHE:PATH=../sources /path/to/bioformats

cmake --build . --target zlib --config Debug
cmake --build . --target bzip2 --config Debug
cmake --build . --target tiff --config Debug

cmake --build . --target zlib --config Release
cmake --build . --target bzip2 --config Release
cmake --build . --target tiff --config Release
```

The rest of the build isn't yet functional, so these targets alone are to be tested here.  Look in `superbuild-install/bin` and make sure the zlib/bzip2/tiff DLLs are present; you should have a `d` suffix for the debug versions.  Look in `superbuild-install/bin` and make sure the zlib/bzip2/tiff LIBs are present; again with a `d` suffix for the debug versions.

### CODE REVIEW

**Comment by mtbc** [comment]
I can check for Linux.

**Comment by mtbc** [comment]
(guessing "previous PRs" is #1847, #1858)

**Comment by mtbc** [comment]
On Linux: I used the same minimal environment and superbuild approach as for previous PRs; it took a while for me to get prerequisites sorted to make `qtgui:BOOL=ON` possible.

If I do a `make` followed by a `make install`, it seems to do a whole bunch of compilation again for the `make install`. The install fails for me with,

```
Linking CXX executable ome-xml-headers
[ 78%] Built target ome-xml-headers
Makefile:126: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/bioformats.dir/build.make:118: recipe for target 'bioformats-prefix/src/bioformats-stamp/bioformats-build' failed
make[2]: *** [bioformats-prefix/src/bioformats-stamp/bioformats-build] Error 2
CMakeFiles/Makefile2:66: recipe for target 'CMakeFiles/bioformats.dir/all' failed
make[1]: *** [CMakeFiles/bioformats.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

I also notice that when I pass to cmake `-Dqtgui:BOOL=OFF` it says,
```
CMake Warning:
  Manually-specified variables were not used by the project:

    qtgui
```
and my `bioformats-build/CMakeCache.txt` has,
```
qtgui:BOOL=ON
```
During the `make` I got a failure,
```
Linking CXX shared library libome-xml.so
[ 30%] Built target ome-xml
Makefile:126: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/bioformats.dir/build.make:118: recipe for target 'bioformats-prefix/src/bioformats-stamp/bioformats-build' failed
make[2]: *** [bioformats-prefix/src/bioformats-stamp/bioformats-build] Error 2
CMakeFiles/Makefile2:66: recipe for target 'CMakeFiles/bioformats.dir/all' failed
make[1]: *** [CMakeFiles/bioformats.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

Possibly I am just not testing correctly!

**Comment by rleigh-dundee** [comment]
@mtbc You need to do a regular build, not a "superbuild".  The qtgui option isn't propagated to the bioformats sub-build yet.

Regarding the actual failure you saw above, you'd need to do a verbose build to see what was going wrong I think; I can't see anything immediately obvious.

**Comment by mtbc** [comment]
The culprit seems to be,
```
Generating moc_GLFlatShader2D.cpp
/usr/lib/i386-linux-gnu/qt5/bin/moc -I/tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib -I/tmp/qt/bioformats-build/cpp/lib -I/tmp/qt/superbuild-install/include -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtSvg -I/usr/include -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -o /tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets/moc_GLFlatShader2D.cpp /home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets/glsl/v110/GLFlatShader2D.h 
Generating moc_GLImageShader2D.cpp
/usr/lib/i386-linux-gnu/qt5/bin/moc -I/tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib -I/tmp/qt/bioformats-build/cpp/lib -I/tmp/qt/superbuild-install/include -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtSvg -I/usr/include -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -o /tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets/moc_GLImageShader2D.cpp /home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets/glsl/v110/GLImageShader2D.h 
Generating moc_GLLineShader2D.cpp
/usr/lib/i386-linux-gnu/qt5/bin/moc -I/tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets -I/home/mtbc/src/bioformats/cpp/lib -I/tmp/qt/bioformats-build/cpp/lib -I/tmp/qt/superbuild-install/include -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtSvg -I/usr/include -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -o /tmp/qt/bioformats-build/cpp/lib/ome/qtwidgets/moc_GLLineShader2D.cpp /home/mtbc/src/bioformats/cpp/lib/ome/qtwidgets/glsl/v110/GLLineShader2D.h 
moc failed...
```

**Comment by rleigh-dundee** [comment]
@mtbc Ah, that's a bug in the qt moc compiler with the version of Boost we're building.  Should have been fixed in Qt 5.5, released yesterday.  And the reason for adding the qtgui=OFF option.

**Comment by mtbc** [comment]
Again my mistake is to use too old a version of some third-party software! :smiley:

**Comment by joshmoore** [comment]
On Windows:
 * git clone
 * mkdir cppbuild && cd cppbuild
 * `cmake -Dbioformats-superbuild:BOOL=ON -DBIOFORMATS_EP_SOURCE_CACHE:PATH=../sources ..`

Worked well, and I saw tiff, zlib, bzip2 and boost going by. Small issue with `--config`:

```
c:\Users\jamoore\Desktop\bioformats\cppbuild>cmake --build . --target=zlib --config=Release
Unknown argument --config=Release
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
```

or moving `--build .` to the end:
```
c:\Users\jamoore\Desktop\bioformats\cppbuild>cmake --build . --config=Release
Unknown argument --config=Release
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
```

**Comment by rleigh-dundee** [comment]
@joshmoore Which cmake version is this? (cmake --version)  It should most definitely work:

```
       --build <dir>
              Build a CMake-generated project binary tree.

              This abstracts a native build tool's command-line interface with
              the following options:

                 <dir>          = Project binary directory to be built.
                 --target <tgt> = Build <tgt> instead of default targets.
                 --config <cfg> = For multi-configuration tools, choose <cfg>.
```

**Comment by mtbc** [comment]
A non-superbuild `cmake -Dqtgui:BOOL=OFF` gives me,
```
CMake Warning at cpp/lib/ome/qtwidgets/CMakeLists.txt:145 (message):
  Not building Qt widgets and view program; Qt5.2, OpenGL or glm not found
```
yet,
```
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLM: /usr/include  
```
and,
```
$ grep Qt CMakeCache.txt 
//The directory containing a CMake configuration file for Qt5Core.
Qt5Core_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core
//The directory containing a CMake configuration file for Qt5Gui.
Qt5Gui_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui
//The directory containing a CMake configuration file for Qt5Svg.
Qt5Svg_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Svg
//The directory containing a CMake configuration file for Qt5Widgets.
Qt5Widgets_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
//The directory containing a CMake configuration file for Qt5.
Qt5_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
```

**Comment by rleigh-dundee** [comment]
@mtbc Thanks for that.  Looking at the logic, we need to update the message, which is incorrect but harmless--it's displaying that text for the case where we explicitly disable it as well.

**Comment by mtbc** [comment]
`make` completes successfully after `-Dqtgui:BOOL=OFF` was passed to cmake (no superbuild).

**Comment by rleigh-dundee** [comment]
@mtbc Just to confirm, if you do a `make DESTDIR=i install`, there's no `view` program in `i/$prefix/libexec`?

**Comment by mtbc** [comment]
```
$ find /tmp/install/libexec/ -type f
/tmp/install/libexec/ome/bioformats/info
```

**Comment by rleigh-dundee** [comment]
Great, thanks, that's what's intended.

**Comment by joshmoore** [comment]
> Which cmake version is this? (cmake --version) It should most definitely work:

3.2.3. As you pointed out over Jabber (and in the updated description), the syntax is `--config Release` not `--config=Release`.

Otherwise, all looks good to me.

**Comment by rleigh-dundee** [comment]
Could this be merged?  Thanks.

**Pull request merged**
