### PR TITLE
ND2: read chunkmap to improve performance

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/Y4KMCatE/16-nd2-chunkmap-speedup-pr

This builds upon https://github.com/openmicroscopy/bioformats/pull/2556 from @csachs to fix remaining test issues and allow chunkmap processing to be disabled via the ```MetadataOptions``` API.

I would expect all tests to pass, with the subset/full repo jobs being slightly faster with this PR included.  

Expected offsets to image data within a file should now be logged at ```DEBUG```, regardless of whether or not chunkmap processing is enabled.  This can be tested with ```showinf -nopix -debug nd2/dallas/150609_m597_ut8.nd2``` and ```showinf -nopix -debug -option nativend2.chunkmap false nd2/dallas/150609_m597_ut8.nd2```.  ```setId``` times can also be compared in the same test, as the ```dallas``` file is quite large and should benefit from the performance improvement here.

With a build of ```bioformats_package.jar``` containing this PR installed in ImageJ, the ```Nikon ND2``` entry in ```Plugins > Bio-Formats > Bio-Formats Plugins Configuration``` should show a checkbox for using the chunkmap.  It should be checked by default, but it would be worth verifying that one or two files open identically with and without the box checked.

### CODE REVIEW

**Comment by sbesson** [comment]
Launched a [repository job](https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-repository-subset/190) against the current `nd2` folder without this PR included to have a baseline. Labelling as `breaking` to test the impact of this change in isolation before moving into the daily builds.

**Comment by sbesson** [comment]
Tested using the build with this PR included versus the latest version of Bio-Formats (5.3.4). For the two of the largest ND2 samples in our repository:

````
[sbesson@ome-c6100-3 ~]$ for i in $(seq 1 3); do (./bftools-5.3.4/showinf -nopix /ome/data_repo/curated/nd2/dallas/150609_m597_ut8.nd2 | grep Init); done
Initializing reader
Initialization took 7.651s
Initializing reader
Initialization took 8.127s
Initializing reader
Initialization took 7.911s
[sbesson@ome-c6100-3 ~]$ for i in $(seq 1 3); do (/opt/hudson/workspace/BIOFORMATS-DEV-breaking-build/tools/showinf -nopix /ome/data_repo/curated/nd2/dallas/150609_m597_ut8.nd2 | grep Init); done
Initializing reader
Initialization took 2.69s
Initializing reader
Initialization took 2.233s
Initializing reader
Initialization took 2.493s
[sbesson@ome-c6100-3 ~]$ for i in $(seq 1 3); do (./bftools-5.3.4/showinf -nopix /ome/data_repo/curated/nd2/sara/Ex9\ ALADIN\ WT\ KO\ KI\ 31_07_2013.nd2 | grep Init); done
Initializing reader
Initialization took 12.967s
Initializing reader
Initialization took 12.745s
Initializing reader
Initialization took 13.851s
[sbesson@ome-c6100-3 ~]$ for i in $(seq 1 3); do (/opt/hudson/workspace/BIOFORMATS-DEV-breaking-build/tools/showinf -nopix /ome/data_repo/curated/nd2/sara/Ex9\ ALADIN\ WT\ KO\ KI\ 31_07_2013.nd2 | grep Init); done
Initializing reader
Initialization took 4.349s
Initializing reader
Initialization took 2.658s
Initializing reader
Initialization took 3.447s
````

So from the performance standpoint, this PR definitely seems to reduce the initialization time by a factor three. This also means we might want to reconsider enabling the `sara` dataset into the daily repository job.

All automated tests are passing so this PR is introducing no regression in the core metadata at the very minimum. Looking at the [time trends](https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-repository-subset/buildTimeTrend), it is interesting to see the time with this PR included (builds 192, 195, 197) is larger than the builds without this PR (builds 193, 194). Could it be that while these changes increase performance for large ND2 files by scanning the chunkmap, the new code adds some overhead which slightly decreases performance for small ND2 files? Is there some additional profiling that can be done here?

**Comment by melissalinkert** [comment]
I think d8b5a97 will help with the discrepancy in build times - it certainly makes a big difference in a handful of files tried locally.  https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-repository-subset/200/ started to re-test.

**Comment by melissalinkert** [comment]
And now https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-repository-subset/201/ started to include 01bf93e and fix the one regressed file from build 200.

**Comment by sbesson** [comment]
With the latest set of commits, builds [201](https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-repository-subset/201), [202](https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-repository-subset/202) and [203](https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-repository-subset/203) all complete in 20min. Additionally, the initialization of the `sara/Ex9\ ALADIN\ WT\ KO\ KI\ 31_07_2013.nd2` file is now down to 1.8s. Very nice! Removing the `breaking` label for inclusion in the daily build.

**Comment by sbesson** [comment]
Also retested the impact of FS caching using a 50GB nd2 file stored on an external USB driver. Ran 6 successive opening of the files right after unmounting and remounting the USB hard drive.

Without this PR:

```
sbesson@c010156:Downloads $ for i in $(seq 1 6); do (showinf -nopix /Volumes/Harris_Drive/Big\ ND2\ File/O1_GROWTH_lowcellDens.nd2 | grep Initialization); done
Initialization took 84.426s
Initialization took 6.471s
Initialization took 6.706s
Initialization took 6.54s
Initialization took 6.687s
Initialization took 6.61s
```

With this PR:

```
sbesson@c010156:Downloads $ for i in $(seq 1 6); do (./bftools/showinf -nopix /Volumes/Harris_Drive/Big\ ND2\ File/O1_GROWTH_lowcellDens.nd2 | grep Initialization); done
Initialization took 1.427s
Initialization took 1.291s
Initialization took 1.224s
Initialization took 1.245s
Initialization took 1.247s
Initialization took 1.075s
```

So for this file, the `setId` performance gain is either 60/1 for a cold cache or 6/1 for a warm cache.

Also tested the plugin functionality (see screenshot below) using ImageJ in debug mode to check the output of the file opening call.
 
screen shot 2017-03-09 at 12 43 07

In addition to the validation by the [full repository job](https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/), one final check might be to review this PR via ImageJ/Fiji on Windows. Once cleared, this all looks great and ready to include for Bio-Formats 5.4.0.

**Comment by bramalingam** [comment]
Did the testing on imageJ, 

1) Checked the config options and can see the expected option (selected).
2) Toggling the checkbox and importing nd2 images did not alter the pixel/metadata on the few files I tried to import.

Looks good in my perspective.

**Comment by sbesson** [comment]
Thanks @bramalingam. As shown by https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-full-repository/465/, all repository tests are passing with this PR included and the `sara` dataset (largest ND2 file in our repository ~147G) is now tested daily as well.

Merging for inclusion in the upcoming Bio-Formats 5.4.0 release and deleting the `nd2_performance` integration branch which is now fully merged into develop. Thanks @csachs for your perseverance and your contribution.

**Comment by csachs** [comment]
Thanks for merging this.
The speed-ups were even more drastic at the time the work was started, and still are for larger files and slower links (eg > 100 GiB over 100 Mbit network).
Really happy this finally made it into develop. I'm sure many ND2 users will benefit from it :smiley:

**Pull request merged**
