### PR TITLE
Add a "Pyramid" column to the supported formats table

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/WL8qzFDe/44-list-has-pyramids-on-the-formats-list

To review, check the staged supported formats table page.  Verify that there is a ```Pyramid``` column on the far right, and verify that none of the values are obviously incorrect.

This does also make the column widths for ```Multiple Images``` and ```Pyramid``` a little larger, to hopefully prevent rendering issues noted in the last formats table PR.  Happy to revert those changes if   they don't help.

### CODE REVIEW

**Comment by mtbc** [comment]
Should this be listed for review?

**Comment by sbesson** [comment]
Rendered at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/supported-formats.html. Looks and renders good to me. Thoughts @hflynn @joshmoore?

**Comment by hflynn** [comment]
I'm increasingly not a fan of the way we render the middle items with the image headers* but as far as this PR goes, yes, it looks fine. 

*Although I'm not sure what to do about it - being able to collapse and expand that section might be useful for people on small screens maybe.

**Comment by joshmoore** [comment]
Would this be a possible place to attempt SVG? See http://tutorials.jenkov.com/svg/text-element.html#vertical-text

**Comment by hflynn** [comment]
That might be an idea yes, although we'd have to check what the browser support is like now too (although given I have Firefox 42 and that says version 22 didn't support it at time of writing, I guess that may be a rather old problem!). I will try to find time to look at that but I don't think it blocks merging this PR.

**Comment by hflynn** [comment]
https://trello.com/c/4rodQhTp/388-try-vertical-text-for-bf-supported-formats-table for reference.

**Pull request merged**
