### PR TITLE
OMETiffWriterTest - new unit tests for OMETiffWriter

### PR DESCRIPTION
**Pull request by dgault**
Initial PR opened for the purposes of judging the timing of automated testing on CI

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-FILES-CPP-DEV-merge-push-superbuild#505](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/505/). See the [console output](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/505/consoleText) for more details.
Possible conflicts:
  - PR #2722 dgault 'TiffWriter - Exception when writing bigTiff multi series'
    - components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

**Comment by sbesson** [comment]
Now #2722 is integrated, you should be able to fix the conflicts by merging `origin/develop` into this branch or rebasing it.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-FILES-CPP-DEV-merge-push-superbuild#506](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/506/). See the [console output](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/506/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

**Comment by sbesson** [comment]
The new test class should also be added to `components/formats-bsd/test/loci/formats/utests/testng.xml` to be effective.

**Comment by sbesson** [comment]
With this PR included, the build times for the [Linux Ant job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/) and the [Windows Ant job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build-win/)  increased by a factor two as expected. The impact on the default test coverage is minimal as shown by the Travis Maven builds. As the OME-TIFF and TIFF writers have different paths, enforcing a systematic coverage of both implementations is certainly a sensible thing for now. Merging this and we can review later whether these long-running unit tests should be re-architected, redesigned and/or moved to a separate component.

**Pull request merged**
