### PR TITLE
Change MapAnnotation type to be an Annotation

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/P3tnL6pY/55-mapannotation-should-not-be-a-textannotation

### CODE REVIEW

**Comment by sbesson** [comment]
Note the last commit should bring the `ome.xsd` annotation types in line with the https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/model/resources/mappings/annotations.ome.xml /cc @joshmoore

**Comment by rleigh-dundee** [comment]
The change looks fine to me, and the generated source changes look sensible and benign:

```
diff -urN components/ome-xml/target-develop/generated-sources/ome/xml/model/MapAnnotation.java components/ome-xml/target-dev-base/generated-sources/ome/xml/model/MapAnnotation.java
--- components/ome-xml/target-develop/generated-sources/ome/xml/model/MapAnnotation.java        2016-04-26 10:12:30.716103000 +0100
+++ components/ome-xml/target-dev-base/generated-sources/ome/xml/model/MapAnnotation.java       2016-04-26 10:45:48.764700000 +0100
@@ -70,9 +70,9 @@
 import ome.xml.model.enums.handlers.*;
 import ome.xml.model.primitives.*;
 
-public class MapAnnotation extends TextAnnotation
+public class MapAnnotation extends Annotation
 {
-       // Base: TextAnnotation -- Name: MapAnnotation -- Type: MapAnnotation -- modelBaseType: TextAnnotation -- langBaseType: Object
+       // Base: Annotation -- Name: MapAnnotation -- Type: MapAnnotation -- modelBaseType: Annotation -- langBaseType: Object
 
        // -- Constants --
 
diff -urN components/ome-xml/target-develop/generated-sources/ome/xml/model/NumericAnnotation.java components/ome-xml/target-dev-base/generated-sources/ome/xml/model/NumericAnnotation.java
--- components/ome-xml/target-develop/generated-sources/ome/xml/model/NumericAnnotation.java    2016-04-26 10:12:30.629620000 +0100
+++ components/ome-xml/target-dev-base/generated-sources/ome/xml/model/NumericAnnotation.java   2016-04-26 10:45:48.695239000 +0100
@@ -70,9 +70,9 @@
 import ome.xml.model.enums.handlers.*;
 import ome.xml.model.primitives.*;
 
-public abstract class NumericAnnotation extends Annotation
+public abstract class NumericAnnotation extends BasicAnnotation
 {
-       // Base: Annotation -- Name: NumericAnnotation -- Type: NumericAnnotation -- modelBaseType: Annotation -- langBaseType: Object
+       // Base: BasicAnnotation -- Name: NumericAnnotation -- Type: NumericAnnotation -- modelBaseType: BasicAnnotation -- langBaseType: Object
 
        // -- Constants --
 
```

One question I have is what is `BasicAnnotation` actually for, since it looks like it does absolutely nothing.

All the jobs are green so far, waiting on full-repository to complete.  Given the changes all look safe, should be good to merge.

**Comment by sbesson** [comment]
I think all annotations derived from`BasicAnnotation` are meant to be primitive annotations. This raises the question on whether `TextAnnotation` should also be a `BasicAnnotation`. I agree we have limited usage of them at the moment although some graph rules occasionally use it - see https://github.com/openmicroscopy/openmicroscopy/pull/4585

**Comment by mtbc** [comment]
No veto from me.

**Comment by mtbc** [comment]
So, this PR makes `NumericAnnotation` a `BasicAnnotation` and `MapAnnotation` merely an `Annotation`.

**Pull request merged**
