### PR TITLE
Metadata pages

### PR DESCRIPTION
**Pull request by sbesson**
While trying to address https://trello.com/c/ddPTOpmY, I found the meta-support generation script was taking too much time. This PR adds infrastructure to speed up the auto-generation compnents build and facilitate the opening of PRs against it.

Included changes on this PR are:
- conversion of the Bash script to Python to allow portability
- increase of performance (usage of `re` module?) while parsing the metadatastore setter methods

Without this PR:
```
$ cd components/autogen
$ rm src/meta-support.txt
$ ant gen-meta-support
...
BUILD SUCCESSFUL
Total time: 21 minutes 46 seconds
```

With this PR:
```
$ cd components/autogen
$ rm src/meta-support.txt
$ and gen-meta-support
...
BUILD SUCCESSFUL
Total time: 3 seconds
```

and `git diff` should show no changes on the `meta-support.txt` file.

### CODE REVIEW

**Comment by sbesson** [comment]
One more commit to force the ordering of the formats returned `listdir` and fix the branch pushed by https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs-autogen/

**Comment by dominikl** [comment]
Ran the gen-meta-support task with current develop branch and scc merge branch, compared the results. Looks fine, both meta-support.txt are matching, just the one resulting from the merged branch, contains some additional data - I suppose coming from other PRs (e. g. about CellH5Reader).
However in both cases - so not introduced by this PR - I got the following exeception after the gen-meta-support task ran:
```
...
 [java] 	XMLAnnotation
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 1: 
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 2: 
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 3: [Groups]
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 4: Image = Image
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 5: Pixels = Pixels TiffData
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 6: Dimensions = Dimensions
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 7: ImagingEnvironment = ImagingEnvironment
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 8: Plane = Plane PlaneTiming StagePosition
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 9: LogicalChannel = LogicalChannel ChannelComponent
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 10: DisplayOptions = DisplayOptions DisplayOptionsProjection DisplayOptionsTime
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 11: ROI = ROI
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 12: StageLabel = StageLabel
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 13: Instrument = Instrument
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 14: LightSource = LightSource Laser Filament Arc LightSourceSettings
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 15: Detector = Detector DetectorSettings
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 16: Objective = Objective
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 17: OTF = OTF
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 18: Experimenter = Experimenter
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 19: SPW = Plate PlateRef Reagent Screen ScreenAcquisition Well WellSample
     [java] 10:48:17.185 [main] DEBUG loci.common.IniParser - Line 20: Minimum = Image Pixels TiffData
     [java] Exception in thread "main" java.lang.NullPointerException
     [java] 	at java.io.Reader.<init>(Reader.java:78)
     [java] 	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
     [java] 	at loci.common.IniParser.openTextResource(IniParser.java:200)
     [java] 	at loci.common.IniParser.parseINI(IniParser.java:94)
     [java] 	at MetaSupportList.<init>(MetaSupportList.java:106)
     [java] 	at MetaSupportList.<init>(MetaSupportList.java:90)
     [java] 	at MetaSupportAutogen.main(MetaSupportAutogen.java:81)

BUILD FAILED
```

Execution time difference is impressive, several min compared to a few ms.

Good to merge.

**Comment by melissalinkert** [comment]
Definitely :+1: for the performance improvement.

The sort order is a little different for me (on Linux) - ```APLReader``` and ```ARFReader``` are before ```AliconaReader```, ```AmiraReader``` and ```AnalyzeReader```.  Either ordering is fine with me, but if there's a way to make it consistent cross-platform that would be cool.

The ```rm src/meta-support.txt``` seems to be the cause of the above exception; if the file is present, then I don't see an exception.

**Comment by sbesson** [comment]
@melissalinkert: last commit should user lowercase strings as the key for the readers sorting which should result in the same ordering as the current one in `meta-support.txt`.

**Comment by sbesson** [comment]
With the latest state of this PR, see https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs-autogen/294/consoleFull

```
gen-meta-support:
     [exec] Parsing AFIReader
     [exec] Parsing AIMReader
     [exec] Parsing AliconaReader
     [exec] Parsing AmiraReader
     [exec] Parsing AnalyzeReader
     [exec] Parsing APLReader
     [exec] Parsing ARFReader
     [exec] Parsing BaseZeissReader
...
++ git status -s
+ [[ -z '' ]]
+ echo 'No local changes'
No local changes

```

**Comment by melissalinkert** [comment]
Looks great now, thanks.

**Pull request merged**
