### PR TITLE
bump model doc reference to new 5.2 OMERO

### PR DESCRIPTION
**Pull request by mtbc**
Effects https://trello.com/c/lUQDSthL/81-update-model-docs-to-point-at-omero-5-2-docs. Staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/users/index.html#omero.

### CODE REVIEW

**Comment by sbesson** [comment]
This likely does not apply to the `develop` branch but to the `dev_5_1` branch?

**Comment by mtbc** [comment]
Ah, probably it does apply to 5.1, you're right. It does apply here too? Removed --no-rebase.

**Comment by mtbc** [comment]
> javac: invalid target release: 1.7

Something seems to need fixing in our BF Travis setup.

**Comment by sbesson** [comment]
No it does not apply to `develop` which will point to a different version of OMERO.

**Comment by mtbc** [comment]
Well, yes, but it surely applies no less than the current line and could cause conflicts in the meantime if trying to rebase PRs that change nearby lines.

**Comment by mtbc** [comment]
Replaced by #2043.

**Pull request closed without merging**
