### PR TITLE
FakeReader: add methods to read special pixels

### PR DESCRIPTION
**Pull request by simleo**
Adds methods to read out the metadata info (S, No, Z, C, T) that `FakeReader` encodes in each plane. This also serves as a source of documentation for the feature.

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice.

**Comment by sbesson** [comment]
All looks good to me. The Javadoc is clear and the addition of `public static` method is certainly sensible and reusable. In the long-run, if we start expanding FakeReader to support other types of pixel data than hardcoded gradients, we might considering deriving a companion `writeSpecialPixels()`.

Is it worth mentioning the existence of these special pixels in the corresponding Sphinx documentation page?

**Comment by simleo** [comment]
> Is it worth mentioning the existence of these special pixels in the corresponding Sphinx documentation page?

I'm not sure, they are only useful for testing purposes. Moreover, I think we should make them optional in the future (see Trello card)

**Comment by sbesson** [comment]
Makes sense. Merging for now.

**Pull request merged**
