### PR TITLE
Fold v5.8.1 changes into east

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
This updates the `east` branch with the 5.8.1 changes on `develop`.

Some of the open pull requests may require rebasing once this is merged.

### CODE REVIEW

**Comment by mtbc** [comment]
It merged cleanly?

**Comment by mtbc** [comment]
Hmmm, I don't see this in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/61/ - does it make sense to try for a Jenkins devspace run? I don't know how everything is configured.

**Comment by rleigh-codelibre** [comment]
It merged without trouble as far as I could tell.  Likely excluded from east-ci due to merge conflicts with the other open PRs.  They will need rebasing on top once this is merged.

**Comment by rleigh-codelibre** [comment]
@mtbc From today's east merge:

```
Merged PRs:
  # PR 3055 rleigh-codelibre 'tools: ImageConverter: Add -noflat option'
  # PR 3110 rleigh-codelibre 'Fold v5.8.1 changes into east'
```

and https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/61/ is green.

**Comment by mtbc** [comment]
Oh, doh, I should have looked at the push job, thank you. I assumed that the "merge" job did the merging.

**Comment by rleigh-codelibre** [comment]
@mtbc I agree the naming is confusing!

**Comment by mtbc** [comment]
I don't know if we need some corresponding follow-up PR for this no longer being a SNAPSHOT version of 5.8.1?

**Comment by rleigh-codelibre** [comment]
I would expect we will need a round of version updates for this and all the downstream components to e.g. 5.8.2-SNAPSHOT, 5.9.0-SNAPSHOT or similar.

**Comment by joshmoore** [comment]
Pushed a bump to 5.9.0-SNAPSHOT

**Pull request merged**
