### PR TITLE
Add version history for 5.1.0

### PR DESCRIPTION
**Pull request by melissalinkert**
This probably needs a little more work before tagging - minimally I would like to add doc links for new formats once the format page PR is opened and merged.

Happy to add anything that seems to be missing - I think all of the major or important changes are here, but there were a ton of PRs to go through so it's possible that a few slipped through the cracks.  Also happy to remove some of the more minor fixes if the list is too long as it is.

### CODE REVIEW

**Comment by hflynn** [comment]
Doc links for the new formats would be great, it would be nice to add a link to http://www.openmicroscopy.org/site/support/ome-model/schemas/january-2015.html for the schema update too. 
Personally I think the length is reasonable - good to show people how much work has been done!

**Comment by hflynn** [comment]
Oh, does look to me like there's any mention of @rleigh-dundee 's C++ work here

**Comment by melissalinkert** [comment]
Updated with doc links now that gh-1660 is merged.  I did add a line about C++ in 9ae8f9e too - I initially hadn't added it as I wasn't sure if we wanted to announce it in the list here, or as a separate paragraph in the announcement post.

**Comment by sbesson** [comment]
Should we add the signed bytes support for MRC (https://github.com/openmicroscopy/bioformats/pull/1656) to this history?

**Comment by melissalinkert** [comment]
Commit pushed to mention MRC sign fix.

**Comment by hflynn** [comment]
This looks good to merge ready for the release to me

**Comment by hflynn** [comment]
Oh date! Want to update this to March 31?

**Comment by melissalinkert** [comment]
Date updated.

**Comment by hflynn** [comment]
:+1: Good to merge as far as I'm concerned, thanks!

**Comment by melissalinkert** [comment]
Date updated to April 2, per latest release status email.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
