### PR TITLE
SDT: add support for Zip-compressed data

### PR DESCRIPTION
**Pull request by melissalinkert**
Fixes https://trac.openmicroscopy.org/ome/ticket/12893.

To test, use the files from QA 11079.  Without this change, the compressed file should have obviously wrong image data when compared with the uncompressed file.  With this change, the images for both files should match.

/cc @imunro

### CODE REVIEW

**Comment by imunro** [comment]
Thanks for the heads-up.

**Comment by imunro** [comment]
Do you think that the "if (codec == null) {"   inside the loops is optimised out?  If not, in the interests of performance it might be good to take this outside the loop unfortunately I can't see a way to do so that doesn't involve rather messy code duplication.

**Comment by imunro** [comment]
Would it be better to have a class that inherits from RandomAccessInputStream  with a read method 
read(byte[] rowBuf)  {
 int nread = 0;
        while (nread < rowBuf.length) {
           int n = codec.read(rowBuf, 0, rowBuf.length - nread);
           nread += n;
            if (n <= 0) {
             break;
            }
         }
then just set it to use this class instead in the case of compressed data?

**Comment by imunro** [comment]
Tested using FLIMfit and the data from QA 11079. Image appearance, max value and timebase all match for both files as expected so could be merged "as is" although  earlier comments still apply.

**Comment by imunro** [comment]
@melissalinkert do you need anything else from me on this ?

**Comment by melissalinkert** [comment]
Don't think so, thanks @imunro.  What I will likely do for now is just add a helper method in SDTReader to reduce the duplicate buffer reading - there's definitely room for a new class(es) at the loci.common level to help with this, but I want to avoid adding a lot of new API given that this is a patch release and we have I/O re-work coming up later in the year.

**Comment by imunro** [comment]
Whatever you think best. It certainly works exactly as is which is great.

**Comment by melissalinkert** [comment]
Commit pushed to reduce duplicate logic.

**Comment by rleigh-dundee** [comment]
The change reads fine and looks good to merge.  I presume the full-repo-test will be using the new configuration files?

**Pull request merged**
