### PR TITLE
Regions

### PR DESCRIPTION
**Pull request by joshmoore**
Migrates the topic branch `regions` to the 5.2 mainline (`develop`).

### CODE REVIEW

**Comment by joshmoore** [comment]
Moving to breaking but the regions build system is also testing this now.

--breaking

**Comment by joshmoore** [comment]
Running https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-breaking-trigger/

**Comment by mtbc** [comment]
All green. https://ci.openmicroscopy.org/view/Breaking/job/BIOFORMATS-DEV-breaking-generated-sources/17/ picked up the changes.

**Comment by joshmoore** [comment]
Points from standup that need looking into / thinking about:

 * samples: @sbesson is currently looking into the policy of duplicating & updating the samples. ETA: 2 days. If possible, it'd be good to know that this branch has existing, tested files.
 * `MetadataConverter`: @melissalinkert points out that any *additional* metadata that needs conversion needs adding in to the converter. This likely is something to put on the checklist for future `DEV`-schema bumps.
 * testing from OMERO: there is currently no way to test Bio-Formats breaking from OMERO breaking *in the mainline* (the regions CI can do it). It might be that this is "just ok" since the 2 projects are decoupled. Everyone just needs to be aware that there will be a period of time where OMERO `develop` will not work with Bio-Formats `develop`. cc: @jburel

**Comment by joshmoore** [comment]
Note also: breaking job has been re-activated with `@daily` (approx. 1300)

**Comment by mtbc** [comment]
MetadataConverter: Absolutely. It was my trying to add a folder method here that showed clearly I wasn't about to get recursive tags.

Testing from OMERO: Is actually pretty important. For instance, OMERO ExporterTest helps to test BF specification XSLT. We may have decoupling from a build point of view, but certainly not from a PR testing point of view.

**Comment by mtbc** [comment]
Once merged, may need to update the `ome.regions` resolver stuff in OMERO's `etc/build.properties`.

**Comment by mtbc** [comment]
You may be encouraged that my current folders work has the Bio-Formats branch based on this PR merged into develop, and every test I try running passes, including the Bio-Formats and OMERO unit tests and the OmeroJava/OmeroPy integration suite. So this PR probably won't need much work to get CI passing!

**Comment by joshmoore** [comment]
Discussion at standup basically gives this a thumbs up *however* due to backporting timelines current suggestion is to remove `--breaking` middle of next week by which time we'll hopefully have `DEV` tests all green.

**Comment by joshmoore** [comment]
Updated https://github.com/openmicroscopy/bioformats/pull/2115#issuecomment-159236807 to no longer contain "breaking"

**Comment by sbesson** [comment]
This PR was quickly tested via https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/43 against `ome-xml` and `ome-tiff` and has 24 failures  in total.

**Comment by sbesson** [comment]
Last commit should fix all the `testValidXML` failures by removing duplicated definition in the new DEV schema.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-performance/52/, https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-test_images_good/11/ and https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/44/ being green with the latest state of this PR included, any last minute veto to get this merged into the mainline @joshmoore @dgault @melissalinkert @rleigh-dundee?

**Comment by rleigh-dundee** [comment]
None from me.

**Comment by joshmoore** [comment]
:tada:

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
