### PR TITLE
Fix NDPI and Leica SCN metadata issues exposed by Virtual Microscope

### PR DESCRIPTION
**Pull request by melissalinkert**
See files in team/atarkowska/virtual-microscope/VLE_for_edu/.  With this change, magnifications should be parsed and stored for NDPI files, and magnifications/physical pixel sizes should be set correctly for Leica SCN data (regardless of whether or not pyramid resolutions are flattened).  Note that there is also some cleanup of the Leica SCN reader to make it more maintainable going forward.

/cc @aleksandra-tarkowska

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
Changes look OK and the metadata looks correct as well.  Looks good to merge.

**Comment by aleksandra-tarkowska** [comment]
Thank you @melissalinkert test files looks ok now. Great job.

**Comment by melissalinkert** [comment]
One last commit pushed as a result of https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/384/

**Comment by rleigh-dundee** [comment]
The change looks fine.  Hopefully all green soon!

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
