### PR TITLE
Updated version history for 5.1.4

### PR DESCRIPTION
**Pull request by melissalinkert**
Usual disclaimers apply with respect to date and verbosity.

/cc @hflynn, @mtbc for general review
/cc @rleigh-dundee for C++ review/additions

### CODE REVIEW

**Comment by hflynn** [comment]
Building on staging now, Travis obviously wasn't green in time for it to be included in last merge build.

**Comment by hflynn** [comment]
All formats correctly and reads fine to me

**Comment by hflynn** [comment]
If the plan is to release the C++ stuff separately (later), the C++ point on here should probably be removed, otherwise good to go AFAIK

**Comment by rleigh-dundee** [comment]
The C++ stuff isn't being released separately--it's in the same release as the java code.  The super build stuff is entirely separate and is not the C++ release.

**Comment by joshmoore** [comment]
@hflynn : the code fixes to make it work on Windows are included, but @rleigh-dundee, we will have to be careful that no on thinks this means that there are necessarily c++ builds ready.

**Pull request merged**
