### PR TITLE
Add a merge build profile to POMs

### PR DESCRIPTION
**Pull request by melissalinkert**
This allows the snapshot repository to be changed; by default, the
latest-build profile (== ome.snapshots repository) will be used.  If
'mvn -P merge-build' is run instead, then the merge-build profile (==
ome.unstable repository) is used.

This was previously gh-1834.

### CODE REVIEW

**Comment by sbesson** [comment]
Tested artifacts deployment via https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-DEV-merge-maven/4/console, passing the profile option to the `mvn` command is enough to get the artifacts deployed on the `ome.unstable` repository.
Will be investigating how to consume these artifacts from the OMERO/Ivy standpoint next..

**Comment by sbesson** [comment]
Discussed today with @melissalinkert @joshmoore @jburel @bramalingam. The strategy above did not work as initially expected since there is no repository classifier that can be used by Ivy while retrieving Maven artifacts. An alternative to be explored is to use the profile to set a different groupId for merge artifacts.

**Comment by sbesson** [comment]
Depending on the testing result of https://github.com/openmicroscopy/openmicroscopy/pull/3935, we may want to resurrect this PR/strategy for uploading merge SNAPSHOTS.

**Comment by melissalinkert** [comment]
Replaced by gh-1867 (on develop).

**Pull request closed without merging**
