### PR TITLE
Fix transforms

### PR DESCRIPTION
**Pull request by jburel**
Now correctly handles empty maps in imaging environment and wavelength units.
Fixes older transforms not generating valid xml.

Corresponding OMERO tests https://github.com/openmicroscopy/openmicroscopy/pull/3614
cc @qidane 
This PR replaces gh-1665

### CODE REVIEW

**Comment by jburel** [comment]
@qidane: what was the reason for adding the ```xslt:fix``` in the first place when downgrading to 2003-FC? I cannot remember

**Comment by qidane** [comment]
I think the problem is/was the regex in the 2003-FC schema for ID always was broken, so if you have a full `urn` form of the LSID then it will not validate. The `xslt.fix:` prefix allowed the urn form to validate and still keep the full LSID in tact. The problem is when the 2003-FC schema is then upgraded again the fixed ID is now broken as it will not validate with the corrected regex.

**Comment by jburel** [comment]
one more commit to come

**Comment by jburel** [comment]
Few more issues noticed when running against files from https://github.com/openmicroscopy/samples
Actions:
 * fix stylesheet
 * Improve mock-objects.

**Comment by jburel** [comment]
@qidane: any reason to have unit-conversion.xsl stylesheet version 2.0 and the rest 1.0.
It will be easier to upgrade the stylesheet.

**Comment by jburel** [comment]
Also I do no think we should strip out wavelength if it is not an int, since in many cases we will have a value like 550.0. I know it is not the rule we have applied in previous transform but I am worried that we lose valuable information
cc @will-moore @rleigh-dundee @pwalczysko @joshmoore @melissalinkert

**Comment by jburel** [comment]
The examples from samples should now validate.

**Comment by jburel** [comment]
Still an issue with microbeam manipulation

**Comment by jburel** [comment]
I think we should re-consider the strategy currently in place when downgrading from float to int
Currently if round(value) != value the value is lost. e.g. 540.1 will be lost instead of having 540 in an older schema.
This generates failures when downgrading to older the schema and also removes some valuable information.
cc @qidane @joshmoore @melissalinkert @will-moore @pwalczysko

**Comment by jburel** [comment]
Ant suite
Total tests run: 76, Failures: 0, Skips: 0
===============================================

**Comment by jburel** [comment]
FYI: @qidane is also making sure that the downgrade paths in ome-transform match the ones suggested in the documentation.

**Comment by qidane** [comment]
There are a few differences:

2008-09 to 2008-02
2009-09 to 2008-02
2010-04 to 2008-02
2009-09 to 2008-09
2010-04 to 2008-09

Just checkin wether docs or ome-transforms have best solution.

**Comment by qidane** [comment]
I think I would prefer to change the ome-transforms file as I the method from the documentation has fewer steps so is likely to produce a margenly better result. @jburel how do you feel about this change? Would you prefer I just updated the docs?

**Comment by jburel** [comment]
can you push a change to the transform so I can run the test locally to access situations?
Tests are not passing on ci-node, due to encoding. investigating issues cc @sbesson

**Comment by qidane** [comment]
https://github.com/jburel/bioformats/pull/3

**Pull request merged**
