### PR TITLE
Updating DeltaVision link

### PR DESCRIPTION
**Pull request by hflynn**
See https://github.com/openmicroscopy/bioformats/issues/1581

This is the UK redirect with prettier graphics 

I've also removed the extra link as the main one goes to the equivalent page.

### CODE REVIEW

**Comment by sbesson** [comment]
Reads fine and staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/formats/deltavision.html. Worth fixing the samples link in the same page?

**Comment by hflynn** [comment]
Oh, I missed that, will push a fix, thanks

**Comment by hflynn** [comment]
Hunted all round the website and couldn't find any sample files so I've just removed the link.

**Comment by ximenesuk** [comment]
@sbesson do you want to double check this one?

**Comment by sbesson** [comment]
Tested on https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/formats/deltavision.html. Thanks.

**Comment by hflynn** [comment]
--rebased-to #1602

**Pull request merged**
