### PR TITLE
Tiffcomment: add note about ImageDescription tag

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/pqx8FSLk/160-can-comment-ome-tiff-but-not-plain-tiff for reference

This PR adds a note to the Sphinx documentation page and the `tiffcomment` usage to mention the `ImageDescription` tag requirement in the TIFF file.

### CODE REVIEW

**Comment by mtbc** [comment]
Do there happen to be any third-party utilities that will add an `ImageDescription` tag to one's TIFF or if there isn't a preexisting one are people basically screwed? (If yes, might be nice to mention; if not, doesn't block this PR which improves the documentation anyway.)

**Comment by rleigh-dundee** [comment]
I would use `present` rather than `in place` in all these descriptions.  Otherwise, it all looks good.

@mtbc You are basically screwed.  In theory an entirely new IFD could be written, but that's a lot more work than adjusting a single offset.

**Comment by sbesson** [comment]
Pushed terminology change suggested above.

**Comment by rleigh-dundee** [comment]
Looks fine and good to merge, thanks.

**Pull request merged**
