### PR TITLE
Display private fields and methods in Javadocs

### PR DESCRIPTION
**Pull request by melissalinkert**
See gh-1693.  Private fields (e.g. ```minimumElapsed``` in Memoizer) should be present in the Javadocs with this PR included.  Feel free to cherry pick the commit, or close outright if this isn't helpful.

### CODE REVIEW

**Comment by sbesson** [comment]
Because Javadoc links will not be public before we release Bio-Formats 5.1.0 and its API documentation, simultaneously changing gh-1693 to point at a to-be-exposed private field would be untested and potentially result in broken links. That being said, I do not see any strong reason NOT to expose private fields in the Javadocs  and link to this private fields in subsequent patch releases. /cc @hflynn

https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-build/769/ is yellow because this PR exposes new Javadoc warnings. I will try to open a PR against this branch to fix them.

**Comment by hflynn** [comment]
Yeah, I'm happy to do a patch release once the API docs are live - assuming the links are correct, we can have it live on the web docs on release day even.

**Comment by melissalinkert** [comment]
Javadoc warnings fixes merged in.

**Comment by sbesson** [comment]
`-Xdoclint:none` addition caused https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-build-win/592/ to fail and may need to be reverted.

**Comment by mtbc** [comment]
There are docs at http://downloads.openmicroscopy.org/bio-formats/5.1.0-m5/api/ but I don't know where the open PRs are staged so I'll rely on a local build once GitHub permits.

**Comment by hflynn** [comment]
I don't think there is a staging build for these.

**Comment by mtbc** [comment]
Locally (on Linux) if I do,
```
git checkout 7d079dd5
git merge 7e7a7c52
git clean -dfx
ant docs
```
then I get,
```
  [javadoc] Skipping /home/mtbc/src/bioformats/components/stubs/mipav-stubs/build/src since it is no directory.
  [javadoc] /home/mtbc/src/bioformats/components/forks/turbojpeg/build/src contains source files in the default package, you must specify them as source files not packages.
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] usage: javadoc [options] [packagenames] [sourcefiles] [@files]
  [javadoc] javadoc: error - invalid flag: -Xdoclint:none
...
  [javadoc] 1 error

BUILD FAILED
/home/mtbc/src/bioformats/ant/toplevel.xml:172: Javadoc returned 1
```
which looks like the issue noted by @sbesson.

**Comment by rleigh-dundee** [comment]
@sbesson Take a look at

https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/antlib/resources/global.xml#L233
https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/antlib/resources/global.xml#L256
https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/antlib/resources/lifecycle.xml#L381

for how to autodetect and enable this option with jdk 1.8.

**Comment by sbesson** [comment]
@rleigh-dundee: thanks for the pointers. A similar strategy should definitely be adapted here (but I won't have time before 5.1.0 under all likelihood). In the meantime, reverting 37443e3 should be enough to let the CI jobs pass with JDK < 1.8.

**Comment by rleigh-dundee** [comment]
@sbesson No problem.  It's fixed in https://github.com/melissalinkert/bioformats/pull/25

**Comment by mtbc** [comment]
This is now working just fine on Java 1.7. :+1: Two small concerns:

1. There are private method comments that don't seem to have much anticipated being Javadoc'd. They might be worth a (very boring) review someday to better-format todo notes, etc.
1. Few people reading the API docs care about the privately scoped parts, but there are often so many that the other stuff is lost among it. This might actually be worth two different docs builds, depending on if the developer -- who will typically want to focus on the stable API -- even wants to see the private stuff that will often dominate it.

Still, if we are going this way, then I don't see any blockers. Someone should check on Java 1.8 of course. (I don't even have an OpenJDK 8 with Jessie.)

**Comment by mtbc** [comment]
@sbesson: Is the doclint argument required to prevent a failed build in Java 8, so if it seems to work then probably the option is being properly used? (I don't know if over time we plan to fix the docs such that we don't need the option any more.)

**Comment by mtbc** [comment]
I have been testing with "ant docs". Does that suffice, or ought I also test some maven target?

**Comment by mtbc** [comment]
BIOFORMATS-5.1-merge-build-win is now green. :+1:

**Comment by rleigh-dundee** [comment]
@mtbc "ant docs" should be sufficient; the maven build is untouched by this change.

BTW, for Java8 testing on Debian you could just drop the Oracle JDK8 into /opt and temporarily add to your PATH/JAVA_HOME; it worked for me.

**Comment by manics** [comment]
> Few people reading the API docs care about the privately scoped parts, but there are often so many that the other stuff is lost among it. This might actually be worth two different docs builds, depending on if the developer -- who will typically want to focus on the stable API -- even wants to see the private stuff that will often dominate it.

The other advantage of a separate private-docs build target is it reduces the temptation for people to use implementation-dependent functionality in their code.

**Comment by dominikl** [comment]
No problems noticed when built with Java 8 (tested with 1.8.0_25)

**Comment by jburel** [comment]
java version "1.8.0_31" no errors noticed

**Comment by melissalinkert** [comment]
This is good to merge then?

**Comment by mtbc** [comment]
From me, no blockers to merging.

**Comment by melissalinkert** [comment]
OK, merging then.  Reminder card for doing the private Javadoc review: https://trello.com/c/U8HDtN3O/159-review-private-method-javadocs

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
