### PR TITLE
prefer the non-regexp version for replacing substrings

### PR DESCRIPTION
**Pull request by thusharaw**
Make the getIFDTextValue faster by preferring the non-regexp version of replace.

### CODE REVIEW

**Comment by dgault** [comment]
Hi @thusharaw, thank you for the contribution.  From taking an initial look this seems like a reasonable change. We will include your PR for testing against the repository of sample files we have.

Do you have a specific scenario or example in which you have noticed a marked improvement in the performance with this change? If you have any associated sample files that can be used for testing they can also be uploaded to http://qa.openmicroscopy.org.uk/qa/upload/

**Comment by thusharaw** [comment]
Hello -


Thanks for taking a look. I uploaded a file that should show a marked improvement with this fix. I have tested with the fixes Alex (my co-worker) made to the parsing of the generic comment:


https://github.com/openmicroscopy/bioformats/pull/2937


coupled with this. The generic comment parsing happens before this code with the regexp is hit.


best,

thushara

________________________________

**Comment by rleigh-codelibre** [comment]
This change looks good and it provides a significant performance improvement.  Please merge.

```
> data
  state  time
1   old 231.4
2   old 221.6
3   old 207.6
4   new 168.7
5   new 165.8
6   new 169.8
> t.test(time ~ state, data = data)

        Welch Two Sample t-test

data:  time by state
t = -7.434, df = 2.1193, p-value = 0.01497
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -80.68514 -23.51486
sample estimates:
mean in group new mean in group old 
            168.1             220.2 
```

**Comment by rleigh-codelibre** [comment]
@thusharaw Regarding the test data, please note the comments in https://github.com/openmicroscopy/bioformats/pull/2937 and also for the test data you provided, I saw a similar problem:

If I run the `showinf` tool, you can see it's warning about problems with the file's metadata:

```
% ./tools/showinf ./17916/problem.ome.tiff -nopix  
Checking file format [OME-TIFF]
Initializing reader
OMETiffReader initializing ./17916/problem.ome.tiff
Image ID 'Image:0': missing plane #0.  Using TiffReader to determine the number of planes.
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Image ID 'Image:1': missing plane #0.  Using TiffReader to determine the number of planes.
Reading IFDs
Populating metadata
```

Because the metadata lacks `TiffData` elements, it doesn't know which plane is associated with each TIFF IFD and it's falling back to using the `TiffReader` to try to determine this by hand, and this is where you are hitting the inefficient parsing.  If you correct the metadata, you won't be hitting these codepaths at all.

You can also verify the correctness the the `xmlvalid` tool:

```
% ./tools/xmlvalid ./17916/problem.ome.tiff | head -n 20
Parsing schema path
http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd
Validating ./17916/problem.ome.tiff
cvc-complex-type.2.4.a: Invalid content was found starting with element 'Plane'. One of '{"http://www.openmicroscopy.org/Schemas/OME/2016-06":Channel, "http://www.openmicroscopy.org/Schemas/OME/2016-06":BinData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":TiffData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":MetadataOnly}' is expected.
cvc-pattern-valid: Value 'XMLAnnotation:1337:50' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:50' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-pattern-valid: Value 'XMLAnnotation:1337:0' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:0' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-complex-type.2.4.a: Invalid content was found starting with element 'Plane'. One of '{"http://www.openmicroscopy.org/Schemas/OME/2016-06":Channel, "http://www.openmicroscopy.org/Schemas/OME/2016-06":BinData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":TiffData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":MetadataOnly}' is expected.
cvc-pattern-valid: Value 'XMLAnnotation:1337:51' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:51' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-pattern-valid: Value 'XMLAnnotation:1337:1' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:1' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-complex-type.2.4.a: Invalid content was found starting with element 'Plane'. One of '{"http://www.openmicroscopy.org/Schemas/OME/2016-06":Channel, "http://www.openmicroscopy.org/Schemas/OME/2016-06":BinData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":TiffData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":MetadataOnly}' is expected.
cvc-pattern-valid: Value 'XMLAnnotation:1337:52' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:52' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-pattern-valid: Value 'XMLAnnotation:1337:2' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
cvc-attribute.3: The value 'XMLAnnotation:1337:2' of attribute 'ID' on element 'AnnotationRef' is not valid with respect to its type, 'AnnotationID'.
cvc-complex-type.2.4.a: Invalid content was found starting with element 'Plane'. One of '{"http://www.openmicroscopy.org/Schemas/OME/2016-06":Channel, "http://www.openmicroscopy.org/Schemas/OME/2016-06":BinData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":TiffData, "http://www.openmicroscopy.org/Schemas/OME/2016-06":MetadataOnly}' is expected.
cvc-pattern-valid: Value 'XMLAnnotation:1337:53' is not facet-valid with respect to pattern '(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Annotation:\S+)|(Annotation:\S+)' for type 'AnnotationID'.
```

In the code used to write the examples, you might want to make sure that:

- you are calling setSeries() for each Image in the metadata and then calling saveBytes for each plane in that image.  Your sample has a single plane only.
- you use `MetadataTools` `createLSID` or a similar function to compile element identifiers which are compatible with the schema constraints.  Your XMLAnnotation IDs have `x:y` numbering when only `x` is allowed.
- you have `TiffData` elements for each image plane inside the `Pixels` element.  These should be automatically created by the `OMETiffWriter` class after you've called `saveBytes` for each image plane.  Is this what you're using to create the images?  If you make sure to write out each plane for each image, they should be automatically created by the writer.

Please do use the lists or forums if you would like to discuss any of the above issues outside the context of this pull request.

Best wishes,
Roger

**Pull request merged**
