### PR TITLE
Automated tests: add support for external configuration directory

### PR DESCRIPTION
**Pull request by sbesson**
Currently automated tests are relying upon configuration files (`.bioformats`) being present under the same tree as the data repository. The goal of this infrastructure PR is to remove this requirement and allow external configuration tree to bee used to test the data repository. Ultimately, this should simplify our workflow when modifying readers and configuration files /cc @jburel

To test this PR:

- check the overall set of changes is sensible. Some refactoring in the test classes to use helper methods and hide parameters of type `${property}` set by `ant`
- check the existing test logic is untouched without specifying a configuration directory
  ```
ant test-config -Dtestng.directory=/path/to/data  # should create/append .bioformats files in-place
ant test-automated -Dtestng.directory=/path/to/data  # should test using local .bioformats files
```
- test the configuration files can be generated under a custom directory using `test-config`
  ```
ant test-config -Dtestng.directory=/path/to/data -Dtestng.configDirectory=/path/to/config 
```
Check that for each section, the entries of `.bioformats` file should now be sorted by key. This is meant to simplify diff examination when updating these files.
- modify the created `.bioformats` file under `/path/to/config` and test the new ant variable picks up this configuration file instead of the local file under the data directory tree using
  ```
ant test-automated -Dtestng.directory=/path/to/data -Dtestng.configDirectory=/path/to/config
```

Other scenarios that can be tested:
- test a more complex tree (multiple level of hierarchies under `/path/to/data`)
- test multiple data folders
- test removing the `.bioformats` files under the data directory with the `configDirectory` property set does not affect the tests (for future data repo cleanup)

### CODE REVIEW

**Comment by sbesson** [comment]
Marking as breaking to prevent conflict with https://github.com/openmicroscopy/bioformats/pull/1804

**Comment by sbesson** [comment]
Pushes fixed to address most of the comments above and also fix the logging when writing configuration files to account for new configuration directory.

**Comment by sbesson** [comment]
@jburel: have your also reviewed the functional aspect of this PR? Is it in a safe state to try and set it up in the breaking Jenkins job?

**Comment by jburel** [comment]
@sbesson: not yet, had to do some final prep for Paris. Will do that this evening.

**Comment by jburel** [comment]
test-config => to be renamed to be clearer. Discussed with @sbesson

**Comment by jburel** [comment]
running ```test-automated``` w/o ```.bioformats```. Failure expected
but message could be improved
```
 Ready to test 8 files
   [testng] [TestNG] Running:
   [testng]   Bio-Formats software test suite
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 400, Failures: 112, Skips: 288
   [testng] ===============================================
   [testng] 
   [testng] The tests failed.

```

**Comment by jburel** [comment]
Generally the commands work when tested against a single level directory.
I have tried generating the ```.bioformats``` for a folder containing files (gatan) and a subfolder (containing gatan). The files in the subfolder were not taken into account.

**Comment by sbesson** [comment]
@jburel:
- for the first case (subfolder), was a `.bioformats` file generated under the subdirectory. If not, can you paste the command you ran as I cannot reproduce?
- will test HCS, do you have a stack trace?

**Comment by sbesson** [comment]
@jburel: last two commits should rename the targets as `gen-config` and `gen-config-xml` (old target names are preserved but deprecated) and allow unconfigured directories to be displayed in the main console output.

**Comment by jburel** [comment]
* First point. I was expected that file in the subfolder will have been picked. After discussion with @sbesson, we need to run the command pointing at subfolder. 
I will try again with hcs data.

**Comment by sbesson** [comment]
@jburel @melissalinkert: time to remove out of breaking?

**Comment by jburel** [comment]
I finally received e-mail notification for a comment made 2 days ago!!!!!

**Comment by jburel** [comment]
The new commands work as expected. 
Do we want to have a warning or stop if the file already exists?

**Comment by jburel** [comment]
wrt HCS, It works if the structure is not a subfolder e.g. flex
but it does not work for mias. 
This will require some work, probably outside the scope of this PR

**Comment by melissalinkert** [comment]
Removing breaking label.

**Pull request merged**
