### PR TITLE
Command-line tools: autoscale without fast

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/1x2IXY5X/12-allow-autoscale-to-be-used-without-fast-in-the-cl-tools

To test this PR, confirm that the following command autoscales the image
```
showinf -autoscale /path/to/test.fake
```
and check the amended documentation is sensible.

### CODE REVIEW

**Comment by mtbc** [comment]
Can "This option allows to ..." prefixes be generally omitted?

**Comment by sbesson** [comment]
In favor of what form? `Display the OME-XML alone`? `Displays the OME-XML alone`?

**Comment by mtbc** [comment]
Either would be fine, if consistent. I can't decide what my preference is so it must be pretty weak!

**Comment by mtbc** [comment]
Docs staged at http://www.openmicroscopy.org/site/support/bio-formats5.1-staging/users/comlinetools/display.html.

**Comment by mtbc** [comment]
Works fine on images like `worm.tiff`. :+1: Help still needs updating:
```
$ tools/showinf
...
  -autoscale: used in combination with '-fast' to automatically adjust
              brightness and contrast
...
```

**Comment by sbesson** [comment]
Thanks. Pushed.

**Comment by mtbc** [comment]
Thank you! One more nitpick: suffix with an asterisk to indicate the "may result in loss of precision"?

**Comment by mtbc** [comment]
```
       -crop: crop images before displaying; argument is 'x,y,w,h'
  -autoscale: automatically adjust brightness and contrast (*)
    -novalid: do not perform validation of OME-XML
```
Good to merge.

**Pull request merged**
