### PR TITLE
Initial CellH5 Reader class

### PR DESCRIPTION
**Pull request by sommerc**
Hi there,

this is the cellh5 reader for bioformats. It implements basic viewing of the raw data contained in the cellh5 hdf5 files. I hope I am on the right track and comments are more than welcome (I am a java noob) 

For future versions of the reader, I want to implement:

* multiple series
* more MetaData Tags (e.g. Timestamps)
* export of segmentations as OME-ROI (hint regarding that are also very welcome :))

Cheers,
Christoph

### CODE REVIEW

**Comment by sommerc** [comment]
any ideas?

**Comment by joshmoore** [comment]
Hi Christoph. Sorry for having let this fall through the cracks. The class that is not being found, `ome.xml.model.primitives.PrimitiveNumber` exists in the development version (the upcoming 5.1 from the branch `origin/develop`) but not in, for example, the 5.0 line. I'd assume you have a mismatch in the jars which are installed. You might take a look at a file listing of your fiji installation to see if you recognize any other jars that either weren't copied or that are duplicates of ones you already copied. Another option would be to start in a fresh IJ/FIJI installation. Hope that helps. ~Josh.

**Comment by sommerc** [comment]
that would explain it! Thank you so much Josh for this hint!!!

**Comment by sommerc** [comment]
Refactored the reader, added CH5Coordinate and CH5Constants, removed GUI and added reading of segmentation label images as separate series (@dietzc)

**Comment by sommerc** [comment]
Hmm, maven hiccups on the jhdf5.jar file again... So, what is the preferred way to add jars,which are not available from a public maven repository? Should I create one?

**Comment by melissalinkert** [comment]
The appropriate JHDF5 13.06.2 file has been deployed to our Artifactory: http://artifacts.openmicroscopy.org/artifactory/webapp/browserepo.html?9&pathId=ome.external:ch/systems/cisd/jhdf5/13.06.2/jhdf5-13.06.2.jar

The Maven build should work if you change the version from 2.9 to 13.06.2 in ```components/formats-gpl/pom.xml```.

**Comment by melissalinkert** [comment]
a1ce1c6 is still expected to fail the build, as the original groupId was correct - the JHDF5 jar was deployed to Artifactory with a groupId of ```ch.systems.cisd```.

**Comment by melissalinkert** [comment]
The Maven builds look better now, but somehow some unrelated changes to the specification and cpp components ended up in this PR (which are causing the C++ and documentation builds to fail).  Could you please try merging in the current develop branch from openmicroscopy/bioformats, and check that the diff shows only the changes that you intended to make?

**Comment by sommerc** [comment]
I already merged the current develop branch to my develop branch with

$ git fetch upstream
$ git merge upstream/develop

However, a diff to see which files were affected by my commit yields:

$ git diff --name-status develop..upstream/develop
M       ant/toplevel.properties
M       components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java
M       components/formats-api/src/loci/formats/MetadataTools.java
M       components/formats-api/src/loci/formats/readers.txt
M       components/formats-common/src/loci/common/services/services.properties
M       components/formats-gpl/build.properties
M       components/formats-gpl/pom.xml
D       components/formats-gpl/src/loci/formats/in/CellH5Reader.java
D       components/formats-gpl/src/loci/formats/services/JHDFService.java
D       components/formats-gpl/src/loci/formats/services/JHDFServiceImpl.java
M       components/formats-gpl/src/loci/formats/services/NetCDFService.java
M       components/formats-gpl/src/loci/formats/services/NetCDFServiceImpl.java
D       components/formats-gpl/test/loci/formats/utests/JHDFServiceTest.java
D       components/formats-gpl/test/loci/formats/utests/MissingJHDFServiceTest.java
D       components/formats-gpl/test/loci/formats/utests/test_jhdf.h5
D       components/formats-gpl/test/loci/formats/utests/testng-no-jhdf.xml
M       components/formats-gpl/test/loci/formats/utests/testng.xml
D       components/specification/released-schema/2013-10-dev-1/catalog.xml
D       components/specification/released-schema/2013-10-dev-2/catalog.xml
D       components/specification/released-schema/2013-10-dev-3/catalog.xml
D       components/specification/released-schema/2013-10-dev-4/BinaryFile.xsd
D       components/specification/released-schema/2013-10-dev-4/OMERO.xsd
D       components/specification/released-schema/2013-10-dev-4/ROI.xsd
D       components/specification/released-schema/2013-10-dev-4/ReadMe.txt
D       components/specification/released-schema/2013-10-dev-4/SA.xsd
D       components/specification/released-schema/2013-10-dev-4/SPW.xsd
D       components/specification/released-schema/2013-10-dev-4/catalog.xml
D       components/specification/released-schema/2013-10-dev-4/dev-catalog.xml
D       components/specification/released-schema/2013-10-dev-4/ome.xsd
D       components/specification/released-schema/2013-10-dev-4/omeOxygenDocConfig.xml
D       components/specification/released-schema/2013-10-dev-4/omeOxygenProject.xpr
D       components/specification/released-schema/2013-10-dev-5/BinaryFile.xsd
D       components/specification/released-schema/2013-10-dev-5/OMERO.xsd
D       components/specification/released-schema/2013-10-dev-5/ROI.xsd
D       components/specification/released-schema/2013-10-dev-5/ReadMe.txt
D       components/specification/released-schema/2013-10-dev-5/SA.xsd
D       components/specification/released-schema/2013-10-dev-5/SPW.xsd
D       components/specification/released-schema/2013-10-dev-5/catalog.xml
D       components/specification/released-schema/2013-10-dev-5/dev-catalog.xml
D       components/specification/released-schema/2013-10-dev-5/ome.xsd
D       components/specification/released-schema/2013-10-dev-5/omeOxygenDocConfig.xml
D       components/specification/released-schema/2013-10-dev-5/omeOxygenProject.xpr
M       components/specification/samples/develop/2013-10to06-downgrade.ome
D       components/specification/transforms/2013-06-to-2013-10-dev-4.xsl
D       components/specification/transforms/2013-06-to-2013-10-dev-5.xsl
D       components/specification/transforms/2013-10-dev-4-to-2013-06.xsl
D       components/specification/transforms/2013-10-dev-5-to-2013-06.xsl
M       cpp/lib/ome/bioformats/CMakeLists.txt
M       cpp/lib/ome/bioformats/MetadataTools.cpp
M       cpp/lib/ome/bioformats/tiff/IFD.cpp
D       cpp/lib/ome/bioformats/tiff/TileBuffer.cpp
D       cpp/lib/ome/bioformats/tiff/TileBuffer.h
D       cpp/lib/ome/bioformats/tiff/TileCache.cpp
D       cpp/lib/ome/bioformats/tiff/TileCache.h
D       cpp/lib/ome/bioformats/tiff/TileCoverage.cpp
D       cpp/lib/ome/bioformats/tiff/TileCoverage.h
M       cpp/lib/ome/bioformats/tiff/Types.h
M       cpp/lib/ome/xerces/dom/Document.h
M       cpp/lib/ome/xml/CMakeLists.txt
M       cpp/test/ome-bioformats/CMakeLists.txt
D       cpp/test/ome-bioformats/tiff-coverage.cpp
D       cpp/test/ome-bioformats/tiff-tilecache.cpp
M       docs/sphinx/metadata-summary.txt
D       jar/cisd-jhdf5-batteries_included_lin_win_mac.jar

I did not touch any of the cpp related files. Does not look like whitespace problems either...

Did another merge just now and pushed it, perhaps now it works...

**Comment by melissalinkert** [comment]
c6a130f unfortunately still shows a lot of unrelated changes.

Stepping through the commits, it looks like e0ec19c is the culprit, although 24bb2a8 is also a little suspicious.  Both of those look like partial merges with extra changes included.

If you would rather not sort out what went wrong, we can close this PR, cherry-pick your commits, and then we'll fix as appropriate in a new PR.

**Comment by sommerc** [comment]
Yes, fixing the merge will take longer than a new PR. Do you want the commit history? Otherwise, I just put all changes up to now into a single commit...

**Comment by melissalinkert** [comment]
The commit history is not particularly necessary as far as I'm concerned.

**Comment by sommerc** [comment]
closed PR in favor for new one: #1591

**Pull request closed without merging**
