### PR TITLE
Lsmreader roi

### PR DESCRIPTION
**Pull request by jburel**
Fix ticket https://trac.openmicroscopy.org.uk/ome/ticket/12628

To test this PR
 * Use the files from QA 10344
 * Select the ```.mdb```. The problem will only be seen when it is selected
 * run ```./showinf -omexml  PathToQA/10344/2014.10.30/2014.10.30.mdb```
 * All 40 rois should now be read.

### CODE REVIEW

**Comment by sbesson** [comment]
--depends-on https://github.com/openmicroscopy/bioformats/pull/1704

**Comment by dominikl** [comment]
showinf shows 41 ROIs for this file. If that's correct, good to merge. What other tool can I use to open mdb images to verify this?

**Comment by jburel** [comment]
@dominikl: I might have entered the wrong number..

**Comment by jburel** [comment]
--no-rebase

**Pull request merged**
