### PR TITLE
Reader metadata pages refactoring 

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/kaw2jhNL/20-metadata-pages

This PR:
- renames all reader metadata pages as `metadata/XXXReader.txt` instead of reusing the formats name as previously
- uses the `reader` list in `formats-pages.txt` to link both to the source code on Github and to the reader metadata pages
- removes the deprecated `metadataPage` field in `formats-pages.txt`
- the old metadata pages `formats/xxxx-metadata.txt` are preserved to prevent breaking URLs and a top-level deprecation warning is added with a link to the formats page
- removes the duplicate Slidebook format page in favor of linking to both metadata pages for the `SlidebookReader` and `Slidebook6Reader`
- adds the missing metadata page for the base readers e.g. `BaseTiffReader`

To review this PR, the main entry points are:
- the [main metadata page](https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/metadata-summary.html): all links in the reader list should point to the correct reader metadata page named `metadata/XXXReader`
- the [supported formats page](https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/supported-formats.html). Formats should now link to the source code and the metadata page. Check formats with multiple readers, like Bitplane Imaris and Slidebook, are behaving as expected.
- the old metadata pages e.g. https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/formats/aperio-afi-metadata.html should now have a top-level deprecation warning redirecting to the formats page.

### CODE REVIEW

**Comment by hflynn** [comment]
Initial impression is that it looks good but I'll have a more thorough check when I'm not trying to sort OMERO release stuff at the same time!

**Comment by sbesson** [comment]
@hflynn: last commit should fix the broken links to the writers and combine the readers source code and metadata links into single lines per reader (using lists for formats with multiple readers)

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/1077/ is green, just looking over the pages now

**Comment by hflynn** [comment]
New formatting looks good. I will try to go through all the formats tomorrow to make sure everything is in place.

**Comment by hflynn** [comment]
There is a slight inconsistency as to whether formats are written out in full of the top of the reader (metadata) page (some have the format written out rather than using the abbreviation/extension, some mention the brand and some not) but that isn't the fault of this PR. Some related issues below though, since I'm noticing them reviewing this:

Ivision reader for IPLab-Mac .ipm files is rather obscure (I assume correct tho) - probably an argument for having the actual format referenced in full at the beginning of the reader (metadata) page.

https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/metadata/MNGReader.html - Multiple Network Graphics is actually Multiple-**image** Network Graphics.

https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/metadata/PGMReader.html has 'Portable **Any** Map as the format, but the format page says 'Portable Gray Map.

Are standard PNGs meant to be read by the AnimatedPNG reader? The note says 'Bio-Formats uses the Java Image I/O API to read and write PNG files' so is it misleading to link to a reader here?

https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/metadata/UnisokuReader.html says it reads Unisoku **STM** format - don't know where STM comes from, file extensions are listed as .dat & .hdr

**Comment by hflynn** [comment]
The new pages all look good, barring the minor quibbles above which are not related to this PR, and all link correctly from the formats table.

**Comment by hflynn** [comment]
Random sample of old metadata pages all have deprecation warning at the top

**Comment by hflynn** [comment]
All the links from the metadata table are correct too.

I'm guessing it is right that there are readers that don't link to any format?

**Comment by hflynn** [comment]
Unless the answer to my question about format-less readers is no, I think this is good to merge.

If @sbesson does want to address any of my nitpicks, probably best done in a new PR where I can see the diffs in github (If you want to address here in comments, I can open that PR myself once I have things clarified).

**Comment by sbesson** [comment]
Answering your last question, some readers definitely do not map to any format but act as base readers like `BaseTiffReader`. I would be inclined to capture these suggestions and implement them in a follow-up PR for readability. Waiting for thumbs up from @melissalinkert as well.

**Comment by hflynn** [comment]
That works for me

**Comment by melissalinkert** [comment]
This all seems fine to me.

**Pull request merged**
