### PR TITLE
Add exclude for oxygen files

### PR DESCRIPTION
**Pull request by qidane**
Exclude files `*.xpr` and `omeOxygenDocConfig.xml`

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The change itself is OK.  I wonder though if it would be better to add to .gitignore to prevent them being committed into git in the first place.

**Comment by qidane** [comment]
`omeOxygenDocConfig.xml` is used as part of the release process so we want that in git. I can add *.xpr to `gitignore`

**Comment by qidane** [comment]
@rleigh-dundee Ok?

**Comment by rleigh-dundee** [comment]
Does `omeOxygenDocConfig.xml` also need adding?

**Comment by qidane** [comment]
`omeOxygenDocConfig.xml` is used as part of the release process so we want that in git.

**Comment by qidane** [comment]
--no-rebase

**Pull request merged**
