### PR TITLE
Split Bio-Formats C++ from bioformats.git

### PR DESCRIPTION
**Pull request by rleigh-dundee**
- Drop moved files (bioformats, qtwidgets, docs, examples)
- Install missing ome-xml header; it was private but needs to be public now it's separate
- Register ome-xml paths (schemas, transforms, samples); samples are used to find test samples in dependent modules
- Provide model version information in public header; needed so that dependent modules know which model version they are using for transforms etc.
- Documentation uses doxygen tagfiles to generate cross-references to one-common

The new bioformats-cpp component will build using https://github.com/rleigh-dundee/bioformats-cpp/commits/develop (the CI jobs have been updated to clone this until it's adopted by the ome organisation).

Some additional work will be needed with the one-common path registration and lookup code to allow it to support multiple search locations.  It currently works for the purposes of making the split work, but isn't going to work in all circumstances.

--------

Testing:

- Builds should remain green
- Documentation should have correct cross-references between the bioformats and ome-xml and one-common docs, and between the ome-xml and ome-common docs
- Check that `bf-test info` still works using a superbuild binary archive; this will verify that the path introspection still works
- Check that the contents of the super-build and regular build binary archives are unchanged (bar the fixes to the api reference paths).  A diff of the file listings should be sufficient to check this.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The Windows build falure looks like we need to set BIOFORMATS_HOME to enable it to pick up the correct paths (until we build DLLs and autodetection starts working).

**Comment by rleigh-dundee** [comment]
Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge/

**Comment by sbesson** [comment]
On the docs build,  one more error remaining

```
     [exec] Warning, treated as error:
     [exec] /opt/hudson/workspace/BIOFORMATS-DEV-merge-docs/src/docs/sphinx/about/whats-new.txt:259: WARNING: unknown document: /developers/cpp/overview
```

**Comment by mtbc** [comment]
If I naïvely download `bioformats-cpp-5.2.0-Release-Ubuntu14.04-x86_64.tar.xz` from cod and unpack it on my Debian 8 system then bf-test complains,
```
E: Could not determine Bio-Formats runtime path for “ome-xml-schema” directory
```
but maybe that's to be expected and I ought to read documentation somewhere.

**Comment by rleigh-dundee** [comment]
@mtbc No, that's likely a bug.  Does setting BIOFORMATS_HOME to the installation root mitigate it?

**Comment by mtbc** [comment]
It does indeed. :+1: Now I just get a bunch of XML errors. :smiley: (I assume somewhere we have OME-TIFF samples that bf-info will like.)

**Comment by mtbc** [comment]
No XML errors from OME-TIFFs newly generated by bfconvert. We may just have bad samples.

**Comment by rleigh-dundee** [comment]
@sbesson Docs should be fixed now.

**Comment by rleigh-dundee** [comment]
@mtbc The path issues should now all be fixed.  The next rebuild should produce working prebuilt binaries.

**Comment by hflynn** [comment]
Docs are indeed green now, thanks!

**Comment by rleigh-dundee** [comment]
Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge/

**Comment by mtbc** [comment]
:+1: `bf-test info` from today's `bioformats-cpp-5.2.0-Release-Ubuntu14.04-x86_64.tar.xz` from cod works just fine without setting any environment variables.

**Comment by sbesson** [comment]
Relaunched https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-CPP-DEV-merge/ with `-d "ON"` passed to the script command to have the doxygen documentation built.

**Comment by sbesson** [comment]
After rebuild with the doxygen option turned on, the binary build of https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge/BUILD_TYPE=Release,node=cod/ properly includes the doxygen doc under `share/doc`. Cross-references between the various API documentations are working as expected.

**Comment by sbesson** [comment]
See https://github.com/ome/ome-common-cpp/pull/9#issuecomment-189376485

**Pull request merged**
