### PR TITLE
Release 2015 01

### PR DESCRIPTION
**Pull request by qidane**
The release of the new schema.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#740](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/740/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/740/consoleText) for more details.
Possible conflicts:
  - PR #1479 qidane 'Updated XSLT for units conversion'
    - components/specification/transforms/2013-10-dev-5-to-2013-06.xsl

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#741](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/741/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/741/consoleText) for more details.
Possible conflicts:
  - PR #1479 qidane 'Updated XSLT for units conversion'
    - components/specification/transforms/2013-10-dev-5-to-2013-06.xsl

**Comment by qidane** [comment]
@hflynn @sbesson I am trying to update the links to the schema documentation in the sphinx docs. I ran the job http://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs-autogen/176/ manually (without the --no-pr option) and it made a branch with the changes I was expecting (and a few I was not) here https://github.com/snoopycrimecop/bioformats/tree/develop/merge/autogen but as far as I can tell there was no PR created. What am I doing wrong?

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs/666/ (well-named) including the merge branch auto-generated from this PR is green. Ready to merge.

**Comment by qidane** [comment]
cherry-pick schema typo fixes by @ehrenfeu from https://github.com/imcf/bioformats/commit/fd2be97f0498818cadf807fbcabec82fa796a613

**Comment by sbesson** [comment]
--no-rebase

**Pull request merged**
