### PR TITLE
Genshi source (embedded)

### PR DESCRIPTION
**Pull request by joshmoore**
The genshi requirement added to the Bio-Formats build sometime ago has broken the IDE workflows that we advertise on the webpage, since the code-generation needed for a valid workspace was missing the Python library. In order to restore IDE usage, this PR adds a fallback version of genshi to the build.

Options looked at:
 * Add genshi zip -- unliked, see https://github.com/openmicroscopy/bioformats/pull/1443#issuecomment-64659772
 * Add genshi source -- current solution
 * Download genshi from Maven -- possibly next step

/cc @melissalinkert @rleigh-dundee @sbesson

### CODE REVIEW

**Comment by joshmoore** [comment]
Took the middle ground and commited the source under `components/xsd-fu/python` which requires none of the previous changes to xsd-fu.xml or ome-xml/pom.xml. I'll see if I can pinpoint @dominikl's issues. Removing excluded.

**Comment by joshmoore** [comment]
@dominikl : with Eclipse 4.4, I was asked to install `build-helper:1.4` and I'm still getting "Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.4:add-source (execution: add-source, phase: generate-sources)" for ome-xml.  I can follow the suggestion from Eclipse and get rid of the errors by adding the following to 3 pom.xml files:
```
+                <pluginExecution>
+                  <pluginExecutionFilter>
+                    <groupId>org.codehaus.mojo</groupId>
+                    <artifactId>
+                      build-helper-maven-plugin
+                    </artifactId>
+                    <versionRange>[1.4,)</versionRange>
+                    <goals>
+                      <goal>add-source</goal>
+                    </goals>
+                  </pluginExecutionFilter>
+                  <action>
+                    <ignore></ignore>
+                  </action>
+                </pluginExecution>
```
but I don't know the implications. @melissalinkert? (Also it doesn't seem to be building the source after a `git clean -fdx`)

**Comment by melissalinkert** [comment]
I think that POM change would be fine.

As for not rebuilding, maybe check that it's not trying to read from your ~/.m2/repository/ instead?

**Comment by joshmoore** [comment]
Even though the eclipse support is not 100%, I'm still adding this for review so that we can at least get the genshi failures taken care of.

**Comment by rleigh-dundee** [comment]
Looks fine, though it would be nice if xsd-fu would only import if if it was not already available on the existing python path so that it's only used as a fallback in the absence of a system copy.  It's currently overriding the system copy unconditionally.  The logic to check is already in xsd-fu, it just needs the path adding there, and moving to an alternative path e.g. xsd-fu/genshi rather than xsd-fu/python/genshi.  There may be a cleaner way.

**Comment by joshmoore** [comment]
@rleigh-dundee : understood, but I'd really at least like to get us to the point where IDE users aren't completely broken. I'll rebase this and then someone can look into making this conditional.

**Comment by joshmoore** [comment]
--rebased-to #1546

**Pull request merged**
