### PR TITLE
FlowSight: default to 1 channel if channel tags are missing

### PR DESCRIPTION
**Pull request by melissalinkert**
Fixes the file in QA 10450.

/cc @zeb

### CODE REVIEW

**Comment by bramalingam** [comment]
./showinf -nopix /Users/bramalingam/Desktop/QA/amnis-isx-cif-sample/HeLasusp\ wt200_17.cif 

Works as expected. No exceptions thrown. Good to merge.

**Comment by melissalinkert** [comment]
Would be good to get confirmation from @zeb as well, since he sent the file that this attempts to fix.

**Comment by zeb** [comment]
Sorry I've let this slide - thanks for the nudge, @melissalinkert. 

Importing (via cli and insight) against a merge build (_5.1.0-m3-1151-5b3cf71-ice35-b411_) looks in good shape so far (due to the very large number of images generated from such samples, the import process takes several hours - will keep you posted after completion).

**Comment by zeb** [comment]
CLI import result for the QA sample:
`==> Summary`
`1 file uploaded, 1 fileset created, 14124 images imported, 0 errors in 7:29:14.006`

**Comment by melissalinkert** [comment]
One more commit pushed which should result in each of the image series having 12 channels now instead of 1.  This is using the ```/AssayDB-Rif/Imaging/ChannelInUseIndicators*``` node, since ```/AssayDB-Rif/Display/Channel*Name``` looks like it can define channels that aren't being used (though in this case all 12 are acquired).

The images do seem more sensible to me, but verification would be much appreciated.

**Comment by rleigh-dundee** [comment]
The code changes look OK and there are 12 channels per series for all series.  There appears to be a bottleneck for OMERO import here, probably simply a factor of the series count.

@zeb Is the channel information and pixel data etc. OK for you with the change?

**Comment by zeb** [comment]
Based on the file metadata, this looks fine by me: another sample with `<ChannelInUseIndicators_0_11>1 1 0 1 0 1 0 0 1 0 0 0 </ChannelInUseIndicators_0_11>` does produce 5 channels. Thanks for this change.

**Comment by melissalinkert** [comment]
Thanks @zeb and @rleigh-dundee.  I'd definitely expect OMERO import to be slow and/or memory intensive, since it's going to be creating 14124 * 12 Channel objects in memory, which as discussed in the Tuesday meeting is not easy to deal with.

I assume it's OK to merge this then?

**Comment by zeb** [comment]
Considering the performance implications, I think I'd be happy for this to be put on hold (or toggled via a feature flag is that makes any sense) for further testing if this is likely to become an import bottleneck/cause performance regressions for the original reader's companion samples/be too risky for inclusion in the 5.1 initial release.

**Comment by melissalinkert** [comment]
The original sample data is unaffected, so I would be inclined to merge this since it does fix the original problem.  Import into OMERO was still slow prior to this PR and isn't something we can really address in the reader.

Happy to hear any strong vetos, otherwise I'll merge tomorrow (Thursday) evening.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
