### PR TITLE
Add version history for 5.0.8

### PR DESCRIPTION
**Pull request by sbesson**
Stub version history like we did for 4.4.8

### CODE REVIEW

**Comment by hflynn** [comment]
Building on staging now.

**Comment by hflynn** [comment]
Looks fine on staging, good to merge once Travis is happy.

**Comment by sbesson** [comment]
Now I wonder if the release date won't be a day earlier. I suppose that is not a big deal? /cc @melissalinkert

**Comment by hflynn** [comment]
5.0.7 was a day earlier than claimed too, so at least we'd be consistently out ;)

**Comment by melissalinkert** [comment]
It'll likely be 10 February *somewhere* when the release happens, so fine with me.

**Comment by sbesson** [comment]
--rebased-to #1583

**Pull request merged**
