### PR TITLE
Fake reader: physical size unit support

### PR DESCRIPTION
**Pull request by sbesson**
This PR reviews and clarifies the unit support in the `FakeReader` key/value pair in the documentation and the tests:

- add concrete example of the keys with unit support in the documentation with and without INI file
- remove unit support from `exposureTime` (not implemented)
- add unit tests to `FakeReaderTest` covering the `physicalSize{XYZ}` keys

/cc @ximenesuk @chris-allan @jburel

### CODE REVIEW

**Comment by sbesson** [comment]
See [the staging documentation page](http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/generating-test-images.html) and the [Linux](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/) and [Windows](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build-win) build jobs.

**Comment by dgault** [comment]
Test runs successfully and the new tests added all appear to make sense and produce the desired results. Looks good to merge.

**Comment by chris-allan** [comment]
We are removing the angstrom tests because?

**Comment by sbesson** [comment]
@chris-allan: half of the Angstrom tests failed on CI (https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/129/console and https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build-win/111/console) with:

```
   [testng] ? does not match a length unit!
   [testng] ? does not match a length unit!
   [testng] ? does not match a length unit!
```

which hints at encoding issues in the Jenkins environment. Also I wasn't able to reproduce these issues either locally or on the Jenkins Linux node in an interactive shell.

Unless these failures should be considered as a blocker, the idea behind 1010791 was to get this PR reviewed and merged into the `develop` line and have a follow-up card/PR to address the non-ASCII unit symbols.

**Comment by chris-allan** [comment]
Understood.

Then until that happens lets remove angstrom from the examples with the idea being to re-introduce them once we have the non-ASCII/UTF-8 issues resolved?

**Comment by sbesson** [comment]
@chris-allan: fair enough. a044323 pushed and https://trello.com/c/qTAgtVHT/99-fakereader-add-unicode-units-tests added to investigate encoding unit tests later.

**Comment by chris-allan** [comment]
:+1:

**Comment by sbesson** [comment]
As confirmed by @melissalinkert who reproduced the issue on Windows, the failures arise from the tests storing physical sizes with Angstrom units into INI files - so a044323 is completely justified. Will re-list this PR for final review tomorrow.

**Comment by dgault** [comment]
Reran the tests on a Windows environment and all tests pass and behave as expected. I can also confirm that with the Angstrom tests added back in I can reproduce the fails on Windows but not on Mac. With this documented in the trello card for further investigation I believe this PR is now good to be included.

**Comment by chris-allan** [comment]
Since the default encoding on Windows is either CP-1250 or CP-1252 and we're using `Constants.ENCODING` in the Bio-Formats INI parser that would make sense. We'd have to find a way to consistently pass a UTF-8 encoding through the to INI parser infrastructure from `FakeReader`.

/cc @melissalinkert

**Comment by sbesson** [comment]
Thanks all. Merging this and leaving the INI parser encoding issue for later investigation.

**Comment by joshmoore** [comment]
On the ENCODING front, it might make sense to just stipulate that .fake's `MUST-BE` UTF-8 (as @rleigh-dundee has proposed we do with OME-XML as well).

**Comment by chris-allan** [comment]
Agreed.

**Comment by melissalinkert** [comment]
See https://github.com/openmicroscopy/bioformats/pull/2248.

**Pull request merged**
