### PR TITLE
Update PicoQuant reader to always buffer data.

### PR DESCRIPTION
**Pull request by imunro**
For very large files this reader was prohibitively slow. See https://trac.openmicroscopy.org/ome/ticket/13183

Test using curated .bin files. A larger example is available in QA 17134. Should now load in < 1min.

### CODE REVIEW

**Comment by dgault** [comment]
Code changes look good to me, default sizes seem sensible and I have no further suggestions for improvements.

Tested against files in curated as well as QA-17134, all files open and display correctly and do so in an improved timeframe (< 1 min). 

The sample file from QA-17134 should be added to inbox and data repo PR opened with a config for it. I don't mind opening the config PR if its easier.

**Comment by imunro** [comment]
Thanks. If you could do that it would be great. I do it sufficiently infrequently that I tend to forget steps.

**Comment by dgault** [comment]
Related config PR for QA-17134 is https://github.com/openmicroscopy/data_repo_config/pull/104

**Comment by dgault** [comment]
Since the config PR is now green this should be good to merge - openmicroscopy/data_repo_config#105

The ticket https://trac.openmicroscopy.org/ome/ticket/13183 can also be closed, I dont appear to have permission to do so

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/204/console for the automated tests run against the whole set of `picoquant` sample files (incl. QA 17134).

**Pull request merged**
