### PR TITLE
Operetta: improve MetadataStore population

### PR DESCRIPTION
**Pull request by melissalinkert**
Ported from a private PR; to test, use QA 17826.

Without this change, ```showinf -omexml -nopix Index.idx.xml``` should show OME-XML that does not contain instrument, wavelength, exposure time, etc. values.  With this change, all of the following should be present:

```
Objective.NominalMagnification
Objective.LensNA
Channel.ExcitationWavelength
Channel.EmissionWavelength
Plane.ExposureTime
Plane.DeltaT
Image.AcquisitionDate
```

This likely requires a minor version since it requires configuration changes (PR forthcoming) and adds new fields to an inner class.

### CODE REVIEW

**Comment by joshmoore** [comment]
Will these need to be rebased on top of gh-2892?

**Comment by melissalinkert** [comment]
gh-2892 is already merged into develop (as gh-2900), so I wouldn't think this would need a rebase in order to be merged into develop.  It's probably up to you if/when this goes into ```metadata54```; it may be useful, but is more of a new feature than a bug fix.

**Comment by mtbc** [comment]
Ready to be listed for review?

**Comment by melissalinkert** [comment]
I hadn't been listing this as it almost certainly requires a 5.8.0, but there are no more planned commits so it should otherwise be ready to go.

**Comment by mtbc** [comment]
The effect on the OME-XML for `Index.idx.xml` as far as I can determine seems to be,

```diff
48a49,51
>    <Instrument ID="Instrument:0">
>       <Objective ID="Objective:0:0" LensNA="0.4" NominalMagnification="10.0"/>
>    </Instrument>
49a53
>       <AcquisitionDate>2017-08-01T16:16:48.497</AcquisitionDate>
50a55,56
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
52c58
<          <Channel ID="Channel:0:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:0:0" Name="HOECHST 33342" SamplesPerPixel="1">
55c61
<          <Channel ID="Channel:0:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:0:1" Name="Alexa 647" SamplesPerPixel="1">
59,60c65,66
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16520.559787750244" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16516.560688614845" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.016520559787750244" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.016516560688614845" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
63a70
>       <AcquisitionDate>2017-08-01T16:16:51.010</AcquisitionDate>
64a72,73
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
66c75
<          <Channel ID="Channel:1:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:1:0" Name="HOECHST 33342" SamplesPerPixel="1">
69c78
<          <Channel ID="Channel:1:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:1:1" Name="Alexa 647" SamplesPerPixel="1">
73,74c82,83
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16520.459204912186" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16516.460105776787" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016520459204912186" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016516460105776787" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
77a87
>       <AcquisitionDate>2017-08-01T16:16:53.510</AcquisitionDate>
78a89,90
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
80c92
<          <Channel ID="Channel:2:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:2:0" Name="HOECHST 33342" SamplesPerPixel="1">
83c95
<          <Channel ID="Channel:2:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:2:1" Name="Alexa 647" SamplesPerPixel="1">
87,88c99,100
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16525.190323591232" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16521.189361810684" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.016525190323591232" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.016521189361810684" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
91a104
>       <AcquisitionDate>2017-08-01T16:16:55.963</AcquisitionDate>
92a106,107
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
94c109
<          <Channel ID="Channel:3:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:3:0" Name="HOECHST 33342" SamplesPerPixel="1">
97c112
<          <Channel ID="Channel:3:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:3:1" Name="Alexa 647" SamplesPerPixel="1">
101,102c116,117
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16526.570543646812" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16522.569581866264" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016526570543646812" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016522569581866264" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
105a121
>       <AcquisitionDate>2017-08-01T16:16:43.463</AcquisitionDate>
106a123,124
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
108c126
<          <Channel ID="Channel:4:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:4:0" Name="HOECHST 33342" SamplesPerPixel="1">
111c129
<          <Channel ID="Channel:4:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:4:1" Name="Alexa 647" SamplesPerPixel="1">
115,116c133,134
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16522.86946773529" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16518.87036859989" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.01652286946773529" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.01651887036859989" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
119a138
>       <AcquisitionDate>2017-08-01T16:16:45.933</AcquisitionDate>
120a140,141
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
122c143
<          <Channel ID="Channel:5:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:5:0" Name="HOECHST 33342" SamplesPerPixel="1">
125c146
<          <Channel ID="Channel:5:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:5:1" Name="Alexa 647" SamplesPerPixel="1">
129,130c150,151
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16523.320227861404" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16519.319266080856" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016523320227861404" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016519319266080856" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
133a155
>       <AcquisitionDate>2017-08-01T16:16:58.417</AcquisitionDate>
134a157,158
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
136c160
<          <Channel ID="Channel:6:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:6:0" Name="HOECHST 33342" SamplesPerPixel="1">
139c163
<          <Channel ID="Channel:6:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:6:1" Name="Alexa 647" SamplesPerPixel="1">
143,144c167,168
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16525.92048048973" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="0.0" PositionYUnit="reference frame" PositionZ="16521.919518709183" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.01652592048048973" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="0.0" PositionYUnit="m" PositionZ="0.016521919518709183" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
147a172
>       <AcquisitionDate>2017-08-01T16:17:00.857</AcquisitionDate>
148a174,175
>       <InstrumentRef ID="Instrument:0"/>
>       <ObjectiveSettings ID="Objective:0:0"/>
150c177
<          <Channel ID="Channel:7:0" Name="HOECHST 33342" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="445.0" EmissionWavelengthUnit="nm" ExcitationWavelength="380.0" ExcitationWavelengthUnit="nm" ID="Channel:7:0" Name="HOECHST 33342" SamplesPerPixel="1">
153c180
<          <Channel ID="Channel:7:1" Name="Alexa 647" SamplesPerPixel="1">
---
>          <Channel EmissionWavelength="675.0" EmissionWavelengthUnit="nm" ExcitationWavelength="630.0" ExcitationWavelengthUnit="nm" ID="Channel:7:1" Name="Alexa 647" SamplesPerPixel="1">
157,158c184,185
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16525.810584425926" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0"/>
<          <Plane PositionX="0.0" PositionXUnit="reference frame" PositionY="-1017.0619032953497" PositionYUnit="reference frame" PositionZ="16521.809622645378" PositionZUnit="reference frame" TheC="1" TheT="0" TheZ="0"/>
---
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.025" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016525810584425926" PositionZUnit="m" TheC="0" TheT="0" TheZ="0"/>
>          <Plane DeltaT="0.0" DeltaTUnit="s" ExposureTime="0.05" ExposureTimeUnit="s" PositionX="0.0" PositionXUnit="m" PositionY="-0.0010170619032953496" PositionYUnit="m" PositionZ="0.016521809622645378" PositionZUnit="m" TheC="1" TheT="0" TheZ="0"/>
```

**Pull request merged**
