### PR TITLE
Correct Pixel Size

### PR DESCRIPTION
**Pull request by michaelgoelzer**
LAS X measures from the center of the top left pixel to the center of
the bottom right pixel

### CODE REVIEW

**Comment by michaelgoelzer** [comment]
split off from pull request #2625

**Comment by melissalinkert** [comment]
Configuration updates in progress here: https://github.com/melissalinkert/data_repo_config/tree/leica-lif-pixel-sizes
I expect to have that finished before Monday so that this PR can be included in CI builds.

**Comment by sbesson** [comment]
Tested alongside the configuration changes updating the pixel sizes of the repository files in [this job](https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-repository-subset/184/). Including into tomorrow's build.

**Comment by melissalinkert** [comment]
Merging now that https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-full-repository/424/console is green.

**Pull request merged**
