### PR TITLE
cpp: Collected Windows portability changes

### PR DESCRIPTION
**Pull request by rleigh-dundee**
- Build static libraries on Windows; Unix remains shared
- Add missing header includes and include directory search paths
- Use native filesystem path methods with wide strings
- Add "prerequisites" target to the superbuild which builds all prerequisite libraries but not bioformats itself; primarily for testing
- Ignore annoying MSVC compiler warnings; it warns about stuff which is perfectly OK by the C++ and POSIX standards
- Add support for building all prerequisites with VS2012

--------

Testing: Unix builds should remain green; Windows builds should remain green, and will test the prequisites target and the VS2012 build.

Note that the big External_xerces_files/* are actually only 8 lines of changes--this is due to having to include the whole file rather than a diff against the original.  You can diff against the original xerces source file if you wish, though it will be tested by https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/ in the "11" column (VC11 == VS2012).

Note that the HTML manpage loading in info.cpp can't be tested properly yet--it depends on work not included in this PR since the Windows build isn't yet fully working; the main thing to note is that the Unix behaviour is unchanged and we will be able to fix it in the later PRs.  It does allow this module to compile and link on Windows, however, so it's a step forward to being able to run it.

### CODE REVIEW

**Comment by jburel** [comment]
could you add the diff to the PR so we can clear see the changes (big files)

**Comment by jburel** [comment]
Column 11: all green see https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/

**Comment by rleigh-dundee** [comment]
Diff for icu.  You can see that the main changes here (written by Visual Studio resaving the solution) are to update the format from 11.00 to 12.00 and to set the minimum visual studio version.  Without these changes, `msbuild` uses the wrong version to build with.

```
--- /Users/rleigh/icu/source/allinone/allinone.sln	2015-03-27 21:10:58.000000000 +0000
+++ cpp/cmake/External_icu_files/VC11/source/allinone/allinone.sln	2015-08-06 17:25:08.000000000 +0100
@@ -1,5 +1,5 @@
-Microsoft Visual Studio Solution File, Format Version 11.00
-# Visual Studio 2010
+Microsoft Visual Studio Solution File, Format Version 12.00
+# Visual Studio 2012
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "cal", "..\samples\cal\cal.vcxproj", "{F7659D77-09CF-4FE9-ACEE-927287AA9509}"
 EndProject
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "cintltst", "..\test\cintltst\cintltst.vcxproj", "{3D1246AE-1B32-479B-BECA-AEFA97BE2321}"
@@ -68,10 +68,6 @@
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "testplug", "..\tools\icuinfo\testplug.vcxproj", "{659D0C08-D4ED-4BF3-B02B-2D8D4B5A7A7A}"
 EndProject
 Global
-	GlobalSection(SubversionScc) = preSolution
-		Svn-Managed = True
-		Manager = AnkhSVN - Subversion Support for Visual Studio
-	EndGlobalSection
 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
 		Debug|Win32 = Debug|Win32
 		Debug|x64 = Debug|x64
@@ -339,4 +335,8 @@
 	GlobalSection(SolutionProperties) = preSolution
 		HideSolutionNode = FALSE
 	EndGlobalSection
+	GlobalSection(SubversionScc) = preSolution
+		Svn-Managed = True
+		Manager = AnkhSVN - Subversion Support for Visual Studio
+	EndGlobalSection
 EndGlobal
--- /Users/rleigh/icu/source/allinone/allinone.sln	2015-03-27 21:10:58.000000000 +0000
+++ cpp/cmake/External_icu_files/VC12/source/allinone/allinone.sln	2015-08-06 17:25:08.000000000 +0100
@@ -1,5 +1,7 @@
-Microsoft Visual Studio Solution File, Format Version 11.00
-# Visual Studio 2010
+Microsoft Visual Studio Solution File, Format Version 12.00
+# Visual Studio 2013
+VisualStudioVersion = 12.0.40629.0
+MinimumVisualStudioVersion = 10.0.40219.1
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "cal", "..\samples\cal\cal.vcxproj", "{F7659D77-09CF-4FE9-ACEE-927287AA9509}"
 EndProject
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "cintltst", "..\test\cintltst\cintltst.vcxproj", "{3D1246AE-1B32-479B-BECA-AEFA97BE2321}"
@@ -68,10 +70,6 @@
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "testplug", "..\tools\icuinfo\testplug.vcxproj", "{659D0C08-D4ED-4BF3-B02B-2D8D4B5A7A7A}"
 EndProject
 Global
-	GlobalSection(SubversionScc) = preSolution
-		Svn-Managed = True
-		Manager = AnkhSVN - Subversion Support for Visual Studio
-	EndGlobalSection
 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
 		Debug|Win32 = Debug|Win32
 		Debug|x64 = Debug|x64
@@ -339,4 +337,8 @@
 	GlobalSection(SolutionProperties) = preSolution
 		HideSolutionNode = FALSE
 	EndGlobalSection
+	GlobalSection(SubversionScc) = preSolution
+		Svn-Managed = True
+		Manager = AnkhSVN - Subversion Support for Visual Studio
+	EndGlobalSection
 EndGlobal
```

**Comment by rleigh-dundee** [comment]
Diff for xerces.  This fixes the format version also, and also fixes the debug icu libraries linked against, which the upstream developers messed up.

```
--- /Users/rleigh/xerces-c-3.1.2/projects/Win32/VC11/xerces-all/xerces-all.sln	2015-03-09 22:45:53.000000000 +0000
+++ cpp/cmake/External_xerces_files/projects/Win32/VC11/xerces-all/xerces-all.sln	2015-08-06 17:25:08.000000000 +0100
@@ -1,4 +1,4 @@
-Microsoft Visual Studio Solution File, Format Version 11.00
+Microsoft Visual Studio Solution File, Format Version 12.00
 # Visual Studio 2012
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "all", "all\all.vcxproj", "{E305E46C-9D74-4755-BF57-29DEAEF4DCDD}"
 EndProject
--- /Users/rleigh/xerces-c-3.1.2/projects/Win32/VC11/xerces-all/XercesLib/XercesLib.vcxproj	2015-03-09 22:45:53.000000000 +0000
+++ cpp/cmake/External_xerces_files/projects/Win32/VC11/xerces-all/XercesLib/XercesLib.vcxproj	2015-08-06 17:25:08.000000000 +0100
@@ -538,7 +538,7 @@
     </ResourceCompile>
     <Link>
       <AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
-      <AdditionalDependencies>ws2_32.lib;advapi32.lib;icuuc.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>ws2_32.lib;advapi32.lib;icuucd.lib;%(AdditionalDependencies)</AdditionalDependencies>
       <OutputFile>$(TargetPath)</OutputFile>
       <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
       <GenerateDebugInformation>true</GenerateDebugInformation>
@@ -578,7 +578,7 @@
       <Culture>0x0409</Culture>
     </ResourceCompile>
     <Link>
-      <AdditionalDependencies>ws2_32.lib;advapi32.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>ws2_32.lib;advapi32.lib;icuucd.lib;%(AdditionalDependencies)</AdditionalDependencies>
       <OutputFile>$(TargetPath)</OutputFile>
       <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
       <GenerateDebugInformation>true</GenerateDebugInformation>
@@ -669,7 +669,7 @@
       <Culture>0x0409</Culture>
     </ResourceCompile>
     <Link>
-      <AdditionalDependencies>ws2_32.lib;advapi32.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>ws2_32.lib;advapi32.lib;icuuc.lib;%(AdditionalDependencies)</AdditionalDependencies>
       <OutputFile>$(TargetPath)</OutputFile>
       <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
       <GenerateDebugInformation>true</GenerateDebugInformation>
```

**Comment by jburel** [comment]
When replacing ```native``` by ```string``` to work on windows
Should the same check (pseudo code):
```
ifdef _MSC_VER use wstring()
else user string()
```
be applied in all occurrences?

**Comment by rleigh-dundee** [comment]
@jburel No.  It's needed only when working with native Windows APIs or (in this case) the libtiff API which uses a wide string open method.

**Comment by jburel** [comment]
@rleigh-dundee: thanks for clarification.

**Pull request merged**
