### PR TITLE
ROIs v2

### PR DESCRIPTION
**Pull request by mtbc**
* introduce 2016-DEV0 schema
* remove Shape.Visible from model

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
Please could you drop the changes to `cpp/lib/ome/xml/meta/Convert.cpp`.  Since the C++ code is still using the 2013-06 model, this breaks the metadata coverage tests.

**Comment by mtbc** [comment]
@rleigh-dundee: Sure.

**Comment by mtbc** [comment]
Will reopen against regions branch.

**Comment by mtbc** [comment]
Replaced by #1998.

**Pull request closed without merging**
