### PR TITLE
Remove decoupled components

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Additional work on top of https://github.com/openmicroscopy/bioformats/pull/3081

Remove all components integrated into bio-formats-build, which leaves formats-(api|bsd|gpl).

Note: expected to fail travis/appveyor testing, because it requires an unreleased ome-turbojpeg jar.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Green in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/31/

**Comment by joshmoore** [comment]
Assuming that we want to get out some set of these repositories (e.g. docs) before we release all of them, then likely we will need to revert part of this PR or close it while "phase 1" which is 5.8-compatible is handled.

**Comment by rleigh-codelibre** [comment]
@joshmoore Would we not do 5.8-compatible changes directly on develop?  Isn't `east` completely separate?

**Comment by joshmoore** [comment]
Ultimately, but I was thinking largely to get `latest` green. i.e. I can't merge this and then expect to have an `east`-based full repo build make use of the test-suite.

**Comment by rleigh-codelibre** [comment]
@joshmoore test-suite removal reverted temporarily.

**Pull request closed without merging**
