### PR TITLE
Catch exceptions in isThisType

### LINKED ISSUE #2924: Uncaught exceptions in PQBinReader, FlowSightReader
Hi all,

Here are two uncaught exceptions I see frequently when loading images:

```
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:352)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:103)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
```

```
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:605)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:293)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:110)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:99)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
```

I am able to load images of any supported type. Allowing these exceptions to raise causes a lot of unnecessary noise.

I plan to look into this further in the next few days. However, my Java is quite rusty and I am unfamiliar with the inner workings of this project. If any more experienced contributors have suggestions, I'd love to hear them. :)

Best,
Claire

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2924

### CODE REVIEW

**Comment by dgault** [comment]
Both of this changes look to good and address the exceptions raised in https://github.com/openmicroscopy/bioformats/issues/2924

To test I created specific instances of each reader and tested the isThisType method with incompatible files. Without the PR I was able to reproduce the exceptions, with the PR included the method returned without exception and correctly returned a value of false.

PR looks good to merge.

**Comment by mcquin** [comment]
Awesome! Thanks @sbesson and @dgault !

Out of curiosity, do you have a release date estimate for 5.6.1?

**Comment by sbesson** [comment]
@mcquin thank you for the contribution. Just waiting for a validation of this PR against our data repository before merging this PR. Re the 5.6.1 timelines, we have chosen to get a [small set of features](https://trello.com/b/Lv9ho9Ot/bio-formats-561) in the upcoming patch release. Realistically, we should be able to have a 5.6.1 release of Bio-Formats next week including this PR.

How does that fit with your own timeline esp. re https://github.com/CellProfiler/CellProfiler/issues/2228? Also congrats on getting `python-bioformats` shipping with recent Bio-Formats versions again - it will be greatly valued by the Python community using this library.

**Comment by sbesson** [comment]
The four failures in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/623/ are unrelated to this PR but rather an issue with configuration on our side. Merging for inclusion in the next patch release

**Pull request merged**
