### PR TITLE
ICS Writer - incorrect planes

### PR DESCRIPTION
**Pull request by dgault**
This issue was raised via the Image J forum - http://forum.imagej.net/t/release-of-bio-formats-5-2-0/2523/9

When exporting to ics format the ordering of the image dimensions was incorrect with images from different channels being displayed in the wrong position.

This issue started occuring after other fixes to the ICSWriter in this PR: https://github.com/openmicroscopy/bioformats/pull/2315

The original issue that the PR was solving was: https://github.com/openmicroscopy/bioformats/issues/2237

Note there is an additional issue which can lock up the exporter, this is still open and is not aimed to be fixed yet - https://github.com/openmicroscopy/bioformats/issues/2238

**To reproduce:**
- Import a suitable multi dimensioned image using Bio-Formats
- Export the image to the ICS format
- Open the original image and the ICS image and compare the image planes to verify that they differ

**To test:**
Ensure that the test cases from the original PR pass:
1) Tried checking the same macro in Fiji https://github.com/openmicroscopy/bioformats/issues/2237 to export the file with a splitC to non ".ome" extensions and the export worked. (This meant the issue was not at the exporter level)

2) Tried bfconvert with splitC to convert it into ".ics" files. Even though this does not throw any exceptions, it still does not do the conversion properly. Ensure each channel file is correctly generated.

Additional the following test cases should be used:
3) Import a suitable multi dimensioned image using Bio-Formats
- Export the image to the ICS format
- Open the original image and the ICS image and compare the image planes to verify they match

4) Import a suitable multi dimensioned image using Bio-Formats
- Export the image to the ICS format using combinations of split dimensions
- Open the original image and each ICS dimension image to verify the files have been generated correctly

### CODE REVIEW

**Comment by bramalingam** [comment]
Tested this PR on : smb://squig.openmicroscopy.org.uk/ome/data_repo/test_images_good/dv/CFPNEAT01_R3D.dv

And the PR does not make a difference with BF5.2.1:
1) The export with default options, has the dimensions wrong (1 Z-section missing) and the first Z-section of Channel 2 is wrong as well.
2) The export with split-channels selected exports the image properly.

**Comment by sbesson** [comment]
@dgault did you build the artifacts locally? Given the opening timestamp, this PR was not included into this morning's merge build.

**Comment by dgault** [comment]
This appears to be a new issue discovered. It is present without this PR and manifests itself differently with the PR. Its a bug that we should probably aim to fix as part of this PR if possible. I will attempt to get a resolution ready for retesting tomorrow.

**Comment by bramalingam** [comment]
@sbesson : Nope downloaded the artifacts from the CI server. Sorry for the late response, somehow missed your comment.

**Comment by dgault** [comment]
Last commit will fix the additional bug which Balaji found while testing. The bug related to the image dimensions being written in the ics metadata.

Without this PR the bug would export with a size Z one smaller that actual, resulting in the last z plane appearing missing but being displayed as the first plane of the next channel. With the PR it was resulting in the channel size being one smaller than actual.

**Comment by sbesson** [comment]
Note the last commit failed the minimal conversion tests under https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/.

**Comment by sbesson** [comment]
In addition to the functional testing, is there room for having the scenario of this PR included in the test coverage? Looking minimally in the code, the most appropriate place testing the writer logic at the moment might be the [ConversionTest](https://github.com/openmicroscopy/bioformats/blob/v5.2.2/components/test-suite/src/loci/tests/testng/ConversionTest.java) which is currently executed in an Ant-only target of the `test-suite` component. Alternatively should we think of refactoring the testing of our writers?

**Comment by bramalingam** [comment]
Tested it with the same dv file (using ImageJ) from test_images_good(CFPNEAT01_R3D). Works as expected. Looks good to merge.

**Pull request merged**
