### PR TITLE
Micromanager: clean up JSON metadata parsing

### PR DESCRIPTION
**Pull request by melissalinkert**
See QA 17040.  This should correctly parse various types of arrays and
keys with child attributes.  As noted previously, this should eventually be replaced
by use of a real JSON library.

To test, use the *.txt files from QA 17040.  Without this change, as noted in the comments for QA 17040:

```
You should see lines like this in the metadata display:
Plane #0 08 39 -0800
Plane #0 ] Camera-SaturatePixels
Plane #1 08 40 -0800
Plane #1 ] Camera-SaturatePixels
et cetera. 
```

With this change, none of the metadata keys should contain ```]``` or ```[``` or be just numbers, the ```Camera-SaturatePixels``` key should be present for every plane, and in general there shouldn't be anything that looks odd.  It's also possible to double-check against the actual JSON strings by turning on TRACE-level debugging, but that requires some patience as the JSON strings do not contain line breaks and are thus a little tricky to read as-is.

### CODE REVIEW

**Comment by bramalingam** [comment]
Works as expected. Looks good to merge.

**Comment by sbesson** [comment]
The QA file was properly tested as part of https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/89/. @bramalingam: which datasets/MM versions were tested as part of this  PR review?

**Comment by bramalingam** [comment]
I had just tested the QA file alone, based on the testing instructions. Do you want me to try other datasets as well?

**Comment by sbesson** [comment]
@bramalingam: I would definitely check the impact of this PR minimally on current (1.4.22) and even former Micro-Manager datasets if we have any.

**Comment by bramalingam** [comment]
Tested with MM1.4.21, 1.4.22 and one dataset from 1.4.15. In all cases, the test passed without any issues.

**Comment by bramalingam** [comment]
--rebased-to #2294

**Pull request merged**
