### PR TITLE
xsd-fu: Clean up Java templates

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Remove tabs and trailing whitespace.  No functional changes.  This is a followup to the recent schema code generation work.

https://github.com/openmicroscopy/bioformats/pull/2450/files?w=1 shows the non-whitespace changes (i.e. none).

--------

Testing: Check jobs are green; review source changes.

### CODE REVIEW

**Comment by sbesson** [comment]
Thanks @rleigh-dundee. As we are tackling the whitespace, what's the cost of unifying the Java templates to use the 2 space indentation used for the Java codebase in Bio-Formats? `AggregateMetadata.template` for instance has a mixture of 2 and 4 space indentations.

**Comment by rleigh-dundee** [comment]
@sbesson The main cost is the tedious editing of the templates to get the indentation levels correct.  It's potentially quite fiddly.  I did it for the C++ templates when I originally wrote them, and we can certainly do this for Java, but it's not possible to automatically do due to the conditionals in the templates--you can only easily re-indent a block between conditionals.  Certainly do-able, but it's probably a couple of days work while this PR was 5 minutes with `M-x untabify` in Emacs.

**Comment by sbesson** [comment]
Despite the large diff generated in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-generated-sources/255/, the non-whitespace diff is indeed null:

```
$ git diff -w snoopycrimecop/develop/merge/generated_sources snoopycrimecop/develop/latest/generated_sources  -- components/ome-xml/
$
```

On the https://github.com/openmicroscopy/bioformats/pull/2450#issuecomment-225460772 discussion, I certainly agree with regard to the tediousness of the task. Should we consider parallelizing the work and dividing the Java templates amongst ourselves as we have done for other cleanup epics?

**Comment by sbesson** [comment]
@rleigh-dundee: if you haven't started, I will open a PR against your branch reducing the indentation to 2.

**Comment by rleigh-dundee** [comment]
@sbesson Why don't we just merge this PR as is and do that separately?

**Comment by sbesson** [comment]
Makes sense. Merging, then.

**Comment by rleigh-dundee** [comment]
@sbesson OK, thanks.

I've not started work on the indentation yet, by the way.  When I did this for C++, I did it by reindenting the generated code and then adjusting the templates until the automatic reindentation resulted in zero changes.

**Pull request merged**
