### PR TITLE
Improve the units API

### PR DESCRIPTION
**Pull request by ctrueden**
Specifically, this branch makes the `Quantity` superclass nicer to work with, and adds some helpful constructors with default unit specifications, to avoid errors when converting downstream code to the new API.

See [here](https://github.com/scifio/scifio-ome-xml/compare/ome-5.1) for an example where these changes would be helpful.

/cc @qidane

### CODE REVIEW

**Comment by ctrueden** [comment]
I don't love the `Unit<? extends Quantity> unit()` declaration, but it's the best you can do without introducing a generic parameter to `Quantity`.

**Comment by ctrueden** [comment]
As an aside, it is shame that the OME codebase could not adopt a standard units library. We will need to create an integration layer to bridge OME units to and from SciJava units.

**Comment by ctrueden** [comment]
OK, I see that there are a bunch of new `FormatTools` method signatures that return new quantities with default units. And I guess, if the default unit differs in the schema depending on which field it is, then the new constructors I added above make less sense and are in fact dangerous. Interested to hear others' thoughts.

**Comment by melissalinkert** [comment]
I'd prefer to see 17300c4 reverted, but the other changes read fine.

**Comment by ctrueden** [comment]
@melissalinkert Are there ever two fields in OME-XML that use the same quantity but different units? If so, I will purge the commit. But if not, what's the harm?

If we do eliminate that commit, I would still like to see shorter API calls to create new quantities. As things stand, it is a little verbose to write `meta.setPhysicalSizeX(FormatTools.getPhysicalSizeX(pSizeX)`.

**Comment by melissalinkert** [comment]
```PhysicalSizeX``` on ```Pixels```, ```PositionX``` on ```Plane```, and ```EmissionWavelength``` on ```Channel``` all use the ```Length``` type, but with different default units (microns, reference frame, and nanometers, respectively).

**Comment by ctrueden** [comment]
Thanks @melissalinkert, I purged 17300c4e531670e437f27dbc8190fdecbc1dd303 from the branch.

**Comment by melissalinkert** [comment]
Thanks.  All reads OK now, just waiting on inclusion in the merge builds.

**Pull request merged**
