### PR TITLE
Add version history for 5.1.7

### PR DESCRIPTION
**Pull request by melissalinkert**
Just what it says on the tin.  I didn't add C++ changes since there don't seem to be any dev_5_1 C++ PRs not tagged for 5.1.6 - happy to add if I missed anything.

### CODE REVIEW

**Comment by sbesson** [comment]
Is there a one-line way to explain https://github.com/openmicroscopy/bioformats/pull/2084?

**Comment by melissalinkert** [comment]
Pushed - open to suggestions for better wording.

**Comment by sbesson** [comment]
Yes this is a tricky one and I don't have any better wording as of now - thoughts @dgault @hflynn ?

**Comment by hflynn** [comment]
The wording certainly makes sense to me, can't comment on whether it's a good description of the PR though I'm afraid!

**Comment by dgault** [comment]
Im happy with that wording, its a tricky one to describe but thats certainly the main benefit from a user point of view.

**Comment by jburel** [comment]
added Mark to https://www.openmicroscopy.org/site/about/ome-contributors

**Comment by hflynn** [comment]
Ah thanks for doing that @jburel - I'd forgotten that page existed!

**Comment by dgault** [comment]
Documentation looks good to me

**Comment by jburel** [comment]
@hflynn: I went through the file and added few more

**Comment by hflynn** [comment]
Thanks! I'm going to stick a card somewhere so I don't forget about it again.

**Comment by melissalinkert** [comment]
--rebased-to #2150

**Pull request merged**
