### PR TITLE
Remove jace docs & link to new repo

### PR DESCRIPTION
**Pull request by hflynn**
Companion PR to #2416 removing jace docs and linking to new repo instead.

This PR should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again.

Staged on http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/non-java-code.html

### CODE REVIEW

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/249/ is green

**Comment by sbesson** [comment]
All components of the JACE developer documentation have been migrated to https://github.com/ome/bio-formats-jace/pull/2. Once the Readme is updated with the final modifications and merged, this PR should be ready to go in as well. With regard to deployment, will we need the `support/bioformats*/developers/jace/*` URLs to redirect and point at the decoupled GitHub repository?

**Comment by hflynn** [comment]
I'll fix up the readme this afternoon.
Redirects would be nice, although LOCI is linking to the developers index so I'd consider them an optional extra for completeness.

**Comment by sbesson** [comment]
Feel free to open a post 5.2.0 release card for the redirects. Merging.

**Pull request merged**
