### PR TITLE
Adding addition BF related mailing lists/groups

### PR DESCRIPTION
**Pull request by hflynn**
List of places people look for help with BF issues wasn't complete.

Will be staged on https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/about/index.html#help

Also, rearranged order so OME, ImageJ and Fiji items are grouped together.

### CODE REVIEW

**Comment by hflynn** [comment]
The docs build doesn't like the Fiji google group anchor link but it does work.

**Comment by joshmoore** [comment]
The list makes sense to me. I'll follow up on the card re: internal usage. The only addition that might be worth it if we have text around what we *expect/want* users/developers to do with these lists.

**Comment by hflynn** [comment]
Elsewhere in the BF docs our sole recommendation to mail the ome-users list with problems/bugs. I'm not sure it's worth trying to suggest an alternative policy here given we already know a lot of users get referred to us from elsewhere without ever having read this documentation.

**Comment by hflynn** [comment]
N.B. I'm going to add the Fiji google group link to https://github.com/openmicroscopy/sphinx-ignore-links/blob/master/broken_links.txt so it stops making the build yellow.

**Comment by melissalinkert** [comment]
This is fine to merge then?

**Comment by hflynn** [comment]
From my POV yes. @joshmoore ?

**Comment by joshmoore** [comment]
Yup.

**Pull request merged**
