### PR TITLE
Flex fixes for new sysgro data

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/ZZGjfe10/120-sysgro-continued.  This should resolve all three stack traces noted in the card.  I haven't tried full OMERO imports, so it's possible that there are still issues, but everything I could see from ```showinf -omexml``` works now.

### CODE REVIEW

**Comment by joshmoore** [comment]
```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: import-request-failure
Parameters: {message=, stacktrace=java.lang.NullPointerException
        at loci.formats.in.FlexReader.openBytes(FlexReader.java:280)
        at loci.formats.ImageReader.openBytes(ImageReader.java:462)
        at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:156)
        at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:225)
        at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:349)
        at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:349)
        at loci.formats.MinMaxCalculator.openBytes(MinMaxCalculator.java:269)
```

**Comment by melissalinkert** [comment]
One more fix pushed.

**Comment by melissalinkert** [comment]
One more fix pushed for JL_120904_S32B.

**Comment by joshmoore** [comment]
Ultimately 3 plates were considered too corrupted to worry about. Thanks for the valiant effort. All valid data is now in.

**Pull request merged**
