### PR TITLE
Fix PCIReader test failures on Windows

### PR DESCRIPTION
**Pull request by sbesson**
This PR should fix the few Bio-Rad PIC `test_images_good` samples still failing on Windows. Tested against the PCI subset of the full repository. Automated tests should pass under Windows (to be tested manually) and LInux (see full-repository job)

--no-rebase

### CODE REVIEW

**Comment by melissalinkert** [comment]
https://github.com/sbesson/bioformats/pull/3 opened to fix remaining test failures.  Should be OK to unexclude once that's merged.

**Comment by rleigh-dundee** [comment]
Windows 7 x64 / Java 8u31 64-bit / 4 threads, 8000m

```
[2015-03-24 16:45:37,961] INFO  JPEGReader initializing C:\test_images_good\jpeg\2kx2k.jpg
[2015-03-24 16:45:38,388] ERROR         testPixelsHashes: FAILED (series 0 (807f704fc3d1eb5a576e434ba6b3dda9))
--
[2015-03-24 16:45:38,534] INFO  JPEGReader initializing C:\test_images_good\jpeg\2kx2k.jpg
[2015-03-24 16:45:38,683] ERROR         testSubimagePixelsHashes: FAILED (series 0 (dfa4c719df1d14dbb04efab8b6e10fc6))
--
[2015-03-24 16:45:39,666] INFO  JPEGReader initializing C:\test_images_good\jpeg\2kx2k.jpg
[2015-03-24 16:45:39,936] ERROR         testUnflattenedPixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 16:45:40,083] INFO  JPEGReader initializing C:\test_images_good\jpeg\2kx2k.jpg
[2015-03-24 16:45:40,236] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 16:49:06,773] INFO  BioRadReader initializing C:\\test_images_good\\biorad-pic\\arwen0205_raw00201.pic
[2015-03-24 16:49:06,778] ERROR         testSaneUsedFiles: FAILED ()
--
[2015-03-24 16:45:04,189] INFO  JPEGReader initializing C:\test_images_good\jpeg\8kx8k.jpg
[2015-03-24 16:45:07,801] ERROR         testSubimagePixelsHashes: FAILED (series 0 (db853b871f597241e9f38d21a78d7dd7))
--
[2015-03-24 16:45:23,823] INFO  JPEGReader initializing C:\test_images_good\jpeg\8kx8k.jpg
[2015-03-24 16:45:25,698] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 16:45:30,851] INFO  JPEGReader initializing C:\test_images_good\jpeg\4kx4k.jpg
[2015-03-24 16:45:32,465] ERROR         testPixelsHashes: FAILED (series 0 (4f9da702bdcb4b69e41f908b1d1a2445))
--
[2015-03-24 16:45:32,857] INFO  JPEGReader initializing C:\test_images_good\jpeg\4kx4k.jpg
[2015-03-24 16:45:33,325] ERROR         testSubimagePixelsHashes: FAILED (series 0 (cc7e2899ee44cc9f5406674165c5cba8))
--
[2015-03-24 16:45:37,361] INFO  JPEGReader initializing C:\test_images_good\jpeg\4kx4k.jpg
[2015-03-24 16:45:38,543] ERROR         testUnflattenedPixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 16:45:39,021] INFO  JPEGReader initializing C:\test_images_good\jpeg\4kx4k.jpg
[2015-03-24 16:45:39,414] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
...
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 21408, Failures: 165, Skips: 0
   [testng] ===============================================
```

What those 165 failures are was not logged; I've put the recorded failures above.

**Comment by rleigh-dundee** [comment]
Test on MacOS:

```
1% egrep -h -i 'initiali|fail' target/bio-formats-test-* | grep -B1 -i fail
[2015-03-24 17:46:40,088] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/2kx2k.jpg
[2015-03-24 17:46:40,940] ERROR         testPixelsHashes: FAILED (series 0 (807f704fc3d1eb5a576e434ba6b3dda9))
--
[2015-03-24 17:46:41,188] INFO  JPEGReader initializing /jpeg/2kx2k.jpg
[2015-03-24 17:46:41,446] ERROR         testSubimagePixelsHashes: FAILED (series 0 (dfa4c719df1d14dbb04efab8b6e10fc6))
--
[2015-03-24 17:46:43,313] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/2kx2k.jpg
[2015-03-24 17:46:43,861] ERROR         testUnflattenedPixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 17:46:44,161] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/2kx2k.jpg
[2015-03-24 17:46:44,439] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 17:48:39,547] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/4kx4k.jpg
[2015-03-24 17:48:41,907] ERROR         testPixelsHashes: FAILED (series 0 (4f9da702bdcb4b69e41f908b1d1a2445))
--
[2015-03-24 17:48:42,641] INFO  JPEGReader initializing /jpeg/4kx4k.jpg
[2015-03-24 17:48:43,280] ERROR         testSubimagePixelsHashes: FAILED (series 0 (cc7e2899ee44cc9f5406674165c5cba8))
--
[2015-03-24 17:48:46,624] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/4kx4k.jpg
[2015-03-24 17:48:50,286] ERROR         testUnflattenedPixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 17:48:51,471] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/4kx4k.jpg
[2015-03-24 17:48:52,211] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
--
[2015-03-24 17:49:42,505] INFO  JPEGReader initializing /jpeg/8kx8k.jpg
[2015-03-24 17:49:47,292] ERROR         testSubimagePixelsHashes: FAILED (series 0 (db853b871f597241e9f38d21a78d7dd7))
--
[2015-03-24 17:50:11,886] INFO  JPEGReader initializing /Users/rleigh/images/test_images_good/jpeg/8kx8k.jpg
[2015-03-24 17:50:15,256] ERROR         testUnflattenedSubimagePixelsHashes: FAILED (series 0, resolution 0)
```

**Comment by melissalinkert** [comment]
Alternative JPEG hashes are already allowed, but at the moment they are only configured for the platforms on which Jenkins is running tests.  All of the noted failures are outside the scope of this PR and 5.1.0 (we'll make a more concerted effort to finish the Windows issues once CI builds are running, hopefully for 5.1.1).

**Pull request merged**
