### PR TITLE
Fix duplicate or missing copyrights

### PR DESCRIPTION
**Pull request by melissalinkert**
See https://trello.com/c/zvzrb0lN/122-copyright-policies.  This fixes the few obviously incorrect copyright blocks noted on the card.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
The changes looks fine.  However, there are still two separate copyright notices in WlzReader; could they be merged into one?

**Comment by melissalinkert** [comment]
I left the WlzReader copyright intact (except for the date) so that we're preserving the copyright block added by the original author.  If there's a strong consensus that it's OK to merge the blocks, I can do so, but wanted to be on the safe side.

**Comment by melissalinkert** [comment]
Anyone have further objections to merging?

**Comment by rleigh-dundee** [comment]
Not from me.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
