### PR TITLE
Add JPEG-XR support for CZI data

### PR DESCRIPTION
**Pull request by melissalinkert**
Requires https://github.com/ome/ome-common-java/pull/8

This is a port of work done on private 5.1-based branches to support JPEG-XR-compressed .czi data.  There are also a few changes in the ImageJ plugin to fix obvious problems with reading and displaying RGB thumbnails.  JPEG-XR decoding is provided by an additional dependency on:

https://github.com/glencoesoftware/jxrlib

Relevant data for testing is listed in https://trello.com/c/OHKk0BiI/41-jpeg-xr.  A configuration PR for the public datasets on that card is forthcoming; the private datasets can be reviewed and tested as a follow-up to this PR.  All of the test files contain larger pyramids, so testing in ImageJ/showinf is a little tricky.  The last 2 series in each file are label/macro images which should open easily.  Remaining series are pyramids, so you may only be able to open smaller tiles and not the full image.  Note that the brightfield files (anything with ```BF``` in the name) will show black pixels for missing tiles, where Zen shows white.  This is intentional and expected, but just something to be aware of.

### CODE REVIEW

**Comment by sbesson** [comment]
NB: https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/342/console with this PR included failed against the `zeiss-czi` but so did https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/343/console without this PR against the same dataset. Investigating issues with the test-suite logic.

**Comment by melissalinkert** [comment]
The console output from build 343 shows:

```
Merged PRs:
  # PR 2601 simleo 'Test suite: use canonical paths to remove duplicates'
  # PR 2635 simleo 'Revert changes to handle symlinks with external configuration'
  # PR 2644 rleigh-codelibre 'Build versioning from maven'
  # PR 2647 hflynn 'update developer docs'
  # PR 2648 melissalinkert 'Add JPEG-XR support for CZI data'
```

so I guess this was included in both builds anyway?

**Comment by sbesson** [comment]
@melissalinkert you are correct, I misread the logs. Actually the output of [this build](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/345/console) with the PR included versus [this build](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/343/console) without the PR suggests this PR breaks non-regression tests for some of the non JPEG-XR Zeiss CZI samples in the data repository.

**Comment by sbesson** [comment]
Reading more about https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html, an alternative to https://github.com/openmicroscopy/bioformats/pull/2648/commits/4ebc32311c5e31156caadcf32aa5654138eff29f and the ome-model and ome-poi PRs might be to explicitly declare the `ome-common` dependency at the top of each relevant dependency list in the POMs so that we can individually bump the component version across the board without having to bump all the intermediate component. /cc @rleigh-codelibre

**Comment by melissalinkert** [comment]
Last 5 commits together with https://github.com/openmicroscopy/data_repo_config/pull/154 and https://github.com/openmicroscopy/data_repo_config/pull/155 should fix existing data repo test failures and enable testing for public JPEG-XR samples.

**Comment by sbesson** [comment]
With the corresponding configuration PRs, https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/350 passed including on the JPEG-XR samples which is extremely promising. Also tested in command-line

```
[sbesson@ome-c6100-1 ~]$ /opt/hudson/workspace/BIOFORMATS-DEV-merge-build/tools/showinf -nopix /ome/data_repo/curated/zeiss-czi/zeiss/jpeg-xr/g_FL_1channel_noZ_compression85%.czi 
Checking file format [Zeiss CZI]
Initializing reader
ZeissCZIReader initializing /ome/data_repo/curated/zeiss-czi/zeiss/jpeg-xr/g_FL_1channel_noZ_compression85%.czi
Failure during the reader initialization
[sbesson@ome-c6100-1 ~]$ /opt/hudson/workspace/BIOFORMATS-DEV-merge-repository-subset/tools/showinf -nopix /ome/data_repo/curated/zeiss-czi/zeiss/jpeg-xr/g_FL_1channel_noZ_compression85%.czi
Checking file format [Zeiss CZI]
Initializing reader
ZeissCZIReader initializing /ome/data_repo/curated/zeiss-czi/zeiss/jpeg-xr/g_FL_1channel_noZ_compression85%.czi
Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
Initialization took 1.697s

Reading core metadata
filename = /ome/data_repo/curated/zeiss-czi/zeiss/jpeg-xr/g_FL_1channel_noZ_compression85%.czi
Series count = 8
Series #0 :
```

In order to move forward with the testing and get this PR integrated into the open-source workflow, I would propose the following steps:
- get https://github.com/ome/ome-common-java/pull/8
- cut a new ome-common-java release to Maven Central
- update this PR to consume the new release artifacts and fix Travis
- open/update an OMERO PR to consume the 5.3.0-SNAPSHOT in the merge build /cc @jburel

**Comment by melissalinkert** [comment]
5654c7c bumps all of the split-out components to 5.3.1 and turns Travis green.  When building locally, I needed to explicitly run ```mvn clean``` before ```ant clean jars tools```, as just ```ant clean jars tools``` with whatever cached Maven state resulted in ```ome-common``` 5.3.0 still being used (which built without error, but resulted in an exception during testing).

**Comment by sbesson** [comment]
Note the last commit fails some of the bio-formats-plugins unit tests.

**Comment by melissalinkert** [comment]
Yes, I'm working on that right now and should have a fix pushed shortly.

**Comment by sbesson** [comment]
Travis is green, so was https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/357/ and the manual testing of the last 2 problematic files resulted in similar output as the ones shown by ZEN screenshots. Running https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/360/ against the `zeiss-czi` folder to validate the last commit bumping the `jxrlib` version. Are all the results of the testing captured so that they can be tackled independently? If so, this PR should be ready to merge.

**Pull request merged**
