### PR TITLE
Fix automated tests to handle symlinks with external configuration

### PR DESCRIPTION
**Pull request by sbesson**
Follow up of https://github.com/openmicroscopy/bioformats/pull/1894 and https://github.com/openmicroscopy/bioformats/pull/1819.

While the external configuration logic works accurately on Linux and Windows for the main folder, this PR attempts to solve the case of data folders containing symlinks e.g. `test_images_good`. With the data repository structure being organized as follows:

```
/ome/data_repo/test_images_good      # folder containing symlinks to the data /ome/data_repo/from_skyking/
/ome/data_repo/config/breaking           # folder containing configuration files
```
the goal of this PR is to resolve the symlinks and the configuration files with the following command:

```
ant test-automated -Dtestng.directory=/ome/data_repo/test_images_good -Dtestng.configDirectory=/ome/data_repo/config/breaking/test_images_good
```

The main caveat of this PR is the extensive usage of `File.getCanonicalPath()` which may have some impact on performance while scanning files. This performance should be assessed both on Linux and Windows

To be tested via the breaking jobs.

/cc @melissalinkert

### CODE REVIEW

**Comment by sbesson** [comment]
Pushed one last commit to handle symlinked folders pointing at the raw data + `.bioformats` files vs symlinked raw data files only,

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-breaking-build/275/consoleTest (with this PR)
```
  [testng] [2015-08-11 11:23:42,927] [main] ----------------------------------------
   [testng] [2015-08-11 11:23:42,927] [main] Total files: 246
   [testng] [2015-08-11 11:23:42,927] [main] Scan time: 54.741 s (222 ms/file)
   [testng] [2015-08-11 11:23:42,928] [main] ----------------------------------------
...
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 8300, Failures: 0, Skips: 50
   [testng] ===============================================
```

vs https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-build/275/consoleFull

```
   [testng] [2015-08-10 02:55:16,625] [main] ----------------------------------------
   [testng] [2015-08-10 02:55:16,625] [main] Total files: 246
   [testng] [2015-08-10 02:55:16,625] [main] Scan time: 51.706 s (210 ms/file)
   [testng] [2015-08-10 02:55:16,625] [main] ----------------------------------------
...
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 8300, Failures: 0, Skips: 0
   [testng] ===============================================
```

**Comment by sbesson** [comment]
See also https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-test_images_good/592/consoleText
```
   [testng] Scanning for files...
   [testng] [2015-08-11 03:18:09,795] [main] ----------------------------------------
   [testng] [2015-08-11 03:18:09,795] [main] Total files: 675
   [testng] [2015-08-11 03:18:09,796] [main] Scan time: 83.193 s (123 ms/file)
   [testng] [2015-08-11 03:18:09,796] [main] ----------------------------------------
...
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 22300, Failures: 0, Skips: 0
   [testng] ============================================
```

vs https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-breaking-test_images_good/235/consoleText

```
   [testng] Scanning for files...
   [testng] [2015-08-11 11:52:43,473] [main] ----------------------------------------
   [testng] [2015-08-11 11:52:43,473] [main] Total files: 675
   [testng] [2015-08-11 11:52:43,473] [main] Scan time: 170.467 s (252 ms/file)
   [testng] [2015-08-11 11:52:43,474] [main] ----------------------------------------
...
   [testng] ===============================================
   [testng] Bio-Formats software test suite
   [testng] Total tests run: 22300, Failures: 0, Skips: 0
   [testng] ===============================================
```

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-build/979/, https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-test_images_good/593 and https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-performance/571/

**Comment by melissalinkert** [comment]
Merging, see last comment on https://trello.com/c/tbUfkJiE/6-external-configuration-directory-follow-up.

**Pull request merged**
