### PR TITLE
CellH5 BioFormats reader class / JHDF5 Service

### PR DESCRIPTION
**Pull request by sommerc**

### CODE REVIEW

**Comment by sommerc** [comment]
This PR replaces PR #1161

**Comment by sommerc** [comment]
the test file "test_jhdf.h5" is corrupt or at least differs from the version I added... :-/ Why??

the md5sums of the file are:

local: "5082ba70a5f9383c19ead4861e95f74e *test_jhdf.h5"
remote: "b7d72635a92e50a1874a52e0bebbc481 *test_jhdf.h5"

**Comment by ximenesuk** [comment]
@melissalinkert I listed this for review on Thursday but it didn't get picked up so inherited you name. Would you like a wider review by someone else on the team?

**Comment by melissalinkert** [comment]
Definitely on my radar to review this yet this week.  Another pair of eyes on this might be helpful once it's included, but for now extra review isn't necessary.

**Comment by melissalinkert** [comment]
Closing in favor of https://github.com/openmicroscopy/bioformats/pull/1637, as this isn't currently mergeable and was in need of several fixes anyway (primarily for import into OMERO).

**Pull request closed without merging**
