### PR TITLE
add enumeration values for acquisition mode

### PR DESCRIPTION
**Pull request by mtbc**
Increments OME-XML schema version attribute value and adds acquisition modes,
* BrightField
* SweptFieldConfocal
* SPIM

and parsing for,
* Laser Scan Confocal
* Swept Field Confocal

The schema namespace is left unchanged.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Looks good to me in principle.

However, do we want to add new enumerations to the end of the list to preserve ABI?  We don't have a fixed ABI for C++, so probably not too important there at this point in time, but it would break the ABI by changing the enum values. How do enum additions affect Java?  Not necessarily something which needs affect this PR, but something to bear in mind for how we handle ABI changes in the future.

**Comment by sbesson** [comment]
@rleigh-codelibre thanks for raising the ABI considerations and agreed that we might want to investigate how to minimize breakages in the future - see https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-generated-sources/lastSuccessfulBuild/ for the current enum generated changes on C++ and Java.

**Comment by rleigh-codelibre** [comment]
The latest changes look fine, and the generated source changes show all enums are appended which will preserve the existing enum values.

This looks good to merge, thanks.

**Comment by hflynn** [comment]
Will this require updates to the Model docs too @mtbc ?

**Comment by mtbc** [comment]
Just the autogenerated really, though it's probably also worth a line in "what's new"; we'll catch that in the routine diffs I suggested.

As for the more general issue of extending enumerations, probably the docs checklist item on https://trello.com/c/0zNp8HvU/167-enumerations-addition will cover it, @sbesson?

**Comment by sbesson** [comment]
Documentating the changes in the version 2 of the 2016-06 schema certainly sounds reasonable, I'll add a note to the checklist. Otherwise all tests are passing including the integration testing at the OMERO level which auto-detects new enumeration. Parsing the logs of the [last full repository job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-full-repository/293/ for improperly parsed values shows that the new enumeration are properly picked up.

```
sbesson@lifesci-51950:target $ grep WARN.*Unknown * | wc -l
  171504
sbesson@lifesci-51950:target $ grep WARN.*Acquisition * | wc -l
       0
```

**Pull request merged**
