### PR TITLE
PerkinElmer UltraVIEW VoX link

### PR DESCRIPTION
**Pull request by mtbc**
fixes the broken link to the microscope information

### CODE REVIEW

**Comment by sbesson** [comment]
As this page is auto-generated, this might require a corresponding change in the `components/autogen/src/format-pages.txt` file.

**Comment by mtbc** [comment]
Ah, okay, sorry I thought there was a CI job for that. Will do.

**Comment by mtbc** [comment]
Oh! I thought things in `autogen/` had been autogenerated! Got it the wrong way around, bah.

**Comment by sbesson** [comment]
No worries, the CI job does it the other way around actually. What you can do after changing the autogen component is running the command described in http://www.openmicroscopy.org/site/support/bio-formats5/developers/format-documentation.html to check it has the desired effect on the page.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-docs/199/ being green. Merging.

**Comment by sbesson** [comment]
--rebased-to #2327

**Pull request merged**
