### PR TITLE
Expanding building instructions for netbeans

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/sxKZ49y4/129-update-to-build-instructions and https://trello.com/c/pSlJ3apG/94-review-existing-bf-dev-docs - @imunro requested some additional advice on the build page. Text based on Melissa's comments on the review card.

### CODE REVIEW

**Comment by hflynn** [comment]
Remaining issue is where to put the 'what do you need to build' bit - I wasn't clear where that fitted or indeed what the full answer is.

**Comment by melissalinkert** [comment]
Each of the components and the associated build targets are described in ```developers/components```,so maybe it's enough to just link to that?

**Comment by imunro** [comment]
Looking at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/developers/components.html  I can't immediately see the relationship between the headings on that page and the  modules/projects I see in my IDE (screenshot attached)  
screen shot 2015-01-29 at 17 22 18

**Comment by hflynn** [comment]
I'll leave you to explain that one @melissalinkert

**Comment by melissalinkert** [comment]
@imunro - would it make more sense if the module names were next to the component names on the overview page, e.g. ```formats-api``` becomes ```formats-api (Bio-Formats API)```?  If so, I can do that in a separate PR.

**Comment by imunro** [comment]
By the sound of it that would work.

**Comment by hflynn** [comment]
@melissalinkert if you stick a list of the components in each module on a card for me, I'm quite happy to open a docs PR to fix that up.

**Comment by imunro** [comment]
Maybe I'm being over-critical here & we don't expect those with no Java background (i.e. me) to use these docs ?

**Comment by hflynn** [comment]
@imunro adding the module name to the components isn't a big deal either way so I wouldn't worry about that in this instance

**Comment by melissalinkert** [comment]
See https://github.com/openmicroscopy/bioformats/pull/1569 (I needed to look up the mappings anyway, so was just as easy to open a PR).

**Comment by hflynn** [comment]
Do i need to do anything further on this PR or are you happy for it to be merged @imunro ?

**Comment by imunro** [comment]
Happy to be merged. Looks good to me.

**Comment by hflynn** [comment]
--no-rebase

**Pull request merged**
