### PR TITLE
Unit conversions (XSD from sympy)

### PR DESCRIPTION
**Pull request by joshmoore**
This PR is the Bio-Formats/Schema part of https://github.com/openmicroscopy/openmicroscopy/pull/3530

On review, there should be numerous **more** conversions than there were previously though the math statements may be slightly more complicated. There is currently no handling for the various overflow situations which could arise, since they are likely library dependent.

https://github.com/joshmoore/ome-units/blob/10f6c5a2acc1f7202c6793b8139b7e9400b18f22/templates/xsd#L98 is probably the best place to look at if these should be adjusted.

cc: @qidane 
--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
https://github.com/joshmoore/ome-units/commit/39a0be372bcb6a3266ff8cb6f06ac7dbf865fe59 changes are provided in https://github.com/joshmoore/bioformats/commit/9f3f68806437de80b008197068fd24716cb028d7

**Comment by joshmoore** [comment]
@qidane : I had to swap the direction of the lookups. I assume this was previously broken for many of the SI conversions. Do we have a good test case? (e.g. nanometers to angstroms)

See: https://github.com/joshmoore/ome-units/commit/c66013ef1058c74ff607b0893667f06fbbd72ca5

**Comment by qidane** [comment]
This file has angstroms:
https://github.com/openmicroscopy/bioformats/blob/develop/components/specification/samples/develop/6x4y1z1t1c8b-swatch-instrument-units-alternate.ome

When imported and converted to default units it should match:
https://github.com/openmicroscopy/bioformats/blob/develop/components/specification/samples/develop/6x4y1z1t1c8b-swatch-instrument-units-default.ome
and:
https://github.com/openmicroscopy/bioformats/blob/develop/components/specification/samples/develop/6x4y1z1t1c8b-swatch-instrument-units-none.ome

**Comment by joshmoore** [comment]
Pushed further changes to match:
 * https://github.com/joshmoore/ome-units/commit/c2806c360691a9e1681a89f4ffeef3f995e1531c
 * https://github.com/openmicroscopy/openmicroscopy/pull/3584

**Comment by melissalinkert** [comment]
Any reason not to merge this?

**Comment by joshmoore** [comment]
I think tomorrow there should be an integration test run to check these. Probably worth waiting on that. Just merge if all is green? cc: @jburel

**Comment by jburel** [comment]
All the tests now pass, PR opened see https://github.com/openmicroscopy/openmicroscopy/pull/3614. I have also run the transform against the sample files. I have error with stylesheet to investigate but not related to this PR.

**Comment by jburel** [comment]
I have added more tests covering the full model. The failures are not due to the conversion.
All elements are converted.

**Comment by jburel** [comment]
Only thing notice, the version of the stylesheet is 2, it should be 1 to match the other stylesheet

**Comment by joshmoore** [comment]
Pushed version change: `s/2.0/1.0/`

**Comment by jburel** [comment]
noticed locally
(30.0, , RepetitionRate, Laser). => no units
the one in the file UNITS.AHZ

**Comment by joshmoore** [comment]
From which unit to which? Sorry, I'm not following.

**Comment by jburel** [comment]
frequency in the file for repetition rate is 30 AHZ
default in model. Hz

**Comment by jburel** [comment]
also noticed in the log:  units-conversion.xsl - ERROR - ConvertValueToUnit, cannot perform conversion from any unit to [µm].

**Comment by jburel** [comment]
@joshmoore: ignore comment about repetition rate. Error in the stylesheet.

**Pull request merged**
