### PR TITLE
FEITiffReader - Using native units

### PR DESCRIPTION
**Pull request by dgault**
Using metres for physical size rather than micrometres

### CODE REVIEW

**Comment by melissalinkert** [comment]
Does this need to be updated for inclusion in 5.1.6?

**Comment by dgault** [comment]
These changes are showing issues when the physical size is calculated from magnification settings ie:

private static final double MAG_MULTIPLIER = 0.0024388925;

String magnification = ini.getTable("Vector").get("Magnification");
sizeX = new Double(magnification) * MAG_MULTIPLIER;
sizeY = new Double(magnification) * MAG_MULTIPLIER;

**Comment by dgault** [comment]
Related Config PR - https://github.com/openmicroscopy/data_repo_config/pull/49

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-repository-subset/182/console looks good.

**Comment by dgault** [comment]
Note: This PR requires https://github.com/openmicroscopy/bioformats/pull/2084

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-5.1-merge-full-repository/696/

**Comment by dgault** [comment]
--rebased-to #2140

**Pull request merged**
