### PR TITLE
Remove JACE C++ bindings from the Bio-Formats source code repository

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/ZizTu2RX/4-bio-formats-jace-decoupling

The JACE binding have been migrated to a [standalone repository](https://github.com/ome/bio-formats-jace). This PR removes these bindings from the Bio-Formats source code repository.
One question remains about the documentation pages under `docs/sphinx/developers/jace`. Should these be migrated to the filtered repository as well as either Sphinx or a readme? Should we keep a stub index.html? /cc @hflynn

### CODE REVIEW

**Comment by hflynn** [comment]
My preferred option would be to link to the repo from https://www.openmicroscopy.org/site/support/bio-formats5.2/developers/non-java-code.html and remove all the doc pages in the jace subfolder. I would just put all the content removed into a readme as the easiest option.

**Comment by rleigh-dundee** [comment]
The changes themselves all look fine to me.

**Comment by hflynn** [comment]
@sbesson do you want me to open a PR to delete the docs pages and link to the new repo? https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/248/warnings3Result/ is complaining about the code links on the jace overview page being broken now.

**Comment by sbesson** [comment]
@hflynn: please I won't have any time to address this today.

**Comment by hflynn** [comment]
no problem, I'll open a PR against the new repo to shift the content to the readme too, we can tweak it later as needed.

**Pull request merged**
