### PR TITLE
Improve AFI and SVS metadata

### PR DESCRIPTION
**Pull request by melissalinkert**
Backported from a private PR.

This updates ```AFIReader``` to more closely mirror ```SVSReader```, updates image names to use the same format as https://github.com/openmicroscopy/bioformats/pull/3094, and fixes exposure time and channel name metadata.

SVS tests should continue to pass with no configuration changes.  AFI files require updated configuration; the main things to check using any ```.afi``` from ```curated/afi/samples``` are:

* ```showinf -nopix file.afi``` and ```showinf -nopix -noflat file.afi``` show the same series counts and dimensions as ```showinf -nopix file_xyz.svs``` and ```showinf -nopix -noflat file_xyz.svs```
* ```showinf -nopix -omexml file.afi``` shows plausible exposure times - less than 1 second with this change, compared with hundreds of seconds with develop
* ```showinf -nopix -omexml file.afi``` shows channel names that correspond to the names of the grouped .svs files
* ```showinf -nopix -noflat file.afi``` shows image names that clearly indicate the label and macro series as in https://github.com/openmicroscopy/bioformats/pull/3094
* ```showinf -nopix file.afi``` shows 3 entries for each key in the original metadata table, one per channel

073ecff, 30434e2, and 1344477 add logic for handling pyramid resolutions and thumbnails with mismatched pixel types.  If there is a mismatch within resolutions of a single SVS, then anything not matching the full resolution image is removed.  If there is a mismatch between the whole pyramid in two SVS files (e.g. one SVS has all 16-bit images, and one has all 8-bit images), then the narrower pixels are expanded.  Often this indicates inconsistent post-processing, but I don't have a good example for testing as these cases are expected to be very rare in practice.  I could add ```WARN``` or ```ERROR``` level logging if that would help, and/or an option to turn off that logic.

This does require a minor release as memo files will be affected.  I don't have any other planned AFI/SVS changes though, so it's not blocking anything and can be medium/low priority for 5.9.0.

### CODE REVIEW

**Comment by sbesson** [comment]
Passed in https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-test-folder/7424/console and https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-test-folder/7364/console.

Note the changes proposed here to `SVSReader` conflicts with the refactoring that happened on the `east` branch. /cc @joshmoore @rleigh-codelibre

**Comment by sbesson** [comment]
Discussed earlier at the Formats meeting with @melissalinkert. This change is a candidate for 5.9.0 but not critical for the Users meeting in any way especially with regard to the ongoing work on OME-TIFF pyramids. Leaving it open for inclusion in the daily testing but this. When we are ready to reintegrate `east` into `develop`, this can be excluded  and conflicts can be fixed after merging

**Comment by sbesson** [comment]
Excluding from the daily builds for the scope of 5.9.0 as the changes in this PR would break memo files which is outside the contract of the release.

**Comment by melissalinkert** [comment]
One more commit added from a recent private PR, which adds channel color population for .afi datasets.  ```showinf -nopix -omexml``` on ```data_repo/curated/afi/samples/*.afi``` and/or opening in ImageJ with ```Composite``` color mode can be used to verify that colors are present.

**Comment by melissalinkert** [comment]
Conflicts now resolved and https://github.com/openmicroscopy/data_repo_config/pull/335 opened with updated AFI configurations.  Removing exclude label for now; if builds fail too much, can re-exclude.

**Pull request merged**
