### PR TITLE
C++: Add simple plane viewer

### PR DESCRIPTION
**Pull request by rleigh-dundee**
This is not new code.  This is https://github.com/openmicroscopy/bioformats-examples/tree/master/cpp/glview integrated into the bioformats build.  Changes include:

- cmake checks to make Qt support optional; OME_QTOPENGL is used to conditionally build and install the viewer if system support for Qt and OpenGL/GLM is present.
- add ome-qtwidgets library containing GL plane viewer, GL renderable object types and navigation view widgets; these were all present in the old repo, but here they are all factored out into separate classes and source files, with some additional cleanup and enhancement on top of that
- add glview viewer using ome-qtwidgets

Caveats:

- as for showinf, this is currently hardcoded to use `OMETIFFReader` in the absence of `ImageReader`.
- only the first series is viewable due to not yet having any UI control to switch series
- there seems to be a problem with RGB data; multiple planes work OK, but needs further investigation
- renderer is currently using a greyscale LUT with over/undersaturation (HiLo like ImageJ) to demonstrate LUT rendering.  Does not yet support channel colours from the metadata or blending multiple channels to view them at once.

Note travis does not test the viewer since Ubuntu 12.04 doesn't have Qt5.  If you're building from source, install `qt5` and `glm` to build the viewer.

--no-rebase

--------

Testing:

- Run `./bf ./cpp/bin/glview/glview`
- Open OME-TIFF (File->Open or Ctrl-O)
- Image should load and show the first plane
- Sliders should allow navigation in all available dimensions

Should look similar to this:

glview-vessels1

### CODE REVIEW

**Comment by mtbc** [comment]
"travis does not test the viewer": Should I run something locally to test the viewer, with ctest or whatever, ideally without having to the entire BF C++ test suite?

**Comment by mtbc** [comment]
"Ubuntu 12.04 doesn't have Qt5": seems to be little hope of a `libqt5-dev` in Debian too.

**Comment by rleigh-dundee** [comment]
They are likely available in testing (below is Ubuntu 14.10), but your best bet is to download and run http://download.qt-project.org/official_releases/online_installers/qt-opensource-linux-x64-online.run
to install Qt 5.4 for Linux.  If you add the bin dir to your PATH, should get picked up, or else you can set -DQT5_DIR=/path/to/qt5 when running cmake.

```
libqt5clucene5:amd64                            install
libqt5concurrent5:amd64                         install
libqt5core5a:amd64                              install
libqt5dbus5:amd64                               install
libqt5designer5:amd64                           install
libqt5designercomponents5:amd64                 install
libqt5gui5:amd64                                install
libqt5help5:amd64                               install
libqt5network5:amd64                            install
libqt5opengl5:amd64                             install
libqt5opengl5-dev:amd64                         install
libqt5printsupport5:amd64                       install
libqt5qml5:amd64                                install
libqt5quick5:amd64                              install
libqt5quickwidgets5:amd64                       install
libqt5sql5:amd64                                install
libqt5sql5-sqlite:amd64                         install
libqt5svg5:amd64                                install
libqt5svg5-dev:amd64                            install
libqt5test5:amd64                               install
libqt5webkit5:amd64                             install
libqt5widgets5:amd64                            install
libqt5xml5:amd64                                install
pyqt5-dev                                       install
qdbus-qt5                                       install
qt5-default:amd64                               install
qt5-qmake:amd64                                 install
qtbase5-dev:amd64                               install
qtbase5-dev-tools                               install
qttools5-dev:amd64                              install
qttools5-dev-tools                              install
```

**Comment by mtbc** [comment]
Seems to be having all kinds of trouble, e.g., from `test_images_good`, `tubhiswt_C2.ome.tif` gives me,
```
terminate called after throwing an instance of 'ome::bioformats::FormatException'
  what():  Unmatched filename for UUID ‘urn:uuid:1fdb0a1a-5374-46da-bd24-d04e8cbf3175’
Aborted
```
and `4D-series.ome.tif` gives me,
```
***** Internal Program Error - assertion (i < N) failed in const T& boost::array<T, N>::operator[](boost::array<T, N>::size_type) const [with T = bool; long unsigned int N = 9ul; boost::array<T, N>::const_reference = const bool&; boost::array<T, N>::size_type = long unsigned int]:
/usr/include/boost/array.hpp(129): out of range
Aborted
```
and `8x binning int 125x50 286fps_1.ome.tif` gives me,
```
terminate called after throwing an instance of 'std::logic_error'
  what():  CoreMetadata null
Aborted
```
etc. Which files *should* I be using for testing? By the way, `ctest` tells me,
```
100% tests passed, 0 tests failed out of 43
```

**Comment by mtbc** [comment]
After the compilation it seems to still need the original source directory around:
```
mtbc@ls28101:/tmp/build$ ./bf ./cpp/bin/glview/glviewterminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::canonical: No such file or directory: "/home/mtbc/src/bioformats/components/specification/released-schema/catalog.xml"
Aborted
```

**Comment by rleigh-dundee** [comment]
@mtbc That's expected.  Unless you do `make install` to do a full install, it will need files from the source tree in addition to the build tree.

**Comment by mtbc** [comment]
Oh! That makes sense, thank you.

**Comment by mtbc** [comment]
Had various discussions about known issues and mentioned RFEs to @rleigh-dundee. As far as I am concerned, this PR is already good to go, later PRs can make improvements.

**Comment by rleigh-dundee** [comment]
Green in https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp/617/  This adds some portability workarounds for MacOS 10.8 and adds min/max labels to the constrast sliders in the UI.

**Pull request merged**
