### PR TITLE
ND2: add the PFS offset and status to the original metadata table

### PR DESCRIPTION
**Pull request by melissalinkert**
Fixes http://trac.openmicroscopy.org/ome/ticket/12560.  To test, verify that ```PFS Offset``` and ```PFS Status``` entries appear in the original metadata table for .nd2 files that have PFS data listed in the acquisition metadata tab in NIS Elements Viewer.  I was testing with ```nd2/fiji-655/01.nd2```, though it might be a good idea to spot check one or two others.

I would expect builds to remain green.

### CODE REVIEW

**Comment by dominikl** [comment]
Tested with the same file nd2/fiji-655/01.nd2, couldn't find another nd2 file with PFS data. The PFS data is there, in the original metadata table. But I can't open the image in Insight, also thumbnail is black. Bioformats showinf also just shows a black image. So are all nd2 images in today's build.

**Comment by dominikl** [comment]
Probably related to #1551 ... Will test again later, when this PR got excluded.

**Comment by dominikl** [comment]
Tested again with today's build and image nd2/fiji-655/01.nd2. PFS data is there. Also was able to import and view the image. Looks good to merge to me.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
