### PR TITLE
Messy binary

### PR DESCRIPTION
**Pull request by qidane**
Is this an ok approach?

I think it would need OMETiffWriter.java and OMEBinaryOnlyTiffWriter.java defined from a common code (OMECoreTiffWriter.java?) that has almost all of the functions from OMETiffWriter.java. The current approach is a bit messy. (e.g. a function called closeParentWorkaroundToFix)

The other approach is putting a lot of conditionals into OMETiffWriter.java and having a function to set a flag, something like setSaveBinaryOnly(true).

Also at the moment is is saving 1 companion and 1 tiff with all the planes in it. Working on that bit now. The %z in the filename is currently being ignored.

--exclude

@melissalinkert @joshmoore

### CODE REVIEW

**Comment by ximenesuk** [comment]
Wow, this one is heading towards its first birthday. Anything need doing with it @qidane @melissalinkert or should we order a cake?

**Comment by qidane** [comment]
Rebased onto current develop

**Comment by jburel** [comment]
I will look at it post 5.1

**Comment by jburel** [comment]
Closing this PR. Will spend looking at it during 5.1.3

**Pull request closed without merging**
