### PR TITLE
Adding support for Princeton Instruments .spe data

### PR DESCRIPTION
**Pull request by dgault**
This is a new reader to add support for Princeton Instruments .spe files
Specification and sample files can be found on the related ticket:
https://trac.openmicroscopy.org/ome/ticket/12852

Splitting from https://github.com/openmicroscopy/bioformats/pull/1964

### CODE REVIEW

**Comment by sbesson** [comment]
See Findbugs warnings in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-5.1-merge-build/1009/findbugsResult/

**Comment by dgault** [comment]
I've committed a fix for the warnings by updating the reader to use DataTools for converting to and from byte values.

**Comment by joshmoore** [comment]
Marking as `breaking` since this is targeted for the next major version (at the moment, 5.2.0)

**Comment by mtbc** [comment]
Doing okay outside breaking? Wait until after 5.1.7 release to review?

**Comment by dgault** [comment]
Yeah, the sample files still need adding to the test coverage before it can be reviewed

**Comment by sbesson** [comment]
Added ON_HOLD label. Let us know when a sample file/configuration PR is ready for this to be reviewed.

**Comment by dgault** [comment]
Associated configuration PR - https://github.com/openmicroscopy/data_repo_config/pull/61
2 sample files have been added to the inbox

**Comment by dgault** [comment]
https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-repository-subset/56/console

**Comment by melissalinkert** [comment]
Merging as-is given that jobs are green.  I have a couple of minor worries with respect to things like ```bitsPerPixel``` and the ROI indexing, but will address those in a following PR.

**Pull request merged**
