### PR TITLE
Test suite reafctor native units

### PR DESCRIPTION
**Pull request by dgault**
Rebased PR https://github.com/openmicroscopy/bioformats/pull/2050 onto develop branch

### CODE REVIEW

**Comment by sbesson** [comment]
Is 9a23992 meant to be here ?

**Comment by dgault** [comment]
No, i'm not sure were that's come from, investigating now

**Comment by dgault** [comment]
Reverted 9a23992 
I must have taken 1 commit to many when I did the rebase

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/8/console for an application of this PR on a subset of folders with non-native units.

**Comment by sbesson** [comment]
@dgault: re-reading the commit list, would it be possible to force push away 9a23992 and its reverting commit from this PR?

**Comment by dgault** [comment]
Removed 9a23992 and the revert commit

**Comment by sbesson** [comment]
Tested via https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/9/. Merging to prevent rebasing conflicts.

**Comment by sbesson** [comment]
--rebased-from #2050

**Pull request merged**
