### PR TITLE
ScreenReader: fix channel names population

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/oP1oQobf/612-idr0035-caie-drugresponse-bbbc021 

The import of IDR 0035 revealed an issue when populating the channel names using the `ChannelNames` value of the `.screen` files. The bug mostly arose in the case of sparse screens i.e. when not all wells and fields are populated.

This PR should include the fix (using the well-sample index rather the well index) as well as a minimum set of unit tests for `ScreenReader` including a test of the minimum specification for screen files as well as a screen file reproducing the issue 13588b7 .

With this PR, Travis should remain green and including the new `ScreenReaderTest` unit tests. Additionally, the screen files generated in https://github.com/IDR/idr-metadata/pull/255 should properly populate the channel names for all individual well samples of the BBBC021 plates.

### CODE REVIEW

**Comment by sbesson** [comment]
Closing this for now as we are focusing on getting other deliverables out of the door. Once a team picks up the new IDR 0035 dataset as part of this roadmap, this can be either reopened or individual commits can be cherry-picked appropriately.

**Comment by manics** [comment]
Looks like travis is broken on the `metadata54` branch

**Comment by sbesson** [comment]
Thanks @manics, last set of commits should backport the relevant commits to fix the Unidata artifactory URL as well as the Appveyor configuration and selectively disable the latter on this branch.

**Comment by sbesson** [comment]
@bramalingam have you checked this PR (deployed on idr-testing) does not corrupt the loading of the first images of each plate of all screen-based studies? Once verified, we should be able to cut the release of `idr:formats-{bsd,gpl}:0.4.1` and release the software stack for IDR 0.4.5.

**Comment by bramalingam** [comment]
Tested IDR35 and its images via the client, travis is passing and checked the tests for code changes as well. Everything works as expected. Looks good to merge, according to me.

**Comment by bramalingam** [comment]
@sbesson 
Tested the UI(opening an image from one of the plates) for screens imported from the following directories (which contained .screen files):

./idr0036-gustafsdottir-cellpainting/screens
./idr0012-fuchs-cellmorph/secondary/raw/screens
./idr0004-thorpe-rad52/screens
./idr0026-weigelin-immunotherapy/screens
./idr0025-stadler-proteinatlas/screens
./idr0011-ledesmafernandez-dad4/screens
./idr0033-rohban-pathways/screens
./idr0012-fuchs-cellmorph/primary/raw/screens
./idr0015-UNKNOWN-taraoceans/screenA/patterns
./idr0013-neumann-mitocheck/screens
./idr0016-wawer-bioactivecompoundprofiling/screens

And the images opened without any issues. Guess that sorts all of the test cases. Looks good to merge according to me.

**Comment by sbesson** [comment]
Thanks @bramalingam

**Pull request merged**
