### PR TITLE
minor code cleanup for formats classes

### PR DESCRIPTION
**Pull request by mtbc**
Should slightly improve performance, maybe readability, but not make behavioral changes. Check that code looks like it will do the same as before and that CI passes. Partly about introducing good patterns before people copy them into further code.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-push#613](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-push/613/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-push/613/consoleText) for more details.
Possible conflicts:
  - PR #2492 melissalinkert 'Kodak: handle CCD temperature stored in hexadecimal'
    - components/formats-gpl/src/loci/formats/in/KodakReader.java

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-DEV-merge-push#615](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-push/615/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-push/615/consoleText) for more details.
Possible conflicts:
  - PR #2492 melissalinkert 'Kodak: handle CCD temperature stored in hexadecimal'
    - components/formats-gpl/src/loci/formats/in/KodakReader.java

**Comment by mtbc** [comment]
Force-pushed away some of the commits to reduce number of changed files; may thus avoid conflicts. (If the PR's still unworkable after this, just exclude and I'll attend to it upon my return.)

**Comment by mtbc** [comment]
Travis doesn't seem to be picking this up.

**Comment by sbesson** [comment]
I suspect the usage of guava in the MNGReader class is likely responsible for the failures observed in test_images_good and https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/272/. Marking as breaking for confirmation.

**Comment by sbesson** [comment]
After marking this PR as breaking, https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-repository-subset/97/ and https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-repository-subset/273/ confirmed it is responsible for the memoization issue due to the use of Guava. Closing this as it will not make the 5.2.0 cut with @mtbc away, we should be able to reopen more specific PRs in 5.2.x (e.g. only Vector->List).

**Comment by mtbc** [comment]
Removed offending commit; can now reopen to see how this now is in breaking?

**Comment by sbesson** [comment]
Using `breaking` for testing is fine. As you pushed away, you might not be able to reopen this PR directly but might have to create a new one.

**Comment by mtbc** [comment]
Weird. You don't have an open button for it either? Okay, might split into a couple then while I'm at it, ta.

**Comment by sbesson** [comment]
No, I don't have one either although this looks like the expected upstream behavior - see https://github.com/isaacs/github/issues/361 for a related discussion. Splitting into smaller topical PRs would be good to ease the review process as well.

**Comment by mtbc** [comment]
Okay. Given how the commits somewhat build on each other I'll probably break into a couple of rounds of a couple of PRs.

**Comment by mtbc** [comment]
Superseded by #2528 which changes far fewer files than even this reduced PR.

**Pull request closed without merging**
