### PR TITLE
cpp: LICENSE: Add BSD licence text

### PR DESCRIPTION
**Pull request by rleigh-dundee**
See https://github.com/ome/ome-common-cpp/pull/23

### CODE REVIEW

**Comment by mtbc** [comment]
So we have this BSD license in this `cpp` directory but the GPL in a parent directory; it's sufficiently understood that this overrides that for this bit?

**Comment by rleigh-dundee** [comment]
This is duplicating what's already done for `formats-bsd`, so is following existing practice.  It will hopefully be resolved when we split the model out of bioformats.git.

**Comment by mtbc** [comment]
:+1: Fair enough.

**Comment by mtbc** [comment]
This now looks good to me. :+1:

**Pull request merged**
