### PR TITLE
Removing version banner at top of docs

### PR DESCRIPTION
**Pull request by hflynn**
5.1.x isn't really 'new' anymore with the release of 5.1.4 and BF users are generally upgrading regularly anyway so the banner is just unnecessary visual clutter (previous versions are still available from the docs menu on the website).

### CODE REVIEW

**Comment by hflynn** [comment]
Random Maven build failure it would appear, unrelated I assume

**Comment by hflynn** [comment]
https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/ looks fine

**Comment by sbesson** [comment]
:+1:

**Comment by sbesson** [comment]
@hflynn: I suppose you want the same PR opened against ome-documentation?

**Comment by hflynn** [comment]
That was my plan, was just sorting out Ola's PR and the help stuff first.

**Pull request merged**
