### PR TITLE
Fix at least one typo.

### PR DESCRIPTION
**Pull request by ehrenfeu**
`s/([Aa])t lease/$1t least/`

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @ehrenfeu. Included in builds.

**Comment by mtbc** [comment]
Excellent, thank you, I had been meaning to get around to this one! :smiley: Looks good to me. :+1:

**Comment by mtbc** [comment]
@qidane: If we fix typos in old schemas, is there some manual process by which we make the corrections "live" at the URLs?

**Comment by qidane** [comment]
The full schema release process (which I will be demoing today!) is needed. And you would also need to regenerate all the generated documentation for the schema versions affected. 

There are probably other typos in there.

**Comment by qidane** [comment]
Oh, we would also need to rebase the branch we made yesterday or pull in this commit. If not it will all need done again.

**Comment by qidane** [comment]
Could we split this commit and just make the schema changes for the xsd files directly on 2015-01 schema release branch as we need to progress this today and if not the changes will not be in until the next time we do a release. see: https://github.com/qidane/bioformats/tree/release-2015-01

**Comment by ehrenfeu** [comment]
Sorry if I have been creating additional work - initally I was hesitating to touch the `.xsd` files, but in the end I thought you'd just refuse my PR in case this was a problem...?
@qidane should I split the commit?

**Comment by qidane** [comment]
@ehrenfeu If you could split off the xsd fine changes that would be great and I will cherry-pick your commit.

Thanks!

**Comment by ehrenfeu** [comment]
Hum, I guess I have to open a new PR for this, or what's the best choice to support your workflow?

**Comment by jburel** [comment]
@ehrenfeu: thanks for pointing out the typo (and fixing it)
@qidane the easiest might be to rewrite the commits ourselves and close this PR if that's okay with you @ehrenfeu

**Comment by ehrenfeu** [comment]
Well, I have it in a separate branch anyway already. @jburel I'll close this PR and open a new one.

**Pull request closed without merging**
