### PR TITLE
Make ImageReader defensive against reader errors

### PR DESCRIPTION
**Pull request by joshmoore**
Small programming errors in potential readers (e.g.
a NullPointerException during isThisType) can potentially
cause a file of a different type to become unreadable.
ImageReader should catch all such exceptions and considers
readers that throw such exceptions invalid.

fix gh-3343

### CODE REVIEW

**Comment by melissalinkert** [comment]
Definitely :+1: to making NPE-type issues less burdensome, but does this mean that repo tests will no longer fail on any ```isThisType```-related regressions?

**Comment by joshmoore** [comment]
Hmmm... good point. Shall I add a system property  check? And if so, is there already one that would cover “test running”?

**Comment by melissalinkert** [comment]
I guess a quick fix would be to check the ```testng.directory``` system property, but I don't know that that's a good idea long-term.  Maybe better to add a format-independent ```MetadataOptions``` key and check that (and then update the tests to set the option)?

**Comment by joshmoore** [comment]
Longer-term I could see setting an error handler on the metadata options which could be a step on the path to leniency. I don't see any format-independent options listed on https://docs.openmicroscopy.org/bio-formats/6.0.1/formats/options.html?highlight=options -- prefix with `bioformats.`, `internal.`, ... ?

**Comment by melissalinkert** [comment]
I'd probably lean towards ```bioformats.```, but no really strong opinion.

**Comment by joshmoore** [comment]
Or `core`.

**Comment by melissalinkert** [comment]
The scenario I had in mind was where a reader's ```isThisType``` is changed such that it accidentally throws an exception on a file where it should return ```false```.  For example, a TIFF-based reader checking the value of a particular IFD tag but not checking if the tag is missing.

On second look, you're right that ```FormatReaderTest.testIsThisType``` should be covering that case, though.  No objection to getting this merged.

**Pull request merged**
