### PR TITLE
NetCDF upgrade

### PR DESCRIPTION
**Pull request by sbesson**
Re-opening the effort started in https://github.com/openmicroscopy/bioformats/pull/2938 - see also https://trello.com/c/VrpWk1Fj/119-netcdf-review and discussions in https://github.com/openmicroscopy/bioformats/pull/2928.

At the Bio-Formats level, the primary expectation is that automated tests keep passing especially for all readers using the netcdf service (Minc, Imaris HDF, Veeco). Additionally, this should address known issues with some Imaris IMS files so new files should be included in the testing.

As noted on the previous effort, the biggest known impact might still be at the level of the Bio-Formats/OMERO coupling. Lots of effort are currently put into improving the OMERO 5.5 Java build system and reviewing Java dependencies across the stack (https://github.com/ome/ome-common-java/pull/42, https://github.com/openmicroscopy/bioformats/pull/3335).

### CODE REVIEW

**Comment by mtbc** [comment]
> the biggest known impact might still be at the level of the Bio-Formats/OMERO coupling

@jburel: to get this working I had to exclude `netcdf` from [omero-model's `bufr` dependency](https://github.com/ome/omero-model/blob/v5.5.0-m7/build.gradle#L44).

**Comment by mtbc** [comment]
Apart from the abovementioned exclusion everything seems to me to be working well. I had to tweak rendering settings "max" down for some images to make them not-black and the pixel data thread had to work hard for Dave Mason's `TransFactors_2C_*_IMS3.ims` images but overall things look good in OMERO with this PR.

**Comment by jburel** [comment]
What is the impact of the exclusion? is it a version incompatibility or the dependency is no longer needed by netcdf itself

**Comment by mtbc** [comment]
Without the exclusion I couldn't build openmicroscopy because Ivy wanted NetCDF 4.2.20 which is older than Unidata host so it couldn't retrieve it.

**Comment by sbesson** [comment]
So far, CI testing on sample files had some positive outcome. For instance, Imaris IMS files that failed previously can now be read with the upgrade. Mark also confirmed that it is possible to deploy an OMERO server with this dependency https://github.com/openmicroscopy/bioformats/pull/3358#issuecomment-487919185

Two outstanding issues:

- multi-threaded tests seem to be silently aborted - see [here](https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-folder/66734/console) or [here](https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-folder/67010/console). This behavior does not happen when executed the non-regression tests in a single thread (see [log](https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-folder/66872/console). This might raise problems like segmentation faults during concurrent access.
- as flagged in the original issue, this dependency upgrade breaks the building of OMERO 5.4 with Bio-Formats 6 which has been one of the way Bio-Formats 6 PRs have been reviewed for the past months. Integrating Bio-Formats 6 PRs using the OMERO 5.5 build system in the daily CI is the goal but the infrastructure is still not in-place.

Work has started to resolve the last bit but will not be in place. Excluding this PR to allow the review of Bio-Formats 6.1 candidates.

**Comment by joshmoore** [comment]
@sbesson : is there any way to get access to a failed `target/bio-formats-test-pool-1-thread-9-2019-04-30_02-48-43.log` other than not cleaning up the docker containers?

**Comment by sbesson** [comment]
No easy access at the moment, I am afraid. Archiving the content of `target` might be something we want to look into. Most of the time this was unnecessary as the main log sufficed to replicate the issue. I have executed the tests against `veeco` and attached the logs below:

[bio-formats-test-main-2019-05-01_16-50-28.log](https://github.com/openmicroscopy/bioformats/files/3135040/bio-formats-test-main-2019-05-01_16-50-28.log)
[bio-formats-test-pool-1-thread-1-2019-05-01_16-50-29.log](https://github.com/openmicroscopy/bioformats/files/3135041/bio-formats-test-pool-1-thread-1-2019-05-01_16-50-29.log)
[bio-formats-test-pool-1-thread-2-2019-05-01_16-50-29.log](https://github.com/openmicroscopy/bioformats/files/3135042/bio-formats-test-pool-1-thread-2-2019-05-01_16-50-29.log)
[bio-formats-test-pool-1-thread-3-2019-05-01_16-50-29.log](https://github.com/openmicroscopy/bioformats/files/3135043/bio-formats-test-pool-1-thread-3-2019-05-01_16-50-29.log)

**Comment by sbesson** [comment]
NB: I just realized that the behavior described above is not new - see for example the [log](https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-folder/45405/console) of a  4 months old build.

I still suspect there is still a potential concurrency issues we need to look into. However, this dependency upgrade does not seem to be the culprit. Re-including.

**Pull request merged**
