### PR TITLE
Read Imspector file version 2

### PR DESCRIPTION
**Pull request by bjoernthiel**

### CODE REVIEW

**Comment by bjoernthiel** [comment]
Can we have this delivered as a patch?

**Comment by melissalinkert** [comment]
This reads fine to me - thanks, @bjoernthiel.

Adding the 'include' label so that our CI builds pick this up; assuming no problems, I would expect this to be merged and included in the upcoming 5.1.3 release.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Pull request merged**
