### PR TITLE
getUsedFiles performance fix (develop)

### PR DESCRIPTION
**Pull request by simleo**
Same as #2227, but rebased onto develop.

### CODE REVIEW

**Comment by joshmoore** [comment]
NB: :+1: on having this on develop for more thorough testing. Once that's done, I'd propose opening against `dev_5_1` as a candidate for 5.1.9 (in which case the `metadata` might can be closed)

**Comment by sbesson** [comment]
See the FileStitcher failures on https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/106/. Excluding for now to test #2226

**Comment by simleo** [comment]
Now it should be OK. The problem was in the first section, where I was trying to avoid the useless conversion to set and back to array for the single-series case. Returning `getSeriesUsedFiles`'s result directly does not work because it can be `null`, while `getUsedFiles` is expected to always return an array (possibly empty). Is this difference between the two methods documented anywhere?

**Comment by melissalinkert** [comment]
All looks good and builds are back to normal, so merging this.

The potential for returning null is not documented, unfortunately.  I'd be inclined to clarify the Javadocs so that ```null``` is not allowed, and update any misbehaving readers to return an empty array instead - happy to discuss though.

**Pull request merged**
