### PR TITLE
Joda milliseconds parsing

### PR DESCRIPTION
**Pull request by sbesson**
Follow up of https://github.com/openmicroscopy/bioformats/pull/1734

This PR implements milliseconds handling for `DateTools.formatDate()` and in to the corresponding readers:

- the `DateTools` date parsing logic is largely refactored to migrate all the milllisecond handling and date parsing logic to a new `DateTools.parseDate()`. `DateTools.getTime()` and `DateTools.formatDate()` are modified to call `parseData()` instead of reimplementing the logic.
- `DateTools.formatDate()` methods are added to support a milliseconds separator both for single date format and multiple date formats
- unit tests are added to `DateToolsTest` to cover the semantics and test use cases applies to the readers
- readers using `DateTools.formatDate()` with date formats containing milliseconds are modified to use the new signature handling milliseconds
- for `QuesantReader`a specific workaround is added to add a unique separator between seconds and milliseconds and used the `DateTools.formatDate()`

### CODE REVIEW

**Comment by sbesson** [comment]
From https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-test_images_good/481, the QuesantReader fix requires at least one more commit.

**Comment by melissalinkert** [comment]
All seems fine to me.  Just waiting to merge until all builds are green with the latest commits included.

**Comment by sbesson** [comment]
Commits to come on this PR to fix 2 issues highlighted by the full-repository job:
1- `DateTools.parseDate()`  need to handle more generically date formats with milliseconds following by another pattern e.g. ` AM`, `Z`...

  ```
  [testng] java.lang.NumberFormatException: For input string: "625Z"
   [testng] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_65]
   [testng] 	at java.lang.Long.parseLong(Long.java:441) ~[na:1.7.0_65]
   [testng] 	at java.lang.Long.parseLong(Long.java:483) ~[na:1.7.0_65]
   [testng] 	at loci.common.DateTools.parseDate(DateTools.java:204) ~[formats-common.jar:na]
```
2- some Quesant formats seem to store the date with a separator between seconds and milliseconds, e.g.:

```
[testng] [2015-05-02 13:19:58,240] [pool-1-thread-7] 
   [testng] java.lang.NumberFormatException: For input string: "p77"
   [testng] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_65]
   [testng] 	at java.lang.Long.parseLong(Long.java:441) ~[na:1.7.0_65]
   [testng] 	at java.lang.Long.parseLong(Long.java:483) ~[na:1.7.0_65]
   [testng] 	at loci.common.DateTools.parseDate(DateTools.java:204) ~[formats-common.jar:na]
   [testng] 	at loci.common.DateTools.formatDate(DateTools.java:271) ~[formats-common.jar:na]
   [testng] 	at loci.common.DateTools.formatDate(DateTools.java:246) ~[formats-common.jar:na]
   [testng] 	at loci.formats.in.QuesantReader.initFile(QuesantReader.java:131) ~[formats-gpl.jar:na]
 ```

**Comment by melissalinkert** [comment]
Still something weird going on with the Quesant date parsing, see https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/478/consoleText.  Excluding for now.

**Comment by sbesson** [comment]
Last commits should improve the handling of `NumberFormatException` in `DateTools.parseDate()` and prevent `setId()` failures while parsing the date. This should preserve the statu quo with `QuesantReader` i.e. dates with a different format than are not parsed. Removing exclude label to include in tomorrow's merge builds.

**Comment by melissalinkert** [comment]
Builds are looking good now :+1:

**Pull request merged**
