### PR TITLE
Add a NEWS file to the bftools zip

### PR DESCRIPTION
**Pull request by burgerga**
Copy whats-new file to bftools zip as is, but renamed to NEWS.rst

See #2576

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
This looks fine to me and the name is good, and it's all packaged properly.  Looks good to merge; thanks for doing this!

**Comment by hflynn** [comment]
👍

**Comment by rleigh-codelibre** [comment]
The only followup comment would be to ask whether we should repeat this for the other zip archives (matlab, octave), and also for the source releases.

**Comment by sbesson** [comment]
Thanks @burgerga for another contribution, merging. I would agree with https://github.com/openmicroscopy/bioformats/pull/2584#issuecomment-248866028 especially as the Octave package already includes it.

**Pull request merged**
