### PR TITLE
Another round of Nikon ND2 metadata issues

### PR DESCRIPTION
**Pull request by melissalinkert**
Fixes http://trac.openmicroscopy.org/ome/ticket/12548 and http://trac.openmicroscopy.org/ome/ticket/12656.

To test, verify that ```showinf``` or ImageJ show the same dimensions as NIS Elements Viewer for the following files:

* QA 9507
* QA 10100
* QA 10370
* QA 10366

The QA 10366 file should also be checked to verify that PhysicalSizeZ and the channel colors are set correctly (as described in the QA issue).  Builds are expected to remain green.

### CODE REVIEW

**Comment by bramalingam** [comment]
Everything works as expected. But opening the 10366 in ImageJ to check the colours for the Individual channels, had the right colours for the first two channels. The third channel had a red background and the foreground pixels were green(as expected). In the NIS I did not see the red background for that channel? Can you please check that part alone?

**Comment by melissalinkert** [comment]
One more fix pushed.  For QA 10366, the first channel should be gray, the second should be red, and the third should be green - none of the channels should have multiple colors.

**Comment by rleigh-dundee** [comment]
10366: All OK

10370: Dimensionality correct.  Channel names don't correspond to names from spectral loop consistently.  Should be EGFP/TD/EGFP/EGFP/EGFP with colour green/brightfield/green/green/green; actually observed as Channel0/EGFP/EGFP/EGFP/Channel0 with colours white/green/green/green/green

10100: All OK

9507: Dimensionality correct.  Channel names correct.  Channel colours differ: Should be purple/orange/yellow but actually observed as yellow/orange/yellow.

**Comment by melissalinkert** [comment]
Should be all sorted out now.

**Comment by rleigh-dundee** [comment]
All looks fine and good to merge, thanks.

**Comment by melissalinkert** [comment]
One last commit pushed, as f901217 introduced a single test failure in https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/375

**Comment by rleigh-dundee** [comment]
Looks fine, images still correctly named.  Please merge.

**Comment by melissalinkert** [comment]
--no-rebase

**Pull request merged**
