### PR TITLE
Use netcdf.version variable

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/srr1vUFa/22-update-netcdf-dependency

This PR bumps the netcdf dependency to 4.3.22 (should still be Java 6 compatible) and uses a version parameter to simplify further updates.

### CODE REVIEW

**Comment by sbesson** [comment]
Excluding for now, as I need to update the OMERO Ivy logic to consume edu.ucar artifacts from the Unidata Maven repository.

**Comment by sbesson** [comment]
Unexcluding for review.

**Comment by sbesson** [comment]
Discussed with @melissalinkert, I am not sure this PR actually brings much overall. Despite `netcdf 4.3.22` being in Maven Central, its parent POM `thredds-parent 4.3.22` is not. Removing the `unidata.releases` repositories from all `pom.xml`, cleaning up `~/.m2/repositories/edu*` and running `$ mvn` results in:

```
[ERROR] Failed to execute goal on project formats-gpl: Could not resolve dependencies for project ome:formats-gpl:jar:5.1.5-SNAPSHOT: Failed to collect dependencies at edu.ucar:netcdf:jar:4.3.22: Failed to read artifact descriptor for edu.ucar:netcdf:jar:4.3.22: Could not find artifact edu.ucar:thredds-parent:pom:4.3.22 in ome.snapshots (http://artifacts.openmicroscopy.org/artifactory/ome.snapshots) -> [Help 
```

I'll reduce this PR to a simple cleanup to use `${netcdf.version}`.

**Comment by hflynn** [comment]
Assuming https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/1084/warnings3Result/ is related to this, can you make sure that is fixed at the same time if it will otherwise remain an issue, please? Thanks.

**Comment by sbesson** [comment]
Last commit should also fix the merge docs warnings since we are not changing the version of the JAR anymore

**Comment by hflynn** [comment]
:+1:

**Comment by jburel** [comment]
* in components/formats-gpl/src/loci/formats/services/NetCDFServiceImpl.java version variable is not used.
* Do we also want to improve the handling of the version in java-library.txt?

**Comment by sbesson** [comment]
Propagating build properties inside the Java classes themselves or the documentation requires some infrastructure. In this first case, I do not even think we have a proper solution (cf version number bump in the UpgradeChecker). I would be inclined to drive this maintenance via the documentation as the linkcheck will warn us if the linked JAR are not modified. Concrete proposal would be to remove the line https://github.com/openmicroscopy/bioformats/blob/v5.1.4/components/formats-gpl/src/loci/formats/services/NetCDFServiceImpl.java#L66. Thoughts?

**Comment by sbesson** [comment]
Discussed with @melissalinkert, closing this ticket in favor of a broader discussion about the HDF5 library to use in Bio-Formats 5.2.0 - see https://trello.com/c/IsKUcIPR.

**Pull request closed without merging**
