### PR TITLE
Add lavisionbiotech.com to ignore list

### PR DESCRIPTION
**Pull request by hflynn**
This link is breaking the merge docs currently but I'd assume the failure is temporary given the last thing on their twitter account is news of a new website design at this same URL. Adding it to the ignore list for now to get the build green for the release review.

### CODE REVIEW

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/992/ green again with this included

**Comment by sbesson** [comment]
With this excluded, https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-docs/994 seems to have been building fine so this might have been transient. Closing and we can reopen if the issue reappears.

**Comment by hflynn** [comment]
The build is complaining about this link again today - we may need to re-open this if a re-run doesn't sort it

**Comment by hflynn** [comment]
Actually, this will conflict if we re-open it now, I'll add a commit to #3043 instead.

**Pull request closed without merging**
