### PR TITLE
Remove sphinx documentation

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Moved to https://github.com/ome/bio-formats-documentation

This is a test for the east-ci, using the decoupled repository.

### CODE REVIEW

**Comment by hflynn** [comment]
This looks fine fetching the branch and poking about locally - the docs are gone, the code build still runs.

We probably want to delete the paragraph at the bottom of the contributing.md file about the autogen format docs but that can be done on a following tidy up PR.

**Comment by hflynn** [comment]
BF builds on the East CI are green too

**Comment by rleigh-codelibre** [comment]
Yes, the contributing docs will also need updating.

**Comment by hflynn** [comment]
👍 Although that can probably wait until we move over the using the new structure

**Pull request closed without merging**
