### PR TITLE
Roi handler update rebase

### PR DESCRIPTION
**Pull request by bramalingam**
This is PR #1442  rebased onto dev_5_0.

To test :

1) Add bioformats_package.jar to your ImageJ plugins folder
2) Open any Image in ImageJ, draw roi's and add them to the ROI Manager.
3) Try exporting images using Plugins-->Bio-Formats-->Bio-Formats Exporter.

This should write the ROI's from the ROI manager to your ome-tiff.

To check :

Using Command line tools :

---. /showinf -nopix -omexml /Users/bramalingam/Desktop/ImageJTest/finalTest.ome.tif

This should show all the ROI's , within "< ROI >" " < /ROI >"

Using Image J : 

Import the Image using Bio-formats Importer (select checkbox "Display ROI's" while import) and check if the ROI Manager is populated with the ROI's (that were drawn earlier).

### CODE REVIEW

**Comment by pwalczysko** [comment]
I had the tickbox on the ``Export ROI`` not ticked - shouldn't it be a default option ?
screen shot 2015-01-28 at 16 08 20

**Comment by pwalczysko** [comment]
Created all  the ROIs in the IJ toolbar via ROI Manager. When exporting, got

```
ImageJ 1.49o; Java 1.6.0_65 [64-bit]; Mac OS X 10.8.5; 1380MB of 6000MB (23%)
 
java.lang.RuntimeException: loci.common.services.ServiceException: java.lang.RuntimeException: ROI missing required ID property.
	at loci.formats.out.OMETiffWriter.close(OMETiffWriter.java:129)
	at loci.plugins.out.Exporter.run(Exporter.java:664)
	at loci.plugins.LociExporter.run(LociExporter.java:77)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:263)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:112)
	at ij.IJ.runUserPlugIn(IJ.java:201)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:695)
Caused by: loci.common.services.ServiceException: java.lang.RuntimeException: ROI missing required ID property.
	at loci.formats.services.OMEXMLServiceImpl.createRoot(OMEXMLServiceImpl.java:367)
	at loci.formats.services.OMEXMLServiceImpl.createOMEXMLMetadata(OMEXMLServiceImpl.java:325)
	at loci.formats.services.OMEXMLServiceImpl.createOMEXMLMetadata(OMEXMLServiceImpl.java:314)
	at loci.formats.out.OMETiffWriter.setupServiceAndMetadata(OMETiffWriter.java:252)
	at loci.formats.out.OMETiffWriter.close(OMETiffWriter.java:100)
	... 9 more
Caused by: java.lang.RuntimeException: ROI missing required ID property.
	at ome.xml.model.ROI.update(ROI.java:168)
	at ome.xml.model.ROI.<init>(ROI.java:119)
	at ome.xml.model.OME.update(OME.java:318)
	at ome.xml.model.OME.<init>(OME.java:140)
	at ome.xml.meta.OMEXMLMetadataRoot.<init>(OMEXMLMetadataRoot.java:72)
	at loci.formats.services.OMEXMLServiceImpl.createRoot(OMEXMLServiceImpl.java:362)
	... 13 more
```

**Comment by bramalingam** [comment]
The default option is "unchecked" for export ROI's in this PR.

**Comment by pwalczysko** [comment]
@bramalingam @jburel : Please try to focus on the provenance of the ROIs problematics. At the present state, we will get crashes in case the ome.tiff will be reopened and new ROIs added (except for some very rare specific occassions with addition of the same type of ROI. Also on OMERO server, when the ome.tiff with the ROIs written into the header is imported, will it be possible to reopen and new ROIs added to it ? It does not seem like a plausible workflow to have ome.tiffs created with first-time-ROIs-only.
This is valid also for 5.1 line.

**Comment by melissalinkert** [comment]
Given that there are still issues here and in the 5.1 line, as well as several PRs that follow on from gh-1442 which are not being rebased, I have concerns about including this for 5.0.7.  Happy to discuss though.

**Comment by pwalczysko** [comment]
Considering the issue https://github.com/openmicroscopy/bioformats/pull/1548#issuecomment-71874517 and having still a crash here to double check tomorrow, I feel that @melissalinkert might be right. It is a very useful feature, but we possibly could have the default workflow set as "use 5.1 bioformats if you want to create ROIs in IJ, you can read them in OMERO 5.0 as well". 
@jburel ?

**Comment by jburel** [comment]
I think we should keep it for 5.1,
Agree that we have several issues related to roi and generation of the ome-tiff files.

**Comment by melissalinkert** [comment]
Closing then - thanks all.

**Comment by jburel** [comment]
@bramalingam: it was still worth the effort i.e. learn how to rebase PRs. Thanks

**Comment by bramalingam** [comment]
Absolutely agree with you guys. Was discussing the same with Petr this evening. 
Will keep working on the develop branch.

**Comment by bramalingam** [comment]
--no-rebase

**Pull request closed without merging**
