### PR TITLE
Allow for simpler fake plate definition

### PR DESCRIPTION
**Pull request by ximenesuk**
This change allows for fake plates to be created by simply having one of the relevant keys in the name set to 1 or more. All non-set keys are then assumed to be equal to 1. See https://trello.com/c/f9tTxVFz/372-improve-fake-parameter-handling

Thus,
```
SPW&plates=1.fake
SPW&plates=1&plateRows=1&plateCols=1&plateAcqs=1&fields=1.fake
```
would both generate the same plate form.

I'm not sure how best to test this. I have done so locally using the breaking build of OMERO - and in fact the fake plate tests in https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/test/integration/clitest/test_import.py in that build should pass with this PR included in Bio-Formats. The Bio-Formats unit tests can't easily be changed to test this as they don't appear to test filename-style fakes. Any other testing suggestions welcome.

If this is mergeable then the now merged docs PR, https://github.com/openmicroscopy/bioformats/pull/2170, will need an additional PR.

### CODE REVIEW

**Comment by sbesson** [comment]
Tested a few potential keys. All seems to work as expected

```
sbesson@ls30630:bftools $ ./showinf -version
Version: 5.2.0-DEV
VCS revision: 37c896a5d3be2d3b900708eccd5cac0b6fb7270e
Build date: 15 January 2016
sbesson@ls30630:bftools $ ./showinf -nopix -omexml-only "SPW&plates=1&plateRows=1&plateCols=1&plateAcqs=1&fields=1.fake"
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0 http://www.openmicroscopy.org/Schemas/OME/2016-DEV0/ome.xsd">
   <Experiment ID="Experiment:0" Type="Photobleaching">
      <Description>Experiment</Description>
      <MicrobeamManipulation ID="MicrobeamManipulation:0" Type="FLIP">
         <Description>Manipulation #0</Description>
         <ROIRef ID="ROI:0"/>
         <ExperimenterRef ID="Experimenter:0"/>
         <LightSourceSettings Attenuation="1.0" ID="LightSource:4" Wavelength="200.2" WavelengthUnit="nm"/>
      </MicrobeamManipulation>
   </Experiment>
   <Plate ColumnNamingConvention="number" Columns="1" ExternalIdentifier="External Identifier" ID="Plate:0" Name="Plate Name 0" RowNamingConvention="letter" Rows="1" Status="Plate status" WellOriginX="0.0" WellOriginXUnit="µm" WellOriginY="1.0" WellOriginYUnit="µm">
      <Description>Plate 0 of 1</Description>
      <Well Color="255" Column="0" ExternalDescription="External Description" ExternalIdentifier="External Identifier" ID="Well:0_0_0_0" Row="0" Type="Transfection: done">
         <WellSample ID="WellSample:0_0_0_0_0_0" Index="0" PositionX="0.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" Timepoint="2006-05-04T18:13:51">
            <ImageRef ID="Image:0"/>
         </WellSample>
      </Well>
      <PlateAcquisition EndTime="2006-05-04T18:13:51" ID="PlateAcquisition:0" Name="PlateAcquisition Name 0" StartTime="2006-05-04T18:13:51">
         <Description>PlateAcquisition 0 of 1</Description>
         <WellSampleRef ID="WellSample:0_0_0_0_0_0"/>
      </PlateAcquisition>
   </Plate>
   <Screen ID="Screen:0" Name="Screen Name 0">
      <Description>Screen Description 0</Description>
      <PlateRef ID="Plate:0"/>
   </Screen>
   <Experimenter ID="Experimenter:0"/>
   <Instrument ID="Instrument:0">
      <Microscope LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="Upright"/>
      <LightSource ID="LightSource:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <LightSource ID="LightSource:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Arc Type="HgXe"/>
      </LightSource>
      <LightSource ID="LightSource:2" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Filament Type="Halogen"/>
      </LightSource>
      <LightSource ID="LightSource:3" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <LightEmittingDiode/>
      </LightSource>
      <LightSource ID="LightSource:4" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <Detector AmplificationGain="0.0" Gain="1.0" ID="Detector:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Offset="2.0" SerialNumber="0123456789" Type="CCD" Voltage="100" VoltageUnit="V" Zoom="3.0"/>
      <Objective CalibratedMagnification="1.0" Correction="UV" ID="Objective:0" Immersion="Oil" Iris="true" LensNA="0.5" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" NominalMagnification="1.5" SerialNumber="0123456789" WorkingDistance="1.0" WorkingDistanceUnit="µm"/>
      <FilterSet ID="FilterSet:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
      <Filter ID="Filter:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Filter ID="Filter:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Dichroic ID="Dichroic:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
   </Instrument>
   <Image ID="Image:0" Name="SPW">
      <Description>Image Description 0</Description>
      <ExperimentRef ID="Experiment:0"/>
      <ImagingEnvironment AirPressure="1.0" AirPressureUnit="mbar" CO2Percent="1.0" Humidity="1.0" Temperature="1.0" TemperatureUnit="°C"/>
      <StageLabel Name="StageLabel" X="1.0" XUnit="reference frame" Y="1.0" YUnit="reference frame" Z="1.0" ZUnit="reference frame"/>
      <Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" PhysicalSizeX="1" PhysicalSizeXUnit="µm" PhysicalSizeY="1" PhysicalSizeYUnit="µm" PhysicalSizeZ="1" PhysicalSizeZUnit="µm" SignificantBits="8" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="uint8">
         <Channel AcquisitionMode="FluorescenceLifetime" Color="1687603455" ContrastMethod="Brightfield" EmissionWavelength="300.3" EmissionWavelengthUnit="nm" ExcitationWavelength="400.3" ExcitationWavelengthUnit="nm" Fluor="Fluor" ID="Channel:0:0" IlluminationType="Oblique" NDFilter="1.0" Name="Name" PinholeSize="0.5" PinholeSizeUnit="µm" PockelCellSetting="0" SamplesPerPixel="1">
            <LightSourceSettings Attenuation="1.0" ID="LightSource:0" Wavelength="200.2" WavelengthUnit="nm"/>
            <DetectorSettings Binning="2x2" Gain="1.0" ID="Detector:0" Integration="20" Offset="1.0" ReadOutRate="1.0" ReadOutRateUnit="Hz" Voltage="1.0" VoltageUnit="V" Zoom="3.0"/>
            <LightPath>
               <ExcitationFilterRef ID="Filter:1"/>
               <DichroicRef ID="Dichroic:0"/>
               <EmissionFilterRef ID="Filter:0"/>
            </LightPath>
         </Channel>
         <MetadataOnly/>
         <Plane DeltaT="0.1" DeltaTUnit="s" ExposureTime="10.0" ExposureTimeUnit="s" PositionX="1.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" PositionZ="1.0" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0">
            <HashSHA1>1234567890ABCDEF1234567890ABCDEF12345678</HashSHA1>
         </Plane>
      </Pixels>
   </Image>
   <ROI ID="ROI:0" Name="ROI name:0">
      <Union>
         <Shape FillColor="100" ID="Shape:0:0" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Line X1="0.0" X2="1.0" Y1="0.0" Y2="1.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:1" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Point X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:3" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Rectangle Height="10.0" Width="10.0" X="0.0" Y="0.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:6" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Ellipse RadiusX="1.0" RadiusY="1.0" X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:10" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Polyline Points="0,0 10,10"/>
         </Shape>
      </Union>
   </ROI>
</OME>

sbesson@ls30630:bftools $ ./showinf -nopix -omexml-only "SPW&plates=1.fake"
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0 http://www.openmicroscopy.org/Schemas/OME/2016-DEV0/ome.xsd">
   <Experiment ID="Experiment:0" Type="Photobleaching">
      <Description>Experiment</Description>
      <MicrobeamManipulation ID="MicrobeamManipulation:0" Type="FLIP">
         <Description>Manipulation #0</Description>
         <ROIRef ID="ROI:0"/>
         <ExperimenterRef ID="Experimenter:0"/>
         <LightSourceSettings Attenuation="1.0" ID="LightSource:4" Wavelength="200.2" WavelengthUnit="nm"/>
      </MicrobeamManipulation>
   </Experiment>
   <Plate ColumnNamingConvention="number" Columns="1" ExternalIdentifier="External Identifier" ID="Plate:0" Name="Plate Name 0" RowNamingConvention="letter" Rows="1" Status="Plate status" WellOriginX="0.0" WellOriginXUnit="µm" WellOriginY="1.0" WellOriginYUnit="µm">
      <Description>Plate 0 of 1</Description>
      <Well Color="255" Column="0" ExternalDescription="External Description" ExternalIdentifier="External Identifier" ID="Well:0_0_0_0" Row="0" Type="Transfection: done">
         <WellSample ID="WellSample:0_0_0_0_0_0" Index="0" PositionX="0.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" Timepoint="2006-05-04T18:13:51">
            <ImageRef ID="Image:0"/>
         </WellSample>
      </Well>
      <PlateAcquisition EndTime="2006-05-04T18:13:51" ID="PlateAcquisition:0" Name="PlateAcquisition Name 0" StartTime="2006-05-04T18:13:51">
         <Description>PlateAcquisition 0 of 1</Description>
         <WellSampleRef ID="WellSample:0_0_0_0_0_0"/>
      </PlateAcquisition>
   </Plate>
   <Screen ID="Screen:0" Name="Screen Name 0">
      <Description>Screen Description 0</Description>
      <PlateRef ID="Plate:0"/>
   </Screen>
   <Experimenter ID="Experimenter:0"/>
   <Instrument ID="Instrument:0">
      <Microscope LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="Upright"/>
      <LightSource ID="LightSource:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <LightSource ID="LightSource:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Arc Type="HgXe"/>
      </LightSource>
      <LightSource ID="LightSource:2" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Filament Type="Halogen"/>
      </LightSource>
      <LightSource ID="LightSource:3" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <LightEmittingDiode/>
      </LightSource>
      <LightSource ID="LightSource:4" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <Detector AmplificationGain="0.0" Gain="1.0" ID="Detector:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Offset="2.0" SerialNumber="0123456789" Type="CCD" Voltage="100" VoltageUnit="V" Zoom="3.0"/>
      <Objective CalibratedMagnification="1.0" Correction="UV" ID="Objective:0" Immersion="Oil" Iris="true" LensNA="0.5" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" NominalMagnification="1.5" SerialNumber="0123456789" WorkingDistance="1.0" WorkingDistanceUnit="µm"/>
      <FilterSet ID="FilterSet:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
      <Filter ID="Filter:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Filter ID="Filter:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Dichroic ID="Dichroic:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
   </Instrument>
   <Image ID="Image:0" Name="SPW">
      <Description>Image Description 0</Description>
      <ExperimentRef ID="Experiment:0"/>
      <ImagingEnvironment AirPressure="1.0" AirPressureUnit="mbar" CO2Percent="1.0" Humidity="1.0" Temperature="1.0" TemperatureUnit="°C"/>
      <StageLabel Name="StageLabel" X="1.0" XUnit="reference frame" Y="1.0" YUnit="reference frame" Z="1.0" ZUnit="reference frame"/>
      <Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" PhysicalSizeX="1" PhysicalSizeXUnit="µm" PhysicalSizeY="1" PhysicalSizeYUnit="µm" PhysicalSizeZ="1" PhysicalSizeZUnit="µm" SignificantBits="8" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="uint8">
         <Channel AcquisitionMode="FluorescenceLifetime" Color="1687603455" ContrastMethod="Brightfield" EmissionWavelength="300.3" EmissionWavelengthUnit="nm" ExcitationWavelength="400.3" ExcitationWavelengthUnit="nm" Fluor="Fluor" ID="Channel:0:0" IlluminationType="Oblique" NDFilter="1.0" Name="Name" PinholeSize="0.5" PinholeSizeUnit="µm" PockelCellSetting="0" SamplesPerPixel="1">
            <LightSourceSettings Attenuation="1.0" ID="LightSource:0" Wavelength="200.2" WavelengthUnit="nm"/>
            <DetectorSettings Binning="2x2" Gain="1.0" ID="Detector:0" Integration="20" Offset="1.0" ReadOutRate="1.0" ReadOutRateUnit="Hz" Voltage="1.0" VoltageUnit="V" Zoom="3.0"/>
            <LightPath>
               <ExcitationFilterRef ID="Filter:1"/>
               <DichroicRef ID="Dichroic:0"/>
               <EmissionFilterRef ID="Filter:0"/>
            </LightPath>
         </Channel>
         <MetadataOnly/>
         <Plane DeltaT="0.1" DeltaTUnit="s" ExposureTime="10.0" ExposureTimeUnit="s" PositionX="1.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" PositionZ="1.0" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0">
            <HashSHA1>1234567890ABCDEF1234567890ABCDEF12345678</HashSHA1>
         </Plane>
      </Pixels>
   </Image>
   <ROI ID="ROI:0" Name="ROI name:0">
      <Union>
         <Shape FillColor="100" ID="Shape:0:0" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Line X1="0.0" X2="1.0" Y1="0.0" Y2="1.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:1" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Point X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:3" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Rectangle Height="10.0" Width="10.0" X="0.0" Y="0.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:6" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Ellipse RadiusX="1.0" RadiusY="1.0" X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:10" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Polyline Points="0,0 10,10"/>
         </Shape>
      </Union>
   </ROI>
</OME>

sbesson@ls30630:bftools $ ./showinf -nopix -omexml-only "SPW&plateAcqs=1.fake"
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0 http://www.openmicroscopy.org/Schemas/OME/2016-DEV0/ome.xsd">
   <Experiment ID="Experiment:0" Type="Photobleaching">
      <Description>Experiment</Description>
      <MicrobeamManipulation ID="MicrobeamManipulation:0" Type="FLIP">
         <Description>Manipulation #0</Description>
         <ROIRef ID="ROI:0"/>
         <ExperimenterRef ID="Experimenter:0"/>
         <LightSourceSettings Attenuation="1.0" ID="LightSource:4" Wavelength="200.2" WavelengthUnit="nm"/>
      </MicrobeamManipulation>
   </Experiment>
   <Plate ColumnNamingConvention="number" Columns="1" ExternalIdentifier="External Identifier" ID="Plate:0" Name="Plate Name 0" RowNamingConvention="letter" Rows="1" Status="Plate status" WellOriginX="0.0" WellOriginXUnit="µm" WellOriginY="1.0" WellOriginYUnit="µm">
      <Description>Plate 0 of 1</Description>
      <Well Color="255" Column="0" ExternalDescription="External Description" ExternalIdentifier="External Identifier" ID="Well:0_0_0_0" Row="0" Type="Transfection: done">
         <WellSample ID="WellSample:0_0_0_0_0_0" Index="0" PositionX="0.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" Timepoint="2006-05-04T18:13:51">
            <ImageRef ID="Image:0"/>
         </WellSample>
      </Well>
      <PlateAcquisition EndTime="2006-05-04T18:13:51" ID="PlateAcquisition:0" Name="PlateAcquisition Name 0" StartTime="2006-05-04T18:13:51">
         <Description>PlateAcquisition 0 of 1</Description>
         <WellSampleRef ID="WellSample:0_0_0_0_0_0"/>
      </PlateAcquisition>
   </Plate>
   <Screen ID="Screen:0" Name="Screen Name 0">
      <Description>Screen Description 0</Description>
      <PlateRef ID="Plate:0"/>
   </Screen>
   <Experimenter ID="Experimenter:0"/>
   <Instrument ID="Instrument:0">
      <Microscope LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="Upright"/>
      <LightSource ID="LightSource:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <LightSource ID="LightSource:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Arc Type="HgXe"/>
      </LightSource>
      <LightSource ID="LightSource:2" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Filament Type="Halogen"/>
      </LightSource>
      <LightSource ID="LightSource:3" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <LightEmittingDiode/>
      </LightSource>
      <LightSource ID="LightSource:4" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Power="200.0" PowerUnit="mW" SerialNumber="0123456789">
         <Laser FrequencyMultiplication="30" LaserMedium="Alexandrite" PockelCell="false" RepetitionRate="30.0" RepetitionRateUnit="aHz" Tuneable="false" Type="Dye" Wavelength="200.0" WavelengthUnit="nm"/>
      </LightSource>
      <Detector AmplificationGain="0.0" Gain="1.0" ID="Detector:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" Offset="2.0" SerialNumber="0123456789" Type="CCD" Voltage="100" VoltageUnit="V" Zoom="3.0"/>
      <Objective CalibratedMagnification="1.0" Correction="UV" ID="Objective:0" Immersion="Oil" Iris="true" LensNA="0.5" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" NominalMagnification="1.5" SerialNumber="0123456789" WorkingDistance="1.0" WorkingDistanceUnit="µm"/>
      <FilterSet ID="FilterSet:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
      <Filter ID="Filter:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Filter ID="Filter:1" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789" Type="LongPass">
         <TransmittanceRange CutIn="200.0" CutInTolerance="1.0" CutInToleranceUnit="nm" CutInUnit="nm" CutOut="300.0" CutOutTolerance="1.0" CutOutToleranceUnit="nm" CutOutUnit="nm" Transmittance="0.5"/>
      </Filter>
      <Dichroic ID="Dichroic:0" LotNumber="9876543210" Manufacturer="Manufacturer" Model="Model" SerialNumber="0123456789"/>
   </Instrument>
   <Image ID="Image:0" Name="SPW">
      <Description>Image Description 0</Description>
      <ExperimentRef ID="Experiment:0"/>
      <ImagingEnvironment AirPressure="1.0" AirPressureUnit="mbar" CO2Percent="1.0" Humidity="1.0" Temperature="1.0" TemperatureUnit="°C"/>
      <StageLabel Name="StageLabel" X="1.0" XUnit="reference frame" Y="1.0" YUnit="reference frame" Z="1.0" ZUnit="reference frame"/>
      <Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" PhysicalSizeX="1" PhysicalSizeXUnit="µm" PhysicalSizeY="1" PhysicalSizeYUnit="µm" PhysicalSizeZ="1" PhysicalSizeZUnit="µm" SignificantBits="8" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="uint8">
         <Channel AcquisitionMode="FluorescenceLifetime" Color="1687603455" ContrastMethod="Brightfield" EmissionWavelength="300.3" EmissionWavelengthUnit="nm" ExcitationWavelength="400.3" ExcitationWavelengthUnit="nm" Fluor="Fluor" ID="Channel:0:0" IlluminationType="Oblique" NDFilter="1.0" Name="Name" PinholeSize="0.5" PinholeSizeUnit="µm" PockelCellSetting="0" SamplesPerPixel="1">
            <LightSourceSettings Attenuation="1.0" ID="LightSource:0" Wavelength="200.2" WavelengthUnit="nm"/>
            <DetectorSettings Binning="2x2" Gain="1.0" ID="Detector:0" Integration="20" Offset="1.0" ReadOutRate="1.0" ReadOutRateUnit="Hz" Voltage="1.0" VoltageUnit="V" Zoom="3.0"/>
            <LightPath>
               <ExcitationFilterRef ID="Filter:1"/>
               <DichroicRef ID="Dichroic:0"/>
               <EmissionFilterRef ID="Filter:0"/>
            </LightPath>
         </Channel>
         <MetadataOnly/>
         <Plane DeltaT="0.1" DeltaTUnit="s" ExposureTime="10.0" ExposureTimeUnit="s" PositionX="1.0" PositionXUnit="reference frame" PositionY="1.0" PositionYUnit="reference frame" PositionZ="1.0" PositionZUnit="reference frame" TheC="0" TheT="0" TheZ="0">
            <HashSHA1>1234567890ABCDEF1234567890ABCDEF12345678</HashSHA1>
         </Plane>
      </Pixels>
   </Image>
   <ROI ID="ROI:0" Name="ROI name:0">
      <Union>
         <Shape FillColor="100" ID="Shape:0:0" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Line X1="0.0" X2="1.0" Y1="0.0" Y2="1.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:1" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Point X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:3" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Rectangle Height="10.0" Width="10.0" X="0.0" Y="0.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:6" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Ellipse RadiusX="1.0" RadiusY="1.0" X="2.0" Y="2.0"/>
         </Shape>
         <Shape FillColor="100" ID="Shape:0:10" StrokeColor="100" TheC="0" TheT="0" TheZ="0">
            <Polyline Points="0,0 10,10"/>
         </Shape>
      </Union>
   </ROI>
</OME>
```

This raises the consistency question of whether `screens` should be remain a no-op if none of the SPW keys are set. A (breaking) possibility would be to set the default value of `screens` to 0 and have `SPW&platest=1.fake` semantically equivalent to `SPW&plates=1&screens=0.fake`.

```
sbesson@ls30630:bftools $ ./showinf -nopix -omexml-only "SPW&screens=1.fake"
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-DEV0 http://www.openmicroscopy.org/Schemas/OME/2016-DEV0/ome.xsd">
   <Image ID="Image:0" Name="SPW">
      <Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" SignificantBits="8" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="uint8">
         <Channel ID="Channel:0:0" SamplesPerPixel="1">
            <LightPath/>
         </Channel>
         <MetadataOnly/>
      </Pixels>
   </Image>
</OME>
```

Also I am not clear where the `ROI` additions come from when creating fake screens. However this is likely something we will revisit as part of the ROI model work /cc @dgault @mtbc

**Comment by ximenesuk** [comment]
@sbesson  screens were always inconsistent! But, yes, they could be brought into line here if that breaking chnage was okay. /cc @melissalinkert

This would break tests currently in the OMERO develop line though those could be fixed in my open import templates PR as those tests are touched there anyhow.

**Comment by ximenesuk** [comment]
@sbesson The ROI is created here: https://github.com/openmicroscopy/bioformats/blob/develop/components/specification/src/ome/specification/XMLMockObjects.java#L936

**Comment by sbesson** [comment]
@ximenesuk: agreed about the inconsistency and certainly not blaming this PR for it. If @melissalinkert and others agree, I would propose to unify this behavior right now as we are starting breaking work as follows:
- at the Bio-Formats level, let `screens` behave like other HCS keys i.e. default to 0 and have non-0 values sufficient to toggle HCS
- have the following mapping

 ```
SPW.fake  % single image
SPW&screens=1.fake  % one screen, one plate
SPW&plates=1.fake  % one orphaned plate
```
- at the OMERO level, modify the SPW fake imports to pass explicitly `SPW&screens=1&plates...` for now
- eventually clean up the rest of the default key/values on the OMERO 5.3 branch

**Comment by melissalinkert** [comment]
All makes sense - no objections here.

**Comment by ximenesuk** [comment]
Thanks both. I'll modify and try to push for Monday.

**Comment by sbesson** [comment]
Note also this PR is failing the automated tests for `plate&plateRows=8&plateCols=12&fields=2&annMap=3.fake` (see https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/40) so a companion data_repo configuration PR will need to be opened for this fake file.

**Comment by ximenesuk** [comment]
Once tests are okay I need to modify the docs for this last commit. I'll add to this PR unless you'd prefer docs in a separate PR.

**Comment by sbesson** [comment]
Retested using today's merge build. Everything works as expected. As the `fake` tests are green in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-repository-subset/90/, getting this in.

**Pull request merged**
