### PR TITLE
Add ROI's to an existing ome-tiff which already has ROI's 

### PR DESCRIPTION
**Pull request by bramalingam**
To test,

1) Import an ome-tiff which already has ROI's using the Bioformats_Importer.
2) Clear the list of ROI's in the ROIManger.
3) Draw new ROI's and add them to the ROIManager.
4) Export as ome-tiff using the the Bioformats exporter (with the export roi's checkbox selected).
5) Now reimport the saved image using Plugins > Bio-formats > Bio-formats Importer (“Please select the following checkboxes, "Display ROIs","Display OME-XML metadata" and "Display Metadata” in the bioformats-importer options)

This should have the old and new ROI's.

### CODE REVIEW

**Comment by jburel** [comment]
When the image is opened, the rois are displayed in the data manager. 
If I deleted the rois from the data manager then export the file and override it.
The "deleted" rois are still there. This is confusing

Another point noticed, we should by default select Show all in roi manager when opening it with ROIs

**Comment by bramalingam** [comment]
@jburel : I have pushed 2 commits to handle the issues stated above.

**Comment by jburel** [comment]
@bramalingam: you have 2 branches with almost the same name
RoiHandler_ome-tiff_provenance and ROIHandler_ome-tiff_provenance
Are you sure you pushed to the correct one?

**Comment by bramalingam** [comment]
replaced by https://github.com/openmicroscopy/bioformats/pull/1566

**Pull request closed without merging**
