### PR TITLE
Formats-GPL: Initial warnings cleanup

### PR DESCRIPTION
**Pull request by dgault**
This is part of the work to review the resources of various components for potential resource leaks.
As part of this I have completed an initial pass of the formats-gpl component and reviewed any warnings.

This PR cleans up some simple warnings throughout covering the following:
- Remove unused imports
- Remove some unused variables
- Provide parameters for some generic types
- Close resources which are left open

This is by no means an extensive or complete cleanup of warnings, simply some initial cleanup which would be easy and safe while identifying potential resource leaks.

To test:
All builds and tests should remain green

### CODE REVIEW

**Comment by melissalinkert** [comment]
Will the removal of variables in ```CellH5Reader```, ```GatanReader```, ```LeicaHandler```, and ```OpenlabReader``` require memo files to be regenerated?  Definitely :+1: to cleaning those up, I just wonder if it requires a minor release?

**Comment by sbesson** [comment]
Interesting thought raised in https://github.com/openmicroscopy/bioformats/pull/2767#issuecomment-282797131. A few comments:

- although we have no official enforcement re serialization as per out current [policy](https://www.openmicroscopy.org/site/support/bio-formats5.3/about/index.html#versioning-policy), incrementing the minor version number for such a code-wide cleanup is a sensible idea
- in terms of timelines, we should certainly aim at encapsulating the largest number of serialization breakages before we release OMERO 5.3.0 /cc @jburel 

I would suggest we review the state of this work on Wednesday afternoon and discuss our various options.

**Comment by sbesson** [comment]
Discussed https://github.com/openmicroscopy/bioformats/pull/2767#issuecomment-282797131 today and we'll indeed call this a minor version increment. Anything else to raise @melissalinkert or are we good to go with this PR?

**Comment by melissalinkert** [comment]
All fine with me.

**Pull request merged**
